package digota

type Charge struct {
	Id               string    `json:"id,omitempty" bson:"Id"`
	Statement        string    `json:"statement,omitempty" bson:"Statement"`
	ChargeAmount     uint64    `json:"charge_amount,omitempty" bson:"ChargeAmount"`
	RefundAmount     uint64    `json:"refund_amount,omitempty" bson:"RefundAmount"`
	Refunds          []*Refund `json:"refunds,omitempty" bson:"Refunds"`
	Currency         int32     `json:"currency,omitempty" bson:"Currency"`
	Email            string    `json:"email,omitempty" bson:"Email"`
	Paid             bool      `json:"paid,omitempty" bson:"Paid"`
	Refunded         bool      `json:"refunded,omitempty" bson:"Refunded"`
	ProviderId       int32     `json:"provider_id,omitempty" bson:"ProviderId"`
	ProviderChargeId string    `json:"provider_charge_id,omitempty" bson:"ProviderChargeId"`
	Created          int64     `json:"created,omitempty" bson:"Created"`
	Updated          int64     `json:"updated,omitempty" bson:"Updated"`
}

type Refund struct {
	RefundAmount     uint64 `json:"refund_amount,omitempty" bson:"RefundAmount"`
	ProviderRefundId string `json:"provider_refund_id,omitempty" bson:"ProviderRefundId"`
	Reason           int32  `json:"reason,omitempty" bson:"Reason"`
	Created          int64  `json:"created,omitempty" bson:"Created"`
}

var Currency_name = map[int32]string{
	0:   "CUR_RESERVED",
	1:   "AFN",
	2:   "ALL",
	3:   "AMD",
	4:   "ANG",
	5:   "ARS",
	6:   "AUD",
	7:   "AWG",
	8:   "AZN",
	9:   "BAM",
	10:  "BBD",
	11:  "BGN",
	12:  "BHD",
	13:  "BMD",
	14:  "BND",
	15:  "BOB",
	16:  "BRL",
	17:  "BSD",
	18:  "BWP",
	19:  "BYN",
	20:  "BYR",
	21:  "BZD",
	22:  "CAD",
	23:  "CLP",
	24:  "CNY",
	25:  "COP",
	26:  "CRC",
	27:  "CUP",
	28:  "CZK",
	29:  "DKK",
	30:  "DOP",
	31:  "DZD",
	32:  "EEK",
	33:  "EGP",
	34:  "EUR",
	35:  "FJD",
	36:  "FKP",
	37:  "GBP",
	38:  "GGP",
	39:  "GHC",
	40:  "GIP",
	41:  "GTQ",
	42:  "GYD",
	43:  "HKD",
	44:  "HNL",
	45:  "HRK",
	46:  "HUF",
	47:  "IDR",
	48:  "ILS",
	49:  "IMP",
	50:  "INR",
	51:  "IQD",
	52:  "IRR",
	53:  "ISK",
	54:  "JEP",
	55:  "JMD",
	56:  "JOD",
	57:  "JPY",
	58:  "KES",
	59:  "KGS",
	60:  "KHR",
	61:  "KPW",
	62:  "KRW",
	63:  "KWD",
	64:  "KYD",
	65:  "KZT",
	66:  "LAK",
	67:  "LBP",
	68:  "LKR",
	69:  "LRD",
	70:  "LTL",
	71:  "LVL",
	72:  "LYD",
	73:  "MAD",
	74:  "MKD",
	75:  "MNT",
	76:  "MUR",
	77:  "MXN",
	78:  "MWK",
	79:  "MYR",
	80:  "MZN",
	81:  "NAD",
	82:  "NGN",
	83:  "NIO",
	84:  "NOK",
	85:  "NPR",
	86:  "NZD",
	87:  "OMR",
	88:  "PAB",
	89:  "PEN",
	90:  "PHP",
	91:  "PKR",
	92:  "PLN",
	93:  "PYG",
	94:  "QAR",
	95:  "RON",
	96:  "RSD",
	97:  "RUB",
	98:  "RUR",
	99:  "SAR",
	100: "SBD",
	101: "SCR",
	102: "SEK",
	103: "SGD",
	104: "SHP",
	105: "SOS",
	106: "SRD",
	107: "SVC",
	108: "SYP",
	109: "THB",
	110: "TND",
	111: "TRL",
	112: "TRY",
	113: "TTD",
	114: "TWD",
	115: "TZS",
	116: "UAH",
	117: "UGX",
	118: "AED",
	119: "UYU",
	120: "UZS",
	121: "VEF",
	122: "VND",
	123: "XCD",
	124: "YER",
	125: "ZAR",
	126: "ZMW",
	127: "ZWD",
	128: "USD",
}
var Currency_value = map[string]int32{
	"CUR_RESERVED": 0,
	"AFN":          1,
	"ALL":          2,
	"AMD":          3,
	"ANG":          4,
	"ARS":          5,
	"AUD":          6,
	"AWG":          7,
	"AZN":          8,
	"BAM":          9,
	"BBD":          10,
	"BGN":          11,
	"BHD":          12,
	"BMD":          13,
	"BND":          14,
	"BOB":          15,
	"BRL":          16,
	"BSD":          17,
	"BWP":          18,
	"BYN":          19,
	"BYR":          20,
	"BZD":          21,
	"CAD":          22,
	"CLP":          23,
	"CNY":          24,
	"COP":          25,
	"CRC":          26,
	"CUP":          27,
	"CZK":          28,
	"DKK":          29,
	"DOP":          30,
	"DZD":          31,
	"EEK":          32,
	"EGP":          33,
	"EUR":          34,
	"FJD":          35,
	"FKP":          36,
	"GBP":          37,
	"GGP":          38,
	"GHC":          39,
	"GIP":          40,
	"GTQ":          41,
	"GYD":          42,
	"HKD":          43,
	"HNL":          44,
	"HRK":          45,
	"HUF":          46,
	"IDR":          47,
	"ILS":          48,
	"IMP":          49,
	"INR":          50,
	"IQD":          51,
	"IRR":          52,
	"ISK":          53,
	"JEP":          54,
	"JMD":          55,
	"JOD":          56,
	"JPY":          57,
	"KES":          58,
	"KGS":          59,
	"KHR":          60,
	"KPW":          61,
	"KRW":          62,
	"KWD":          63,
	"KYD":          64,
	"KZT":          65,
	"LAK":          66,
	"LBP":          67,
	"LKR":          68,
	"LRD":          69,
	"LTL":          70,
	"LVL":          71,
	"LYD":          72,
	"MAD":          73,
	"MKD":          74,
	"MNT":          75,
	"MUR":          76,
	"MXN":          77,
	"MWK":          78,
	"MYR":          79,
	"MZN":          80,
	"NAD":          81,
	"NGN":          82,
	"NIO":          83,
	"NOK":          84,
	"NPR":          85,
	"NZD":          86,
	"OMR":          87,
	"PAB":          88,
	"PEN":          89,
	"PHP":          90,
	"PKR":          91,
	"PLN":          92,
	"PYG":          93,
	"QAR":          94,
	"RON":          95,
	"RSD":          96,
	"RUB":          97,
	"RUR":          98,
	"SAR":          99,
	"SBD":          100,
	"SCR":          101,
	"SEK":          102,
	"SGD":          103,
	"SHP":          104,
	"SOS":          105,
	"SRD":          106,
	"SVC":          107,
	"SYP":          108,
	"THB":          109,
	"TND":          110,
	"TRL":          111,
	"TRY":          112,
	"TTD":          113,
	"TWD":          114,
	"TZS":          115,
	"UAH":          116,
	"UGX":          117,
	"AED":          118,
	"UYU":          119,
	"UZS":          120,
	"VEF":          121,
	"VND":          122,
	"XCD":          123,
	"YER":          124,
	"ZAR":          125,
	"ZMW":          126,
	"ZWD":          127,
	"USD":          128,
}

type Card struct {
	Number      string
	ExpireMonth string
	ExpireYear  string
	FirstName   string
	LastName    string
	CVC         string
	Type        int32
}

type ListRequest struct {
	Page  int64
	Limit int64
	Sort  int32
}

type ChargeList struct {
	Charges []Charge
	Total   int32
}
