// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service298Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service298 interface {
	Method298(ctx context.Context, id string, data string, datatwo string) (Service298Data, error)
	MethodOther298(ctx context.Context, id string, data string, datatwo string) (Service298Data, error)
	MethodOtherOther298(ctx context.Context, id string, data string, datatwo string) (Service298Data, error)
}

type Service298Impl struct {
	service298DB backend.NoSQLDatabase
	service299 Service299
}

func NewService298Impl(ctx context.Context, service298DB backend.NoSQLDatabase, service299 Service299) (Service298, error) {
	return &Service298Impl{
		service298DB: service298DB,
		service299: service299,
	}, nil
}

func (s *Service298Impl) Method298(ctx context.Context, id298 string, data298 string, datatwo298 string) (Service298Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service298DB.GetCollection(ctx, "service298_db", "service298_data")
	if err != nil {
		return Service298Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id298},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service298Data{}, err
	}
	var service298Data Service298Data
	exists, err := res.One(ctx, &service298Data)
	if err != nil {
		return Service298Data{}, err
	}
	if exists {
		return service298Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service298DB.GetCollection(ctx, "service298_db", "service298_data")
	if err != nil {
		return Service298Data{}, err
	}
	service298Data = Service298Data{
		ID:   id298,
		Data: data298,
	}
	if err := coll.InsertOne(ctx, service298Data); err != nil {
		return Service298Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service298DB.GetCollection(ctx, "service298_db", "service298_data")
	if err != nil {
		return Service298Data{}, err
	}
	service298Data = Service298Data{
		ID:   id298,
		DataTwo: datatwo298,
	}
	if err := coll.InsertOne(ctx, service298Data); err != nil {
		return Service298Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service299.Method299(ctx, id298, data298, datatwo298); err != nil {
		return Service298Data{}, err
	}

	return service298Data, nil
}

func (s *Service298Impl) MethodOther298(ctx context.Context, id298 string, data298 string, datatwo298 string) (Service298Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service298DB.GetCollection(ctx, "service298_db", "service298_data")
	if err != nil {
		return Service298Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id298},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service298Data{}, err
	}
	var service298Data Service298Data
	exists, err := res.One(ctx, &service298Data)
	if err != nil {
		return Service298Data{}, err
	}
	if exists {
		return service298Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service298DB.GetCollection(ctx, "service298_db", "service298_data")
	if err != nil {
		return Service298Data{}, err
	}
	service298Data = Service298Data{
		ID:   id298,
		DataOther: data298,
	}
	if err := coll.InsertOne(ctx, service298Data); err != nil {
		return Service298Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service298DB.GetCollection(ctx, "service298_db", "service298_data")
	if err != nil {
		return Service298Data{}, err
	}
	service298Data = Service298Data{
		ID:   id298,
		DataOtherTwo: datatwo298,
	}
	if err := coll.InsertOne(ctx, service298Data); err != nil {
		return Service298Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service299.MethodOther299(ctx, id298, data298, datatwo298); err != nil {
		return Service298Data{}, err
	}

	return service298Data, nil
}

func (s *Service298Impl) MethodOtherOther298(ctx context.Context, id298 string, data298 string, datatwo298 string) (Service298Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service298DB.GetCollection(ctx, "service298_db", "service298_data")
	if err != nil {
		return Service298Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id298},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service298Data{}, err
	}
	var service298Data Service298Data
	exists, err := res.One(ctx, &service298Data)
	if err != nil {
		return Service298Data{}, err
	}
	if exists {
		return service298Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service298DB.GetCollection(ctx, "service298_db", "service298_data")
	if err != nil {
		return Service298Data{}, err
	}
	service298Data = Service298Data{
		ID:   id298,
		DataOtherOther: data298,
	}
	if err := coll.InsertOne(ctx, service298Data); err != nil {
		return Service298Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service298DB.GetCollection(ctx, "service298_db", "service298_data")
	if err != nil {
		return Service298Data{}, err
	}
	service298Data = Service298Data{
		ID:   id298,
		DataOtherOtherTwo: datatwo298,
	}
	if err := coll.InsertOne(ctx, service298Data); err != nil {
		return Service298Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service299.MethodOtherOther299(ctx, id298, data298, datatwo298); err != nil {
		return Service298Data{}, err
	}

	return service298Data, nil
}
