// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service127Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service127 interface {
	Method127(ctx context.Context, id string, data string, datatwo string) (Service127Data, error)
	MethodOther127(ctx context.Context, id string, data string, datatwo string) (Service127Data, error)
	MethodOtherOther127(ctx context.Context, id string, data string, datatwo string) (Service127Data, error)
}

type Service127Impl struct {
	service127DB backend.NoSQLDatabase
	service128 Service128
}

func NewService127Impl(ctx context.Context, service127DB backend.NoSQLDatabase, service128 Service128) (Service127, error) {
	return &Service127Impl{
		service127DB: service127DB,
		service128: service128,
	}, nil
}

func (s *Service127Impl) Method127(ctx context.Context, id127 string, data127 string, datatwo127 string) (Service127Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service127DB.GetCollection(ctx, "service127_db", "service127_data")
	if err != nil {
		return Service127Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id127},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service127Data{}, err
	}
	var service127Data Service127Data
	exists, err := res.One(ctx, &service127Data)
	if err != nil {
		return Service127Data{}, err
	}
	if exists {
		return service127Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service127DB.GetCollection(ctx, "service127_db", "service127_data")
	if err != nil {
		return Service127Data{}, err
	}
	service127Data = Service127Data{
		ID:   id127,
		Data: data127,
	}
	if err := coll.InsertOne(ctx, service127Data); err != nil {
		return Service127Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service127DB.GetCollection(ctx, "service127_db", "service127_data")
	if err != nil {
		return Service127Data{}, err
	}
	service127Data = Service127Data{
		ID:   id127,
		DataTwo: datatwo127,
	}
	if err := coll.InsertOne(ctx, service127Data); err != nil {
		return Service127Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service128.Method128(ctx, id127, data127, datatwo127); err != nil {
		return Service127Data{}, err
	}

	return service127Data, nil
}

func (s *Service127Impl) MethodOther127(ctx context.Context, id127 string, data127 string, datatwo127 string) (Service127Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service127DB.GetCollection(ctx, "service127_db", "service127_data")
	if err != nil {
		return Service127Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id127},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service127Data{}, err
	}
	var service127Data Service127Data
	exists, err := res.One(ctx, &service127Data)
	if err != nil {
		return Service127Data{}, err
	}
	if exists {
		return service127Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service127DB.GetCollection(ctx, "service127_db", "service127_data")
	if err != nil {
		return Service127Data{}, err
	}
	service127Data = Service127Data{
		ID:   id127,
		DataOther: data127,
	}
	if err := coll.InsertOne(ctx, service127Data); err != nil {
		return Service127Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service127DB.GetCollection(ctx, "service127_db", "service127_data")
	if err != nil {
		return Service127Data{}, err
	}
	service127Data = Service127Data{
		ID:   id127,
		DataOtherTwo: datatwo127,
	}
	if err := coll.InsertOne(ctx, service127Data); err != nil {
		return Service127Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service128.MethodOther128(ctx, id127, data127, datatwo127); err != nil {
		return Service127Data{}, err
	}

	return service127Data, nil
}

func (s *Service127Impl) MethodOtherOther127(ctx context.Context, id127 string, data127 string, datatwo127 string) (Service127Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service127DB.GetCollection(ctx, "service127_db", "service127_data")
	if err != nil {
		return Service127Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id127},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service127Data{}, err
	}
	var service127Data Service127Data
	exists, err := res.One(ctx, &service127Data)
	if err != nil {
		return Service127Data{}, err
	}
	if exists {
		return service127Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service127DB.GetCollection(ctx, "service127_db", "service127_data")
	if err != nil {
		return Service127Data{}, err
	}
	service127Data = Service127Data{
		ID:   id127,
		DataOtherOther: data127,
	}
	if err := coll.InsertOne(ctx, service127Data); err != nil {
		return Service127Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service127DB.GetCollection(ctx, "service127_db", "service127_data")
	if err != nil {
		return Service127Data{}, err
	}
	service127Data = Service127Data{
		ID:   id127,
		DataOtherOtherTwo: datatwo127,
	}
	if err := coll.InsertOne(ctx, service127Data); err != nil {
		return Service127Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service128.MethodOtherOther128(ctx, id127, data127, datatwo127); err != nil {
		return Service127Data{}, err
	}

	return service127Data, nil
}
