// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service394Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service394 interface {
	Method394(ctx context.Context, id string, data string, datatwo string) (Service394Data, error)
	MethodOther394(ctx context.Context, id string, data string, datatwo string) (Service394Data, error)
	MethodOtherOther394(ctx context.Context, id string, data string, datatwo string) (Service394Data, error)
}

type Service394Impl struct {
	service394DB backend.NoSQLDatabase
	service395 Service395
}

func NewService394Impl(ctx context.Context, service394DB backend.NoSQLDatabase, service395 Service395) (Service394, error) {
	return &Service394Impl{
		service394DB: service394DB,
		service395: service395,
	}, nil
}

func (s *Service394Impl) Method394(ctx context.Context, id394 string, data394 string, datatwo394 string) (Service394Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service394DB.GetCollection(ctx, "service394_db", "service394_data")
	if err != nil {
		return Service394Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id394},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service394Data{}, err
	}
	var service394Data Service394Data
	exists, err := res.One(ctx, &service394Data)
	if err != nil {
		return Service394Data{}, err
	}
	if exists {
		return service394Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service394DB.GetCollection(ctx, "service394_db", "service394_data")
	if err != nil {
		return Service394Data{}, err
	}
	service394Data = Service394Data{
		ID:   id394,
		Data: data394,
	}
	if err := coll.InsertOne(ctx, service394Data); err != nil {
		return Service394Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service394DB.GetCollection(ctx, "service394_db", "service394_data")
	if err != nil {
		return Service394Data{}, err
	}
	service394Data = Service394Data{
		ID:   id394,
		DataTwo: datatwo394,
	}
	if err := coll.InsertOne(ctx, service394Data); err != nil {
		return Service394Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service395.Method395(ctx, id394, data394, datatwo394); err != nil {
		return Service394Data{}, err
	}

	return service394Data, nil
}

func (s *Service394Impl) MethodOther394(ctx context.Context, id394 string, data394 string, datatwo394 string) (Service394Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service394DB.GetCollection(ctx, "service394_db", "service394_data")
	if err != nil {
		return Service394Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id394},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service394Data{}, err
	}
	var service394Data Service394Data
	exists, err := res.One(ctx, &service394Data)
	if err != nil {
		return Service394Data{}, err
	}
	if exists {
		return service394Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service394DB.GetCollection(ctx, "service394_db", "service394_data")
	if err != nil {
		return Service394Data{}, err
	}
	service394Data = Service394Data{
		ID:   id394,
		DataOther: data394,
	}
	if err := coll.InsertOne(ctx, service394Data); err != nil {
		return Service394Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service394DB.GetCollection(ctx, "service394_db", "service394_data")
	if err != nil {
		return Service394Data{}, err
	}
	service394Data = Service394Data{
		ID:   id394,
		DataOtherTwo: datatwo394,
	}
	if err := coll.InsertOne(ctx, service394Data); err != nil {
		return Service394Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service395.MethodOther395(ctx, id394, data394, datatwo394); err != nil {
		return Service394Data{}, err
	}

	return service394Data, nil
}

func (s *Service394Impl) MethodOtherOther394(ctx context.Context, id394 string, data394 string, datatwo394 string) (Service394Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service394DB.GetCollection(ctx, "service394_db", "service394_data")
	if err != nil {
		return Service394Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id394},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service394Data{}, err
	}
	var service394Data Service394Data
	exists, err := res.One(ctx, &service394Data)
	if err != nil {
		return Service394Data{}, err
	}
	if exists {
		return service394Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service394DB.GetCollection(ctx, "service394_db", "service394_data")
	if err != nil {
		return Service394Data{}, err
	}
	service394Data = Service394Data{
		ID:   id394,
		DataOtherOther: data394,
	}
	if err := coll.InsertOne(ctx, service394Data); err != nil {
		return Service394Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service394DB.GetCollection(ctx, "service394_db", "service394_data")
	if err != nil {
		return Service394Data{}, err
	}
	service394Data = Service394Data{
		ID:   id394,
		DataOtherOtherTwo: datatwo394,
	}
	if err := coll.InsertOne(ctx, service394Data); err != nil {
		return Service394Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service395.MethodOtherOther395(ctx, id394, data394, datatwo394); err != nil {
		return Service394Data{}, err
	}

	return service394Data, nil
}
