// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service74Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service74 interface {
	Method74(ctx context.Context, id string, data string, datatwo string) (Service74Data, error)
	MethodOther74(ctx context.Context, id string, data string, datatwo string) (Service74Data, error)
	MethodOtherOther74(ctx context.Context, id string, data string, datatwo string) (Service74Data, error)
}

type Service74Impl struct {
	service74DB backend.NoSQLDatabase
	service75 Service75
}

func NewService74Impl(ctx context.Context, service74DB backend.NoSQLDatabase, service75 Service75) (Service74, error) {
	return &Service74Impl{
		service74DB: service74DB,
		service75: service75,
	}, nil
}

func (s *Service74Impl) Method74(ctx context.Context, id74 string, data74 string, datatwo74 string) (Service74Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service74DB.GetCollection(ctx, "service74_db", "service74_data")
	if err != nil {
		return Service74Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id74},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service74Data{}, err
	}
	var service74Data Service74Data
	exists, err := res.One(ctx, &service74Data)
	if err != nil {
		return Service74Data{}, err
	}
	if exists {
		return service74Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service74DB.GetCollection(ctx, "service74_db", "service74_data")
	if err != nil {
		return Service74Data{}, err
	}
	service74Data = Service74Data{
		ID:   id74,
		Data: data74,
	}
	if err := coll.InsertOne(ctx, service74Data); err != nil {
		return Service74Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service74DB.GetCollection(ctx, "service74_db", "service74_data")
	if err != nil {
		return Service74Data{}, err
	}
	service74Data = Service74Data{
		ID:   id74,
		DataTwo: datatwo74,
	}
	if err := coll.InsertOne(ctx, service74Data); err != nil {
		return Service74Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service75.Method75(ctx, id74, data74, datatwo74); err != nil {
		return Service74Data{}, err
	}

	return service74Data, nil
}

func (s *Service74Impl) MethodOther74(ctx context.Context, id74 string, data74 string, datatwo74 string) (Service74Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service74DB.GetCollection(ctx, "service74_db", "service74_data")
	if err != nil {
		return Service74Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id74},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service74Data{}, err
	}
	var service74Data Service74Data
	exists, err := res.One(ctx, &service74Data)
	if err != nil {
		return Service74Data{}, err
	}
	if exists {
		return service74Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service74DB.GetCollection(ctx, "service74_db", "service74_data")
	if err != nil {
		return Service74Data{}, err
	}
	service74Data = Service74Data{
		ID:   id74,
		DataOther: data74,
	}
	if err := coll.InsertOne(ctx, service74Data); err != nil {
		return Service74Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service74DB.GetCollection(ctx, "service74_db", "service74_data")
	if err != nil {
		return Service74Data{}, err
	}
	service74Data = Service74Data{
		ID:   id74,
		DataOtherTwo: datatwo74,
	}
	if err := coll.InsertOne(ctx, service74Data); err != nil {
		return Service74Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service75.MethodOther75(ctx, id74, data74, datatwo74); err != nil {
		return Service74Data{}, err
	}

	return service74Data, nil
}

func (s *Service74Impl) MethodOtherOther74(ctx context.Context, id74 string, data74 string, datatwo74 string) (Service74Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service74DB.GetCollection(ctx, "service74_db", "service74_data")
	if err != nil {
		return Service74Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id74},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service74Data{}, err
	}
	var service74Data Service74Data
	exists, err := res.One(ctx, &service74Data)
	if err != nil {
		return Service74Data{}, err
	}
	if exists {
		return service74Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service74DB.GetCollection(ctx, "service74_db", "service74_data")
	if err != nil {
		return Service74Data{}, err
	}
	service74Data = Service74Data{
		ID:   id74,
		DataOtherOther: data74,
	}
	if err := coll.InsertOne(ctx, service74Data); err != nil {
		return Service74Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service74DB.GetCollection(ctx, "service74_db", "service74_data")
	if err != nil {
		return Service74Data{}, err
	}
	service74Data = Service74Data{
		ID:   id74,
		DataOtherOtherTwo: datatwo74,
	}
	if err := coll.InsertOne(ctx, service74Data); err != nil {
		return Service74Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service75.MethodOtherOther75(ctx, id74, data74, datatwo74); err != nil {
		return Service74Data{}, err
	}

	return service74Data, nil
}
