// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service319Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service319 interface {
	Method319(ctx context.Context, id string, data string, datatwo string) (Service319Data, error)
	MethodOther319(ctx context.Context, id string, data string, datatwo string) (Service319Data, error)
	MethodOtherOther319(ctx context.Context, id string, data string, datatwo string) (Service319Data, error)
}

type Service319Impl struct {
	service319DB backend.NoSQLDatabase
	service320 Service320
}

func NewService319Impl(ctx context.Context, service319DB backend.NoSQLDatabase, service320 Service320) (Service319, error) {
	return &Service319Impl{
		service319DB: service319DB,
		service320: service320,
	}, nil
}

func (s *Service319Impl) Method319(ctx context.Context, id319 string, data319 string, datatwo319 string) (Service319Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service319DB.GetCollection(ctx, "service319_db", "service319_data")
	if err != nil {
		return Service319Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id319},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service319Data{}, err
	}
	var service319Data Service319Data
	exists, err := res.One(ctx, &service319Data)
	if err != nil {
		return Service319Data{}, err
	}
	if exists {
		return service319Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service319DB.GetCollection(ctx, "service319_db", "service319_data")
	if err != nil {
		return Service319Data{}, err
	}
	service319Data = Service319Data{
		ID:   id319,
		Data: data319,
	}
	if err := coll.InsertOne(ctx, service319Data); err != nil {
		return Service319Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service319DB.GetCollection(ctx, "service319_db", "service319_data")
	if err != nil {
		return Service319Data{}, err
	}
	service319Data = Service319Data{
		ID:   id319,
		DataTwo: datatwo319,
	}
	if err := coll.InsertOne(ctx, service319Data); err != nil {
		return Service319Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service320.Method320(ctx, id319, data319, datatwo319); err != nil {
		return Service319Data{}, err
	}

	return service319Data, nil
}

func (s *Service319Impl) MethodOther319(ctx context.Context, id319 string, data319 string, datatwo319 string) (Service319Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service319DB.GetCollection(ctx, "service319_db", "service319_data")
	if err != nil {
		return Service319Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id319},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service319Data{}, err
	}
	var service319Data Service319Data
	exists, err := res.One(ctx, &service319Data)
	if err != nil {
		return Service319Data{}, err
	}
	if exists {
		return service319Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service319DB.GetCollection(ctx, "service319_db", "service319_data")
	if err != nil {
		return Service319Data{}, err
	}
	service319Data = Service319Data{
		ID:   id319,
		DataOther: data319,
	}
	if err := coll.InsertOne(ctx, service319Data); err != nil {
		return Service319Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service319DB.GetCollection(ctx, "service319_db", "service319_data")
	if err != nil {
		return Service319Data{}, err
	}
	service319Data = Service319Data{
		ID:   id319,
		DataOtherTwo: datatwo319,
	}
	if err := coll.InsertOne(ctx, service319Data); err != nil {
		return Service319Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service320.MethodOther320(ctx, id319, data319, datatwo319); err != nil {
		return Service319Data{}, err
	}

	return service319Data, nil
}

func (s *Service319Impl) MethodOtherOther319(ctx context.Context, id319 string, data319 string, datatwo319 string) (Service319Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service319DB.GetCollection(ctx, "service319_db", "service319_data")
	if err != nil {
		return Service319Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id319},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service319Data{}, err
	}
	var service319Data Service319Data
	exists, err := res.One(ctx, &service319Data)
	if err != nil {
		return Service319Data{}, err
	}
	if exists {
		return service319Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service319DB.GetCollection(ctx, "service319_db", "service319_data")
	if err != nil {
		return Service319Data{}, err
	}
	service319Data = Service319Data{
		ID:   id319,
		DataOtherOther: data319,
	}
	if err := coll.InsertOne(ctx, service319Data); err != nil {
		return Service319Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service319DB.GetCollection(ctx, "service319_db", "service319_data")
	if err != nil {
		return Service319Data{}, err
	}
	service319Data = Service319Data{
		ID:   id319,
		DataOtherOtherTwo: datatwo319,
	}
	if err := coll.InsertOne(ctx, service319Data); err != nil {
		return Service319Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service320.MethodOtherOther320(ctx, id319, data319, datatwo319); err != nil {
		return Service319Data{}, err
	}

	return service319Data, nil
}
