// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service157Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service157 interface {
	Method157(ctx context.Context, id string, data string, datatwo string) (Service157Data, error)
	MethodOther157(ctx context.Context, id string, data string, datatwo string) (Service157Data, error)
	MethodOtherOther157(ctx context.Context, id string, data string, datatwo string) (Service157Data, error)
}

type Service157Impl struct {
	service157DB backend.NoSQLDatabase
	service158 Service158
}

func NewService157Impl(ctx context.Context, service157DB backend.NoSQLDatabase, service158 Service158) (Service157, error) {
	return &Service157Impl{
		service157DB: service157DB,
		service158: service158,
	}, nil
}

func (s *Service157Impl) Method157(ctx context.Context, id157 string, data157 string, datatwo157 string) (Service157Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service157DB.GetCollection(ctx, "service157_db", "service157_data")
	if err != nil {
		return Service157Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id157},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service157Data{}, err
	}
	var service157Data Service157Data
	exists, err := res.One(ctx, &service157Data)
	if err != nil {
		return Service157Data{}, err
	}
	if exists {
		return service157Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service157DB.GetCollection(ctx, "service157_db", "service157_data")
	if err != nil {
		return Service157Data{}, err
	}
	service157Data = Service157Data{
		ID:   id157,
		Data: data157,
	}
	if err := coll.InsertOne(ctx, service157Data); err != nil {
		return Service157Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service157DB.GetCollection(ctx, "service157_db", "service157_data")
	if err != nil {
		return Service157Data{}, err
	}
	service157Data = Service157Data{
		ID:   id157,
		DataTwo: datatwo157,
	}
	if err := coll.InsertOne(ctx, service157Data); err != nil {
		return Service157Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service158.Method158(ctx, id157, data157, datatwo157); err != nil {
		return Service157Data{}, err
	}

	return service157Data, nil
}

func (s *Service157Impl) MethodOther157(ctx context.Context, id157 string, data157 string, datatwo157 string) (Service157Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service157DB.GetCollection(ctx, "service157_db", "service157_data")
	if err != nil {
		return Service157Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id157},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service157Data{}, err
	}
	var service157Data Service157Data
	exists, err := res.One(ctx, &service157Data)
	if err != nil {
		return Service157Data{}, err
	}
	if exists {
		return service157Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service157DB.GetCollection(ctx, "service157_db", "service157_data")
	if err != nil {
		return Service157Data{}, err
	}
	service157Data = Service157Data{
		ID:   id157,
		DataOther: data157,
	}
	if err := coll.InsertOne(ctx, service157Data); err != nil {
		return Service157Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service157DB.GetCollection(ctx, "service157_db", "service157_data")
	if err != nil {
		return Service157Data{}, err
	}
	service157Data = Service157Data{
		ID:   id157,
		DataOtherTwo: datatwo157,
	}
	if err := coll.InsertOne(ctx, service157Data); err != nil {
		return Service157Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service158.MethodOther158(ctx, id157, data157, datatwo157); err != nil {
		return Service157Data{}, err
	}

	return service157Data, nil
}

func (s *Service157Impl) MethodOtherOther157(ctx context.Context, id157 string, data157 string, datatwo157 string) (Service157Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service157DB.GetCollection(ctx, "service157_db", "service157_data")
	if err != nil {
		return Service157Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id157},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service157Data{}, err
	}
	var service157Data Service157Data
	exists, err := res.One(ctx, &service157Data)
	if err != nil {
		return Service157Data{}, err
	}
	if exists {
		return service157Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service157DB.GetCollection(ctx, "service157_db", "service157_data")
	if err != nil {
		return Service157Data{}, err
	}
	service157Data = Service157Data{
		ID:   id157,
		DataOtherOther: data157,
	}
	if err := coll.InsertOne(ctx, service157Data); err != nil {
		return Service157Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service157DB.GetCollection(ctx, "service157_db", "service157_data")
	if err != nil {
		return Service157Data{}, err
	}
	service157Data = Service157Data{
		ID:   id157,
		DataOtherOtherTwo: datatwo157,
	}
	if err := coll.InsertOne(ctx, service157Data); err != nil {
		return Service157Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service158.MethodOtherOther158(ctx, id157, data157, datatwo157); err != nil {
		return Service157Data{}, err
	}

	return service157Data, nil
}
