// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service143Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service143 interface {
	Method143(ctx context.Context, id string, data string, datatwo string) (Service143Data, error)
	MethodOther143(ctx context.Context, id string, data string, datatwo string) (Service143Data, error)
	MethodOtherOther143(ctx context.Context, id string, data string, datatwo string) (Service143Data, error)
}

type Service143Impl struct {
	service143DB backend.NoSQLDatabase
	service144 Service144
}

func NewService143Impl(ctx context.Context, service143DB backend.NoSQLDatabase, service144 Service144) (Service143, error) {
	return &Service143Impl{
		service143DB: service143DB,
		service144: service144,
	}, nil
}

func (s *Service143Impl) Method143(ctx context.Context, id143 string, data143 string, datatwo143 string) (Service143Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service143DB.GetCollection(ctx, "service143_db", "service143_data")
	if err != nil {
		return Service143Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id143},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service143Data{}, err
	}
	var service143Data Service143Data
	exists, err := res.One(ctx, &service143Data)
	if err != nil {
		return Service143Data{}, err
	}
	if exists {
		return service143Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service143DB.GetCollection(ctx, "service143_db", "service143_data")
	if err != nil {
		return Service143Data{}, err
	}
	service143Data = Service143Data{
		ID:   id143,
		Data: data143,
	}
	if err := coll.InsertOne(ctx, service143Data); err != nil {
		return Service143Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service143DB.GetCollection(ctx, "service143_db", "service143_data")
	if err != nil {
		return Service143Data{}, err
	}
	service143Data = Service143Data{
		ID:   id143,
		DataTwo: datatwo143,
	}
	if err := coll.InsertOne(ctx, service143Data); err != nil {
		return Service143Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service144.Method144(ctx, id143, data143, datatwo143); err != nil {
		return Service143Data{}, err
	}

	return service143Data, nil
}

func (s *Service143Impl) MethodOther143(ctx context.Context, id143 string, data143 string, datatwo143 string) (Service143Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service143DB.GetCollection(ctx, "service143_db", "service143_data")
	if err != nil {
		return Service143Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id143},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service143Data{}, err
	}
	var service143Data Service143Data
	exists, err := res.One(ctx, &service143Data)
	if err != nil {
		return Service143Data{}, err
	}
	if exists {
		return service143Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service143DB.GetCollection(ctx, "service143_db", "service143_data")
	if err != nil {
		return Service143Data{}, err
	}
	service143Data = Service143Data{
		ID:   id143,
		DataOther: data143,
	}
	if err := coll.InsertOne(ctx, service143Data); err != nil {
		return Service143Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service143DB.GetCollection(ctx, "service143_db", "service143_data")
	if err != nil {
		return Service143Data{}, err
	}
	service143Data = Service143Data{
		ID:   id143,
		DataOtherTwo: datatwo143,
	}
	if err := coll.InsertOne(ctx, service143Data); err != nil {
		return Service143Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service144.MethodOther144(ctx, id143, data143, datatwo143); err != nil {
		return Service143Data{}, err
	}

	return service143Data, nil
}

func (s *Service143Impl) MethodOtherOther143(ctx context.Context, id143 string, data143 string, datatwo143 string) (Service143Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service143DB.GetCollection(ctx, "service143_db", "service143_data")
	if err != nil {
		return Service143Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id143},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service143Data{}, err
	}
	var service143Data Service143Data
	exists, err := res.One(ctx, &service143Data)
	if err != nil {
		return Service143Data{}, err
	}
	if exists {
		return service143Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service143DB.GetCollection(ctx, "service143_db", "service143_data")
	if err != nil {
		return Service143Data{}, err
	}
	service143Data = Service143Data{
		ID:   id143,
		DataOtherOther: data143,
	}
	if err := coll.InsertOne(ctx, service143Data); err != nil {
		return Service143Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service143DB.GetCollection(ctx, "service143_db", "service143_data")
	if err != nil {
		return Service143Data{}, err
	}
	service143Data = Service143Data{
		ID:   id143,
		DataOtherOtherTwo: datatwo143,
	}
	if err := coll.InsertOne(ctx, service143Data); err != nil {
		return Service143Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service144.MethodOtherOther144(ctx, id143, data143, datatwo143); err != nil {
		return Service143Data{}, err
	}

	return service143Data, nil
}
