// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service154Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service154 interface {
	Method154(ctx context.Context, id string, data string, datatwo string) (Service154Data, error)
	MethodOther154(ctx context.Context, id string, data string, datatwo string) (Service154Data, error)
	MethodOtherOther154(ctx context.Context, id string, data string, datatwo string) (Service154Data, error)
}

type Service154Impl struct {
	service154DB backend.NoSQLDatabase
	service155 Service155
}

func NewService154Impl(ctx context.Context, service154DB backend.NoSQLDatabase, service155 Service155) (Service154, error) {
	return &Service154Impl{
		service154DB: service154DB,
		service155: service155,
	}, nil
}

func (s *Service154Impl) Method154(ctx context.Context, id154 string, data154 string, datatwo154 string) (Service154Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service154DB.GetCollection(ctx, "service154_db", "service154_data")
	if err != nil {
		return Service154Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id154},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service154Data{}, err
	}
	var service154Data Service154Data
	exists, err := res.One(ctx, &service154Data)
	if err != nil {
		return Service154Data{}, err
	}
	if exists {
		return service154Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service154DB.GetCollection(ctx, "service154_db", "service154_data")
	if err != nil {
		return Service154Data{}, err
	}
	service154Data = Service154Data{
		ID:   id154,
		Data: data154,
	}
	if err := coll.InsertOne(ctx, service154Data); err != nil {
		return Service154Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service154DB.GetCollection(ctx, "service154_db", "service154_data")
	if err != nil {
		return Service154Data{}, err
	}
	service154Data = Service154Data{
		ID:   id154,
		DataTwo: datatwo154,
	}
	if err := coll.InsertOne(ctx, service154Data); err != nil {
		return Service154Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service155.Method155(ctx, id154, data154, datatwo154); err != nil {
		return Service154Data{}, err
	}

	return service154Data, nil
}

func (s *Service154Impl) MethodOther154(ctx context.Context, id154 string, data154 string, datatwo154 string) (Service154Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service154DB.GetCollection(ctx, "service154_db", "service154_data")
	if err != nil {
		return Service154Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id154},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service154Data{}, err
	}
	var service154Data Service154Data
	exists, err := res.One(ctx, &service154Data)
	if err != nil {
		return Service154Data{}, err
	}
	if exists {
		return service154Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service154DB.GetCollection(ctx, "service154_db", "service154_data")
	if err != nil {
		return Service154Data{}, err
	}
	service154Data = Service154Data{
		ID:   id154,
		DataOther: data154,
	}
	if err := coll.InsertOne(ctx, service154Data); err != nil {
		return Service154Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service154DB.GetCollection(ctx, "service154_db", "service154_data")
	if err != nil {
		return Service154Data{}, err
	}
	service154Data = Service154Data{
		ID:   id154,
		DataOtherTwo: datatwo154,
	}
	if err := coll.InsertOne(ctx, service154Data); err != nil {
		return Service154Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service155.MethodOther155(ctx, id154, data154, datatwo154); err != nil {
		return Service154Data{}, err
	}

	return service154Data, nil
}

func (s *Service154Impl) MethodOtherOther154(ctx context.Context, id154 string, data154 string, datatwo154 string) (Service154Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service154DB.GetCollection(ctx, "service154_db", "service154_data")
	if err != nil {
		return Service154Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id154},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service154Data{}, err
	}
	var service154Data Service154Data
	exists, err := res.One(ctx, &service154Data)
	if err != nil {
		return Service154Data{}, err
	}
	if exists {
		return service154Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service154DB.GetCollection(ctx, "service154_db", "service154_data")
	if err != nil {
		return Service154Data{}, err
	}
	service154Data = Service154Data{
		ID:   id154,
		DataOtherOther: data154,
	}
	if err := coll.InsertOne(ctx, service154Data); err != nil {
		return Service154Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service154DB.GetCollection(ctx, "service154_db", "service154_data")
	if err != nil {
		return Service154Data{}, err
	}
	service154Data = Service154Data{
		ID:   id154,
		DataOtherOtherTwo: datatwo154,
	}
	if err := coll.InsertOne(ctx, service154Data); err != nil {
		return Service154Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service155.MethodOtherOther155(ctx, id154, data154, datatwo154); err != nil {
		return Service154Data{}, err
	}

	return service154Data, nil
}
