// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service325Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service325 interface {
	Method325(ctx context.Context, id string, data string, datatwo string) (Service325Data, error)
	MethodOther325(ctx context.Context, id string, data string, datatwo string) (Service325Data, error)
	MethodOtherOther325(ctx context.Context, id string, data string, datatwo string) (Service325Data, error)
}

type Service325Impl struct {
	service325DB backend.NoSQLDatabase
	service326 Service326
}

func NewService325Impl(ctx context.Context, service325DB backend.NoSQLDatabase, service326 Service326) (Service325, error) {
	return &Service325Impl{
		service325DB: service325DB,
		service326: service326,
	}, nil
}

func (s *Service325Impl) Method325(ctx context.Context, id325 string, data325 string, datatwo325 string) (Service325Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service325DB.GetCollection(ctx, "service325_db", "service325_data")
	if err != nil {
		return Service325Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id325},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service325Data{}, err
	}
	var service325Data Service325Data
	exists, err := res.One(ctx, &service325Data)
	if err != nil {
		return Service325Data{}, err
	}
	if exists {
		return service325Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service325DB.GetCollection(ctx, "service325_db", "service325_data")
	if err != nil {
		return Service325Data{}, err
	}
	service325Data = Service325Data{
		ID:   id325,
		Data: data325,
	}
	if err := coll.InsertOne(ctx, service325Data); err != nil {
		return Service325Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service325DB.GetCollection(ctx, "service325_db", "service325_data")
	if err != nil {
		return Service325Data{}, err
	}
	service325Data = Service325Data{
		ID:   id325,
		DataTwo: datatwo325,
	}
	if err := coll.InsertOne(ctx, service325Data); err != nil {
		return Service325Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service326.Method326(ctx, id325, data325, datatwo325); err != nil {
		return Service325Data{}, err
	}

	return service325Data, nil
}

func (s *Service325Impl) MethodOther325(ctx context.Context, id325 string, data325 string, datatwo325 string) (Service325Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service325DB.GetCollection(ctx, "service325_db", "service325_data")
	if err != nil {
		return Service325Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id325},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service325Data{}, err
	}
	var service325Data Service325Data
	exists, err := res.One(ctx, &service325Data)
	if err != nil {
		return Service325Data{}, err
	}
	if exists {
		return service325Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service325DB.GetCollection(ctx, "service325_db", "service325_data")
	if err != nil {
		return Service325Data{}, err
	}
	service325Data = Service325Data{
		ID:   id325,
		DataOther: data325,
	}
	if err := coll.InsertOne(ctx, service325Data); err != nil {
		return Service325Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service325DB.GetCollection(ctx, "service325_db", "service325_data")
	if err != nil {
		return Service325Data{}, err
	}
	service325Data = Service325Data{
		ID:   id325,
		DataOtherTwo: datatwo325,
	}
	if err := coll.InsertOne(ctx, service325Data); err != nil {
		return Service325Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service326.MethodOther326(ctx, id325, data325, datatwo325); err != nil {
		return Service325Data{}, err
	}

	return service325Data, nil
}

func (s *Service325Impl) MethodOtherOther325(ctx context.Context, id325 string, data325 string, datatwo325 string) (Service325Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service325DB.GetCollection(ctx, "service325_db", "service325_data")
	if err != nil {
		return Service325Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id325},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service325Data{}, err
	}
	var service325Data Service325Data
	exists, err := res.One(ctx, &service325Data)
	if err != nil {
		return Service325Data{}, err
	}
	if exists {
		return service325Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service325DB.GetCollection(ctx, "service325_db", "service325_data")
	if err != nil {
		return Service325Data{}, err
	}
	service325Data = Service325Data{
		ID:   id325,
		DataOtherOther: data325,
	}
	if err := coll.InsertOne(ctx, service325Data); err != nil {
		return Service325Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service325DB.GetCollection(ctx, "service325_db", "service325_data")
	if err != nil {
		return Service325Data{}, err
	}
	service325Data = Service325Data{
		ID:   id325,
		DataOtherOtherTwo: datatwo325,
	}
	if err := coll.InsertOne(ctx, service325Data); err != nil {
		return Service325Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service326.MethodOtherOther326(ctx, id325, data325, datatwo325); err != nil {
		return Service325Data{}, err
	}

	return service325Data, nil
}
