// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service487Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service487 interface {
	Method487(ctx context.Context, id string, data string, datatwo string) (Service487Data, error)
	MethodOther487(ctx context.Context, id string, data string, datatwo string) (Service487Data, error)
	MethodOtherOther487(ctx context.Context, id string, data string, datatwo string) (Service487Data, error)
}

type Service487Impl struct {
	service487DB backend.NoSQLDatabase
	service488 Service488
}

func NewService487Impl(ctx context.Context, service487DB backend.NoSQLDatabase, service488 Service488) (Service487, error) {
	return &Service487Impl{
		service487DB: service487DB,
		service488: service488,
	}, nil
}

func (s *Service487Impl) Method487(ctx context.Context, id487 string, data487 string, datatwo487 string) (Service487Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service487DB.GetCollection(ctx, "service487_db", "service487_data")
	if err != nil {
		return Service487Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id487},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service487Data{}, err
	}
	var service487Data Service487Data
	exists, err := res.One(ctx, &service487Data)
	if err != nil {
		return Service487Data{}, err
	}
	if exists {
		return service487Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service487DB.GetCollection(ctx, "service487_db", "service487_data")
	if err != nil {
		return Service487Data{}, err
	}
	service487Data = Service487Data{
		ID:   id487,
		Data: data487,
	}
	if err := coll.InsertOne(ctx, service487Data); err != nil {
		return Service487Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service487DB.GetCollection(ctx, "service487_db", "service487_data")
	if err != nil {
		return Service487Data{}, err
	}
	service487Data = Service487Data{
		ID:   id487,
		DataTwo: datatwo487,
	}
	if err := coll.InsertOne(ctx, service487Data); err != nil {
		return Service487Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service488.Method488(ctx, id487, data487, datatwo487); err != nil {
		return Service487Data{}, err
	}

	return service487Data, nil
}

func (s *Service487Impl) MethodOther487(ctx context.Context, id487 string, data487 string, datatwo487 string) (Service487Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service487DB.GetCollection(ctx, "service487_db", "service487_data")
	if err != nil {
		return Service487Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id487},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service487Data{}, err
	}
	var service487Data Service487Data
	exists, err := res.One(ctx, &service487Data)
	if err != nil {
		return Service487Data{}, err
	}
	if exists {
		return service487Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service487DB.GetCollection(ctx, "service487_db", "service487_data")
	if err != nil {
		return Service487Data{}, err
	}
	service487Data = Service487Data{
		ID:   id487,
		DataOther: data487,
	}
	if err := coll.InsertOne(ctx, service487Data); err != nil {
		return Service487Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service487DB.GetCollection(ctx, "service487_db", "service487_data")
	if err != nil {
		return Service487Data{}, err
	}
	service487Data = Service487Data{
		ID:   id487,
		DataOtherTwo: datatwo487,
	}
	if err := coll.InsertOne(ctx, service487Data); err != nil {
		return Service487Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service488.MethodOther488(ctx, id487, data487, datatwo487); err != nil {
		return Service487Data{}, err
	}

	return service487Data, nil
}

func (s *Service487Impl) MethodOtherOther487(ctx context.Context, id487 string, data487 string, datatwo487 string) (Service487Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service487DB.GetCollection(ctx, "service487_db", "service487_data")
	if err != nil {
		return Service487Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id487},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service487Data{}, err
	}
	var service487Data Service487Data
	exists, err := res.One(ctx, &service487Data)
	if err != nil {
		return Service487Data{}, err
	}
	if exists {
		return service487Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service487DB.GetCollection(ctx, "service487_db", "service487_data")
	if err != nil {
		return Service487Data{}, err
	}
	service487Data = Service487Data{
		ID:   id487,
		DataOtherOther: data487,
	}
	if err := coll.InsertOne(ctx, service487Data); err != nil {
		return Service487Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service487DB.GetCollection(ctx, "service487_db", "service487_data")
	if err != nil {
		return Service487Data{}, err
	}
	service487Data = Service487Data{
		ID:   id487,
		DataOtherOtherTwo: datatwo487,
	}
	if err := coll.InsertOne(ctx, service487Data); err != nil {
		return Service487Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service488.MethodOtherOther488(ctx, id487, data487, datatwo487); err != nil {
		return Service487Data{}, err
	}

	return service487Data, nil
}
