// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service212Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service212 interface {
	Method212(ctx context.Context, id string, data string, datatwo string) (Service212Data, error)
	MethodOther212(ctx context.Context, id string, data string, datatwo string) (Service212Data, error)
	MethodOtherOther212(ctx context.Context, id string, data string, datatwo string) (Service212Data, error)
}

type Service212Impl struct {
	service212DB backend.NoSQLDatabase
	service213 Service213
}

func NewService212Impl(ctx context.Context, service212DB backend.NoSQLDatabase, service213 Service213) (Service212, error) {
	return &Service212Impl{
		service212DB: service212DB,
		service213: service213,
	}, nil
}

func (s *Service212Impl) Method212(ctx context.Context, id212 string, data212 string, datatwo212 string) (Service212Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service212DB.GetCollection(ctx, "service212_db", "service212_data")
	if err != nil {
		return Service212Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id212},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service212Data{}, err
	}
	var service212Data Service212Data
	exists, err := res.One(ctx, &service212Data)
	if err != nil {
		return Service212Data{}, err
	}
	if exists {
		return service212Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service212DB.GetCollection(ctx, "service212_db", "service212_data")
	if err != nil {
		return Service212Data{}, err
	}
	service212Data = Service212Data{
		ID:   id212,
		Data: data212,
	}
	if err := coll.InsertOne(ctx, service212Data); err != nil {
		return Service212Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service212DB.GetCollection(ctx, "service212_db", "service212_data")
	if err != nil {
		return Service212Data{}, err
	}
	service212Data = Service212Data{
		ID:   id212,
		DataTwo: datatwo212,
	}
	if err := coll.InsertOne(ctx, service212Data); err != nil {
		return Service212Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service213.Method213(ctx, id212, data212, datatwo212); err != nil {
		return Service212Data{}, err
	}

	return service212Data, nil
}

func (s *Service212Impl) MethodOther212(ctx context.Context, id212 string, data212 string, datatwo212 string) (Service212Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service212DB.GetCollection(ctx, "service212_db", "service212_data")
	if err != nil {
		return Service212Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id212},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service212Data{}, err
	}
	var service212Data Service212Data
	exists, err := res.One(ctx, &service212Data)
	if err != nil {
		return Service212Data{}, err
	}
	if exists {
		return service212Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service212DB.GetCollection(ctx, "service212_db", "service212_data")
	if err != nil {
		return Service212Data{}, err
	}
	service212Data = Service212Data{
		ID:   id212,
		DataOther: data212,
	}
	if err := coll.InsertOne(ctx, service212Data); err != nil {
		return Service212Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service212DB.GetCollection(ctx, "service212_db", "service212_data")
	if err != nil {
		return Service212Data{}, err
	}
	service212Data = Service212Data{
		ID:   id212,
		DataOtherTwo: datatwo212,
	}
	if err := coll.InsertOne(ctx, service212Data); err != nil {
		return Service212Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service213.MethodOther213(ctx, id212, data212, datatwo212); err != nil {
		return Service212Data{}, err
	}

	return service212Data, nil
}

func (s *Service212Impl) MethodOtherOther212(ctx context.Context, id212 string, data212 string, datatwo212 string) (Service212Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service212DB.GetCollection(ctx, "service212_db", "service212_data")
	if err != nil {
		return Service212Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id212},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service212Data{}, err
	}
	var service212Data Service212Data
	exists, err := res.One(ctx, &service212Data)
	if err != nil {
		return Service212Data{}, err
	}
	if exists {
		return service212Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service212DB.GetCollection(ctx, "service212_db", "service212_data")
	if err != nil {
		return Service212Data{}, err
	}
	service212Data = Service212Data{
		ID:   id212,
		DataOtherOther: data212,
	}
	if err := coll.InsertOne(ctx, service212Data); err != nil {
		return Service212Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service212DB.GetCollection(ctx, "service212_db", "service212_data")
	if err != nil {
		return Service212Data{}, err
	}
	service212Data = Service212Data{
		ID:   id212,
		DataOtherOtherTwo: datatwo212,
	}
	if err := coll.InsertOne(ctx, service212Data); err != nil {
		return Service212Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service213.MethodOtherOther213(ctx, id212, data212, datatwo212); err != nil {
		return Service212Data{}, err
	}

	return service212Data, nil
}
