// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service465Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service465 interface {
	Method465(ctx context.Context, id string, data string, datatwo string) (Service465Data, error)
	MethodOther465(ctx context.Context, id string, data string, datatwo string) (Service465Data, error)
	MethodOtherOther465(ctx context.Context, id string, data string, datatwo string) (Service465Data, error)
}

type Service465Impl struct {
	service465DB backend.NoSQLDatabase
	service466 Service466
}

func NewService465Impl(ctx context.Context, service465DB backend.NoSQLDatabase, service466 Service466) (Service465, error) {
	return &Service465Impl{
		service465DB: service465DB,
		service466: service466,
	}, nil
}

func (s *Service465Impl) Method465(ctx context.Context, id465 string, data465 string, datatwo465 string) (Service465Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service465DB.GetCollection(ctx, "service465_db", "service465_data")
	if err != nil {
		return Service465Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id465},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service465Data{}, err
	}
	var service465Data Service465Data
	exists, err := res.One(ctx, &service465Data)
	if err != nil {
		return Service465Data{}, err
	}
	if exists {
		return service465Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service465DB.GetCollection(ctx, "service465_db", "service465_data")
	if err != nil {
		return Service465Data{}, err
	}
	service465Data = Service465Data{
		ID:   id465,
		Data: data465,
	}
	if err := coll.InsertOne(ctx, service465Data); err != nil {
		return Service465Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service465DB.GetCollection(ctx, "service465_db", "service465_data")
	if err != nil {
		return Service465Data{}, err
	}
	service465Data = Service465Data{
		ID:   id465,
		DataTwo: datatwo465,
	}
	if err := coll.InsertOne(ctx, service465Data); err != nil {
		return Service465Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service466.Method466(ctx, id465, data465, datatwo465); err != nil {
		return Service465Data{}, err
	}

	return service465Data, nil
}

func (s *Service465Impl) MethodOther465(ctx context.Context, id465 string, data465 string, datatwo465 string) (Service465Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service465DB.GetCollection(ctx, "service465_db", "service465_data")
	if err != nil {
		return Service465Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id465},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service465Data{}, err
	}
	var service465Data Service465Data
	exists, err := res.One(ctx, &service465Data)
	if err != nil {
		return Service465Data{}, err
	}
	if exists {
		return service465Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service465DB.GetCollection(ctx, "service465_db", "service465_data")
	if err != nil {
		return Service465Data{}, err
	}
	service465Data = Service465Data{
		ID:   id465,
		DataOther: data465,
	}
	if err := coll.InsertOne(ctx, service465Data); err != nil {
		return Service465Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service465DB.GetCollection(ctx, "service465_db", "service465_data")
	if err != nil {
		return Service465Data{}, err
	}
	service465Data = Service465Data{
		ID:   id465,
		DataOtherTwo: datatwo465,
	}
	if err := coll.InsertOne(ctx, service465Data); err != nil {
		return Service465Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service466.MethodOther466(ctx, id465, data465, datatwo465); err != nil {
		return Service465Data{}, err
	}

	return service465Data, nil
}

func (s *Service465Impl) MethodOtherOther465(ctx context.Context, id465 string, data465 string, datatwo465 string) (Service465Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service465DB.GetCollection(ctx, "service465_db", "service465_data")
	if err != nil {
		return Service465Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id465},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service465Data{}, err
	}
	var service465Data Service465Data
	exists, err := res.One(ctx, &service465Data)
	if err != nil {
		return Service465Data{}, err
	}
	if exists {
		return service465Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service465DB.GetCollection(ctx, "service465_db", "service465_data")
	if err != nil {
		return Service465Data{}, err
	}
	service465Data = Service465Data{
		ID:   id465,
		DataOtherOther: data465,
	}
	if err := coll.InsertOne(ctx, service465Data); err != nil {
		return Service465Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service465DB.GetCollection(ctx, "service465_db", "service465_data")
	if err != nil {
		return Service465Data{}, err
	}
	service465Data = Service465Data{
		ID:   id465,
		DataOtherOtherTwo: datatwo465,
	}
	if err := coll.InsertOne(ctx, service465Data); err != nil {
		return Service465Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service466.MethodOtherOther466(ctx, id465, data465, datatwo465); err != nil {
		return Service465Data{}, err
	}

	return service465Data, nil
}
