// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service405Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service405 interface {
	Method405(ctx context.Context, id string, data string, datatwo string) (Service405Data, error)
	MethodOther405(ctx context.Context, id string, data string, datatwo string) (Service405Data, error)
	MethodOtherOther405(ctx context.Context, id string, data string, datatwo string) (Service405Data, error)
}

type Service405Impl struct {
	service405DB backend.NoSQLDatabase
	service406 Service406
}

func NewService405Impl(ctx context.Context, service405DB backend.NoSQLDatabase, service406 Service406) (Service405, error) {
	return &Service405Impl{
		service405DB: service405DB,
		service406: service406,
	}, nil
}

func (s *Service405Impl) Method405(ctx context.Context, id405 string, data405 string, datatwo405 string) (Service405Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service405DB.GetCollection(ctx, "service405_db", "service405_data")
	if err != nil {
		return Service405Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id405},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service405Data{}, err
	}
	var service405Data Service405Data
	exists, err := res.One(ctx, &service405Data)
	if err != nil {
		return Service405Data{}, err
	}
	if exists {
		return service405Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service405DB.GetCollection(ctx, "service405_db", "service405_data")
	if err != nil {
		return Service405Data{}, err
	}
	service405Data = Service405Data{
		ID:   id405,
		Data: data405,
	}
	if err := coll.InsertOne(ctx, service405Data); err != nil {
		return Service405Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service405DB.GetCollection(ctx, "service405_db", "service405_data")
	if err != nil {
		return Service405Data{}, err
	}
	service405Data = Service405Data{
		ID:   id405,
		DataTwo: datatwo405,
	}
	if err := coll.InsertOne(ctx, service405Data); err != nil {
		return Service405Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service406.Method406(ctx, id405, data405, datatwo405); err != nil {
		return Service405Data{}, err
	}

	return service405Data, nil
}

func (s *Service405Impl) MethodOther405(ctx context.Context, id405 string, data405 string, datatwo405 string) (Service405Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service405DB.GetCollection(ctx, "service405_db", "service405_data")
	if err != nil {
		return Service405Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id405},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service405Data{}, err
	}
	var service405Data Service405Data
	exists, err := res.One(ctx, &service405Data)
	if err != nil {
		return Service405Data{}, err
	}
	if exists {
		return service405Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service405DB.GetCollection(ctx, "service405_db", "service405_data")
	if err != nil {
		return Service405Data{}, err
	}
	service405Data = Service405Data{
		ID:   id405,
		DataOther: data405,
	}
	if err := coll.InsertOne(ctx, service405Data); err != nil {
		return Service405Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service405DB.GetCollection(ctx, "service405_db", "service405_data")
	if err != nil {
		return Service405Data{}, err
	}
	service405Data = Service405Data{
		ID:   id405,
		DataOtherTwo: datatwo405,
	}
	if err := coll.InsertOne(ctx, service405Data); err != nil {
		return Service405Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service406.MethodOther406(ctx, id405, data405, datatwo405); err != nil {
		return Service405Data{}, err
	}

	return service405Data, nil
}

func (s *Service405Impl) MethodOtherOther405(ctx context.Context, id405 string, data405 string, datatwo405 string) (Service405Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service405DB.GetCollection(ctx, "service405_db", "service405_data")
	if err != nil {
		return Service405Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id405},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service405Data{}, err
	}
	var service405Data Service405Data
	exists, err := res.One(ctx, &service405Data)
	if err != nil {
		return Service405Data{}, err
	}
	if exists {
		return service405Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service405DB.GetCollection(ctx, "service405_db", "service405_data")
	if err != nil {
		return Service405Data{}, err
	}
	service405Data = Service405Data{
		ID:   id405,
		DataOtherOther: data405,
	}
	if err := coll.InsertOne(ctx, service405Data); err != nil {
		return Service405Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service405DB.GetCollection(ctx, "service405_db", "service405_data")
	if err != nil {
		return Service405Data{}, err
	}
	service405Data = Service405Data{
		ID:   id405,
		DataOtherOtherTwo: datatwo405,
	}
	if err := coll.InsertOne(ctx, service405Data); err != nil {
		return Service405Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service406.MethodOtherOther406(ctx, id405, data405, datatwo405); err != nil {
		return Service405Data{}, err
	}

	return service405Data, nil
}
