// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service178Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service178 interface {
	Method178(ctx context.Context, id string, data string, datatwo string) (Service178Data, error)
	MethodOther178(ctx context.Context, id string, data string, datatwo string) (Service178Data, error)
	MethodOtherOther178(ctx context.Context, id string, data string, datatwo string) (Service178Data, error)
}

type Service178Impl struct {
	service178DB backend.NoSQLDatabase
	service179 Service179
}

func NewService178Impl(ctx context.Context, service178DB backend.NoSQLDatabase, service179 Service179) (Service178, error) {
	return &Service178Impl{
		service178DB: service178DB,
		service179: service179,
	}, nil
}

func (s *Service178Impl) Method178(ctx context.Context, id178 string, data178 string, datatwo178 string) (Service178Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service178DB.GetCollection(ctx, "service178_db", "service178_data")
	if err != nil {
		return Service178Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id178},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service178Data{}, err
	}
	var service178Data Service178Data
	exists, err := res.One(ctx, &service178Data)
	if err != nil {
		return Service178Data{}, err
	}
	if exists {
		return service178Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service178DB.GetCollection(ctx, "service178_db", "service178_data")
	if err != nil {
		return Service178Data{}, err
	}
	service178Data = Service178Data{
		ID:   id178,
		Data: data178,
	}
	if err := coll.InsertOne(ctx, service178Data); err != nil {
		return Service178Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service178DB.GetCollection(ctx, "service178_db", "service178_data")
	if err != nil {
		return Service178Data{}, err
	}
	service178Data = Service178Data{
		ID:   id178,
		DataTwo: datatwo178,
	}
	if err := coll.InsertOne(ctx, service178Data); err != nil {
		return Service178Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service179.Method179(ctx, id178, data178, datatwo178); err != nil {
		return Service178Data{}, err
	}

	return service178Data, nil
}

func (s *Service178Impl) MethodOther178(ctx context.Context, id178 string, data178 string, datatwo178 string) (Service178Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service178DB.GetCollection(ctx, "service178_db", "service178_data")
	if err != nil {
		return Service178Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id178},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service178Data{}, err
	}
	var service178Data Service178Data
	exists, err := res.One(ctx, &service178Data)
	if err != nil {
		return Service178Data{}, err
	}
	if exists {
		return service178Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service178DB.GetCollection(ctx, "service178_db", "service178_data")
	if err != nil {
		return Service178Data{}, err
	}
	service178Data = Service178Data{
		ID:   id178,
		DataOther: data178,
	}
	if err := coll.InsertOne(ctx, service178Data); err != nil {
		return Service178Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service178DB.GetCollection(ctx, "service178_db", "service178_data")
	if err != nil {
		return Service178Data{}, err
	}
	service178Data = Service178Data{
		ID:   id178,
		DataOtherTwo: datatwo178,
	}
	if err := coll.InsertOne(ctx, service178Data); err != nil {
		return Service178Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service179.MethodOther179(ctx, id178, data178, datatwo178); err != nil {
		return Service178Data{}, err
	}

	return service178Data, nil
}

func (s *Service178Impl) MethodOtherOther178(ctx context.Context, id178 string, data178 string, datatwo178 string) (Service178Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service178DB.GetCollection(ctx, "service178_db", "service178_data")
	if err != nil {
		return Service178Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id178},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service178Data{}, err
	}
	var service178Data Service178Data
	exists, err := res.One(ctx, &service178Data)
	if err != nil {
		return Service178Data{}, err
	}
	if exists {
		return service178Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service178DB.GetCollection(ctx, "service178_db", "service178_data")
	if err != nil {
		return Service178Data{}, err
	}
	service178Data = Service178Data{
		ID:   id178,
		DataOtherOther: data178,
	}
	if err := coll.InsertOne(ctx, service178Data); err != nil {
		return Service178Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service178DB.GetCollection(ctx, "service178_db", "service178_data")
	if err != nil {
		return Service178Data{}, err
	}
	service178Data = Service178Data{
		ID:   id178,
		DataOtherOtherTwo: datatwo178,
	}
	if err := coll.InsertOne(ctx, service178Data); err != nil {
		return Service178Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service179.MethodOtherOther179(ctx, id178, data178, datatwo178); err != nil {
		return Service178Data{}, err
	}

	return service178Data, nil
}
