// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service120Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service120 interface {
	Method120(ctx context.Context, id string, data string, datatwo string) (Service120Data, error)
	MethodOther120(ctx context.Context, id string, data string, datatwo string) (Service120Data, error)
	MethodOtherOther120(ctx context.Context, id string, data string, datatwo string) (Service120Data, error)
}

type Service120Impl struct {
	service120DB backend.NoSQLDatabase
	service121 Service121
}

func NewService120Impl(ctx context.Context, service120DB backend.NoSQLDatabase, service121 Service121) (Service120, error) {
	return &Service120Impl{
		service120DB: service120DB,
		service121: service121,
	}, nil
}

func (s *Service120Impl) Method120(ctx context.Context, id120 string, data120 string, datatwo120 string) (Service120Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service120DB.GetCollection(ctx, "service120_db", "service120_data")
	if err != nil {
		return Service120Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id120},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service120Data{}, err
	}
	var service120Data Service120Data
	exists, err := res.One(ctx, &service120Data)
	if err != nil {
		return Service120Data{}, err
	}
	if exists {
		return service120Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service120DB.GetCollection(ctx, "service120_db", "service120_data")
	if err != nil {
		return Service120Data{}, err
	}
	service120Data = Service120Data{
		ID:   id120,
		Data: data120,
	}
	if err := coll.InsertOne(ctx, service120Data); err != nil {
		return Service120Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service120DB.GetCollection(ctx, "service120_db", "service120_data")
	if err != nil {
		return Service120Data{}, err
	}
	service120Data = Service120Data{
		ID:   id120,
		DataTwo: datatwo120,
	}
	if err := coll.InsertOne(ctx, service120Data); err != nil {
		return Service120Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service121.Method121(ctx, id120, data120, datatwo120); err != nil {
		return Service120Data{}, err
	}

	return service120Data, nil
}

func (s *Service120Impl) MethodOther120(ctx context.Context, id120 string, data120 string, datatwo120 string) (Service120Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service120DB.GetCollection(ctx, "service120_db", "service120_data")
	if err != nil {
		return Service120Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id120},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service120Data{}, err
	}
	var service120Data Service120Data
	exists, err := res.One(ctx, &service120Data)
	if err != nil {
		return Service120Data{}, err
	}
	if exists {
		return service120Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service120DB.GetCollection(ctx, "service120_db", "service120_data")
	if err != nil {
		return Service120Data{}, err
	}
	service120Data = Service120Data{
		ID:   id120,
		DataOther: data120,
	}
	if err := coll.InsertOne(ctx, service120Data); err != nil {
		return Service120Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service120DB.GetCollection(ctx, "service120_db", "service120_data")
	if err != nil {
		return Service120Data{}, err
	}
	service120Data = Service120Data{
		ID:   id120,
		DataOtherTwo: datatwo120,
	}
	if err := coll.InsertOne(ctx, service120Data); err != nil {
		return Service120Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service121.MethodOther121(ctx, id120, data120, datatwo120); err != nil {
		return Service120Data{}, err
	}

	return service120Data, nil
}

func (s *Service120Impl) MethodOtherOther120(ctx context.Context, id120 string, data120 string, datatwo120 string) (Service120Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service120DB.GetCollection(ctx, "service120_db", "service120_data")
	if err != nil {
		return Service120Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id120},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service120Data{}, err
	}
	var service120Data Service120Data
	exists, err := res.One(ctx, &service120Data)
	if err != nil {
		return Service120Data{}, err
	}
	if exists {
		return service120Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service120DB.GetCollection(ctx, "service120_db", "service120_data")
	if err != nil {
		return Service120Data{}, err
	}
	service120Data = Service120Data{
		ID:   id120,
		DataOtherOther: data120,
	}
	if err := coll.InsertOne(ctx, service120Data); err != nil {
		return Service120Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service120DB.GetCollection(ctx, "service120_db", "service120_data")
	if err != nil {
		return Service120Data{}, err
	}
	service120Data = Service120Data{
		ID:   id120,
		DataOtherOtherTwo: datatwo120,
	}
	if err := coll.InsertOne(ctx, service120Data); err != nil {
		return Service120Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service121.MethodOtherOther121(ctx, id120, data120, datatwo120); err != nil {
		return Service120Data{}, err
	}

	return service120Data, nil
}
