// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service99Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service99 interface {
	Method99(ctx context.Context, id string, data string, datatwo string) (Service99Data, error)
	MethodOther99(ctx context.Context, id string, data string, datatwo string) (Service99Data, error)
	MethodOtherOther99(ctx context.Context, id string, data string, datatwo string) (Service99Data, error)
}

type Service99Impl struct {
	service99DB backend.NoSQLDatabase
	service100 Service100
}

func NewService99Impl(ctx context.Context, service99DB backend.NoSQLDatabase, service100 Service100) (Service99, error) {
	return &Service99Impl{
		service99DB: service99DB,
		service100: service100,
	}, nil
}

func (s *Service99Impl) Method99(ctx context.Context, id99 string, data99 string, datatwo99 string) (Service99Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id99},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service99Data{}, err
	}
	var service99Data Service99Data
	exists, err := res.One(ctx, &service99Data)
	if err != nil {
		return Service99Data{}, err
	}
	if exists {
		return service99Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	service99Data = Service99Data{
		ID:   id99,
		Data: data99,
	}
	if err := coll.InsertOne(ctx, service99Data); err != nil {
		return Service99Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	service99Data = Service99Data{
		ID:   id99,
		DataTwo: datatwo99,
	}
	if err := coll.InsertOne(ctx, service99Data); err != nil {
		return Service99Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service100.Method100(ctx, id99, data99, datatwo99); err != nil {
		return Service99Data{}, err
	}

	return service99Data, nil
}

func (s *Service99Impl) MethodOther99(ctx context.Context, id99 string, data99 string, datatwo99 string) (Service99Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id99},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service99Data{}, err
	}
	var service99Data Service99Data
	exists, err := res.One(ctx, &service99Data)
	if err != nil {
		return Service99Data{}, err
	}
	if exists {
		return service99Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	service99Data = Service99Data{
		ID:   id99,
		DataOther: data99,
	}
	if err := coll.InsertOne(ctx, service99Data); err != nil {
		return Service99Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	service99Data = Service99Data{
		ID:   id99,
		DataOtherTwo: datatwo99,
	}
	if err := coll.InsertOne(ctx, service99Data); err != nil {
		return Service99Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service100.MethodOther100(ctx, id99, data99, datatwo99); err != nil {
		return Service99Data{}, err
	}

	return service99Data, nil
}

func (s *Service99Impl) MethodOtherOther99(ctx context.Context, id99 string, data99 string, datatwo99 string) (Service99Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id99},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service99Data{}, err
	}
	var service99Data Service99Data
	exists, err := res.One(ctx, &service99Data)
	if err != nil {
		return Service99Data{}, err
	}
	if exists {
		return service99Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	service99Data = Service99Data{
		ID:   id99,
		DataOtherOther: data99,
	}
	if err := coll.InsertOne(ctx, service99Data); err != nil {
		return Service99Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	service99Data = Service99Data{
		ID:   id99,
		DataOtherOtherTwo: datatwo99,
	}
	if err := coll.InsertOne(ctx, service99Data); err != nil {
		return Service99Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service100.MethodOtherOther100(ctx, id99, data99, datatwo99); err != nil {
		return Service99Data{}, err
	}

	return service99Data, nil
}
