// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service206Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service206 interface {
	Method206(ctx context.Context, id string, data string, datatwo string) (Service206Data, error)
	MethodOther206(ctx context.Context, id string, data string, datatwo string) (Service206Data, error)
	MethodOtherOther206(ctx context.Context, id string, data string, datatwo string) (Service206Data, error)
}

type Service206Impl struct {
	service206DB backend.NoSQLDatabase
	service207 Service207
}

func NewService206Impl(ctx context.Context, service206DB backend.NoSQLDatabase, service207 Service207) (Service206, error) {
	return &Service206Impl{
		service206DB: service206DB,
		service207: service207,
	}, nil
}

func (s *Service206Impl) Method206(ctx context.Context, id206 string, data206 string, datatwo206 string) (Service206Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service206DB.GetCollection(ctx, "service206_db", "service206_data")
	if err != nil {
		return Service206Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id206},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service206Data{}, err
	}
	var service206Data Service206Data
	exists, err := res.One(ctx, &service206Data)
	if err != nil {
		return Service206Data{}, err
	}
	if exists {
		return service206Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service206DB.GetCollection(ctx, "service206_db", "service206_data")
	if err != nil {
		return Service206Data{}, err
	}
	service206Data = Service206Data{
		ID:   id206,
		Data: data206,
	}
	if err := coll.InsertOne(ctx, service206Data); err != nil {
		return Service206Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service206DB.GetCollection(ctx, "service206_db", "service206_data")
	if err != nil {
		return Service206Data{}, err
	}
	service206Data = Service206Data{
		ID:   id206,
		DataTwo: datatwo206,
	}
	if err := coll.InsertOne(ctx, service206Data); err != nil {
		return Service206Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service207.Method207(ctx, id206, data206, datatwo206); err != nil {
		return Service206Data{}, err
	}

	return service206Data, nil
}

func (s *Service206Impl) MethodOther206(ctx context.Context, id206 string, data206 string, datatwo206 string) (Service206Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service206DB.GetCollection(ctx, "service206_db", "service206_data")
	if err != nil {
		return Service206Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id206},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service206Data{}, err
	}
	var service206Data Service206Data
	exists, err := res.One(ctx, &service206Data)
	if err != nil {
		return Service206Data{}, err
	}
	if exists {
		return service206Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service206DB.GetCollection(ctx, "service206_db", "service206_data")
	if err != nil {
		return Service206Data{}, err
	}
	service206Data = Service206Data{
		ID:   id206,
		DataOther: data206,
	}
	if err := coll.InsertOne(ctx, service206Data); err != nil {
		return Service206Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service206DB.GetCollection(ctx, "service206_db", "service206_data")
	if err != nil {
		return Service206Data{}, err
	}
	service206Data = Service206Data{
		ID:   id206,
		DataOtherTwo: datatwo206,
	}
	if err := coll.InsertOne(ctx, service206Data); err != nil {
		return Service206Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service207.MethodOther207(ctx, id206, data206, datatwo206); err != nil {
		return Service206Data{}, err
	}

	return service206Data, nil
}

func (s *Service206Impl) MethodOtherOther206(ctx context.Context, id206 string, data206 string, datatwo206 string) (Service206Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service206DB.GetCollection(ctx, "service206_db", "service206_data")
	if err != nil {
		return Service206Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id206},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service206Data{}, err
	}
	var service206Data Service206Data
	exists, err := res.One(ctx, &service206Data)
	if err != nil {
		return Service206Data{}, err
	}
	if exists {
		return service206Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service206DB.GetCollection(ctx, "service206_db", "service206_data")
	if err != nil {
		return Service206Data{}, err
	}
	service206Data = Service206Data{
		ID:   id206,
		DataOtherOther: data206,
	}
	if err := coll.InsertOne(ctx, service206Data); err != nil {
		return Service206Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service206DB.GetCollection(ctx, "service206_db", "service206_data")
	if err != nil {
		return Service206Data{}, err
	}
	service206Data = Service206Data{
		ID:   id206,
		DataOtherOtherTwo: datatwo206,
	}
	if err := coll.InsertOne(ctx, service206Data); err != nil {
		return Service206Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service207.MethodOtherOther207(ctx, id206, data206, datatwo206); err != nil {
		return Service206Data{}, err
	}

	return service206Data, nil
}
