// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service25Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service25 interface {
	Method25(ctx context.Context, id string, data string, datatwo string) (Service25Data, error)
	MethodOther25(ctx context.Context, id string, data string, datatwo string) (Service25Data, error)
	MethodOtherOther25(ctx context.Context, id string, data string, datatwo string) (Service25Data, error)
}

type Service25Impl struct {
	service25DB backend.NoSQLDatabase
	service26 Service26
}

func NewService25Impl(ctx context.Context, service25DB backend.NoSQLDatabase, service26 Service26) (Service25, error) {
	return &Service25Impl{
		service25DB: service25DB,
		service26: service26,
	}, nil
}

func (s *Service25Impl) Method25(ctx context.Context, id25 string, data25 string, datatwo25 string) (Service25Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service25DB.GetCollection(ctx, "service25_db", "service25_data")
	if err != nil {
		return Service25Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id25},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service25Data{}, err
	}
	var service25Data Service25Data
	exists, err := res.One(ctx, &service25Data)
	if err != nil {
		return Service25Data{}, err
	}
	if exists {
		return service25Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service25DB.GetCollection(ctx, "service25_db", "service25_data")
	if err != nil {
		return Service25Data{}, err
	}
	service25Data = Service25Data{
		ID:   id25,
		Data: data25,
	}
	if err := coll.InsertOne(ctx, service25Data); err != nil {
		return Service25Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service25DB.GetCollection(ctx, "service25_db", "service25_data")
	if err != nil {
		return Service25Data{}, err
	}
	service25Data = Service25Data{
		ID:   id25,
		DataTwo: datatwo25,
	}
	if err := coll.InsertOne(ctx, service25Data); err != nil {
		return Service25Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service26.Method26(ctx, id25, data25, datatwo25); err != nil {
		return Service25Data{}, err
	}

	return service25Data, nil
}

func (s *Service25Impl) MethodOther25(ctx context.Context, id25 string, data25 string, datatwo25 string) (Service25Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service25DB.GetCollection(ctx, "service25_db", "service25_data")
	if err != nil {
		return Service25Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id25},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service25Data{}, err
	}
	var service25Data Service25Data
	exists, err := res.One(ctx, &service25Data)
	if err != nil {
		return Service25Data{}, err
	}
	if exists {
		return service25Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service25DB.GetCollection(ctx, "service25_db", "service25_data")
	if err != nil {
		return Service25Data{}, err
	}
	service25Data = Service25Data{
		ID:   id25,
		DataOther: data25,
	}
	if err := coll.InsertOne(ctx, service25Data); err != nil {
		return Service25Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service25DB.GetCollection(ctx, "service25_db", "service25_data")
	if err != nil {
		return Service25Data{}, err
	}
	service25Data = Service25Data{
		ID:   id25,
		DataOtherTwo: datatwo25,
	}
	if err := coll.InsertOne(ctx, service25Data); err != nil {
		return Service25Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service26.MethodOther26(ctx, id25, data25, datatwo25); err != nil {
		return Service25Data{}, err
	}

	return service25Data, nil
}

func (s *Service25Impl) MethodOtherOther25(ctx context.Context, id25 string, data25 string, datatwo25 string) (Service25Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service25DB.GetCollection(ctx, "service25_db", "service25_data")
	if err != nil {
		return Service25Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id25},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service25Data{}, err
	}
	var service25Data Service25Data
	exists, err := res.One(ctx, &service25Data)
	if err != nil {
		return Service25Data{}, err
	}
	if exists {
		return service25Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service25DB.GetCollection(ctx, "service25_db", "service25_data")
	if err != nil {
		return Service25Data{}, err
	}
	service25Data = Service25Data{
		ID:   id25,
		DataOtherOther: data25,
	}
	if err := coll.InsertOne(ctx, service25Data); err != nil {
		return Service25Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service25DB.GetCollection(ctx, "service25_db", "service25_data")
	if err != nil {
		return Service25Data{}, err
	}
	service25Data = Service25Data{
		ID:   id25,
		DataOtherOtherTwo: datatwo25,
	}
	if err := coll.InsertOne(ctx, service25Data); err != nil {
		return Service25Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service26.MethodOtherOther26(ctx, id25, data25, datatwo25); err != nil {
		return Service25Data{}, err
	}

	return service25Data, nil
}
