// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service175Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service175 interface {
	Method175(ctx context.Context, id string, data string, datatwo string) (Service175Data, error)
	MethodOther175(ctx context.Context, id string, data string, datatwo string) (Service175Data, error)
	MethodOtherOther175(ctx context.Context, id string, data string, datatwo string) (Service175Data, error)
}

type Service175Impl struct {
	service175DB backend.NoSQLDatabase
	service176 Service176
}

func NewService175Impl(ctx context.Context, service175DB backend.NoSQLDatabase, service176 Service176) (Service175, error) {
	return &Service175Impl{
		service175DB: service175DB,
		service176: service176,
	}, nil
}

func (s *Service175Impl) Method175(ctx context.Context, id175 string, data175 string, datatwo175 string) (Service175Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service175DB.GetCollection(ctx, "service175_db", "service175_data")
	if err != nil {
		return Service175Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id175},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service175Data{}, err
	}
	var service175Data Service175Data
	exists, err := res.One(ctx, &service175Data)
	if err != nil {
		return Service175Data{}, err
	}
	if exists {
		return service175Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service175DB.GetCollection(ctx, "service175_db", "service175_data")
	if err != nil {
		return Service175Data{}, err
	}
	service175Data = Service175Data{
		ID:   id175,
		Data: data175,
	}
	if err := coll.InsertOne(ctx, service175Data); err != nil {
		return Service175Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service175DB.GetCollection(ctx, "service175_db", "service175_data")
	if err != nil {
		return Service175Data{}, err
	}
	service175Data = Service175Data{
		ID:   id175,
		DataTwo: datatwo175,
	}
	if err := coll.InsertOne(ctx, service175Data); err != nil {
		return Service175Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service176.Method176(ctx, id175, data175, datatwo175); err != nil {
		return Service175Data{}, err
	}

	return service175Data, nil
}

func (s *Service175Impl) MethodOther175(ctx context.Context, id175 string, data175 string, datatwo175 string) (Service175Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service175DB.GetCollection(ctx, "service175_db", "service175_data")
	if err != nil {
		return Service175Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id175},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service175Data{}, err
	}
	var service175Data Service175Data
	exists, err := res.One(ctx, &service175Data)
	if err != nil {
		return Service175Data{}, err
	}
	if exists {
		return service175Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service175DB.GetCollection(ctx, "service175_db", "service175_data")
	if err != nil {
		return Service175Data{}, err
	}
	service175Data = Service175Data{
		ID:   id175,
		DataOther: data175,
	}
	if err := coll.InsertOne(ctx, service175Data); err != nil {
		return Service175Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service175DB.GetCollection(ctx, "service175_db", "service175_data")
	if err != nil {
		return Service175Data{}, err
	}
	service175Data = Service175Data{
		ID:   id175,
		DataOtherTwo: datatwo175,
	}
	if err := coll.InsertOne(ctx, service175Data); err != nil {
		return Service175Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service176.MethodOther176(ctx, id175, data175, datatwo175); err != nil {
		return Service175Data{}, err
	}

	return service175Data, nil
}

func (s *Service175Impl) MethodOtherOther175(ctx context.Context, id175 string, data175 string, datatwo175 string) (Service175Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service175DB.GetCollection(ctx, "service175_db", "service175_data")
	if err != nil {
		return Service175Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id175},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service175Data{}, err
	}
	var service175Data Service175Data
	exists, err := res.One(ctx, &service175Data)
	if err != nil {
		return Service175Data{}, err
	}
	if exists {
		return service175Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service175DB.GetCollection(ctx, "service175_db", "service175_data")
	if err != nil {
		return Service175Data{}, err
	}
	service175Data = Service175Data{
		ID:   id175,
		DataOtherOther: data175,
	}
	if err := coll.InsertOne(ctx, service175Data); err != nil {
		return Service175Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service175DB.GetCollection(ctx, "service175_db", "service175_data")
	if err != nil {
		return Service175Data{}, err
	}
	service175Data = Service175Data{
		ID:   id175,
		DataOtherOtherTwo: datatwo175,
	}
	if err := coll.InsertOne(ctx, service175Data); err != nil {
		return Service175Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service176.MethodOtherOther176(ctx, id175, data175, datatwo175); err != nil {
		return Service175Data{}, err
	}

	return service175Data, nil
}
