// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service35Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service35 interface {
	Method35(ctx context.Context, id string, data string, datatwo string) (Service35Data, error)
	MethodOther35(ctx context.Context, id string, data string, datatwo string) (Service35Data, error)
	MethodOtherOther35(ctx context.Context, id string, data string, datatwo string) (Service35Data, error)
}

type Service35Impl struct {
	service35DB backend.NoSQLDatabase
	service36 Service36
}

func NewService35Impl(ctx context.Context, service35DB backend.NoSQLDatabase, service36 Service36) (Service35, error) {
	return &Service35Impl{
		service35DB: service35DB,
		service36: service36,
	}, nil
}

func (s *Service35Impl) Method35(ctx context.Context, id35 string, data35 string, datatwo35 string) (Service35Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service35DB.GetCollection(ctx, "service35_db", "service35_data")
	if err != nil {
		return Service35Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id35},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service35Data{}, err
	}
	var service35Data Service35Data
	exists, err := res.One(ctx, &service35Data)
	if err != nil {
		return Service35Data{}, err
	}
	if exists {
		return service35Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service35DB.GetCollection(ctx, "service35_db", "service35_data")
	if err != nil {
		return Service35Data{}, err
	}
	service35Data = Service35Data{
		ID:   id35,
		Data: data35,
	}
	if err := coll.InsertOne(ctx, service35Data); err != nil {
		return Service35Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service35DB.GetCollection(ctx, "service35_db", "service35_data")
	if err != nil {
		return Service35Data{}, err
	}
	service35Data = Service35Data{
		ID:   id35,
		DataTwo: datatwo35,
	}
	if err := coll.InsertOne(ctx, service35Data); err != nil {
		return Service35Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service36.Method36(ctx, id35, data35, datatwo35); err != nil {
		return Service35Data{}, err
	}

	return service35Data, nil
}

func (s *Service35Impl) MethodOther35(ctx context.Context, id35 string, data35 string, datatwo35 string) (Service35Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service35DB.GetCollection(ctx, "service35_db", "service35_data")
	if err != nil {
		return Service35Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id35},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service35Data{}, err
	}
	var service35Data Service35Data
	exists, err := res.One(ctx, &service35Data)
	if err != nil {
		return Service35Data{}, err
	}
	if exists {
		return service35Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service35DB.GetCollection(ctx, "service35_db", "service35_data")
	if err != nil {
		return Service35Data{}, err
	}
	service35Data = Service35Data{
		ID:   id35,
		DataOther: data35,
	}
	if err := coll.InsertOne(ctx, service35Data); err != nil {
		return Service35Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service35DB.GetCollection(ctx, "service35_db", "service35_data")
	if err != nil {
		return Service35Data{}, err
	}
	service35Data = Service35Data{
		ID:   id35,
		DataOtherTwo: datatwo35,
	}
	if err := coll.InsertOne(ctx, service35Data); err != nil {
		return Service35Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service36.MethodOther36(ctx, id35, data35, datatwo35); err != nil {
		return Service35Data{}, err
	}

	return service35Data, nil
}

func (s *Service35Impl) MethodOtherOther35(ctx context.Context, id35 string, data35 string, datatwo35 string) (Service35Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service35DB.GetCollection(ctx, "service35_db", "service35_data")
	if err != nil {
		return Service35Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id35},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service35Data{}, err
	}
	var service35Data Service35Data
	exists, err := res.One(ctx, &service35Data)
	if err != nil {
		return Service35Data{}, err
	}
	if exists {
		return service35Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service35DB.GetCollection(ctx, "service35_db", "service35_data")
	if err != nil {
		return Service35Data{}, err
	}
	service35Data = Service35Data{
		ID:   id35,
		DataOtherOther: data35,
	}
	if err := coll.InsertOne(ctx, service35Data); err != nil {
		return Service35Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service35DB.GetCollection(ctx, "service35_db", "service35_data")
	if err != nil {
		return Service35Data{}, err
	}
	service35Data = Service35Data{
		ID:   id35,
		DataOtherOtherTwo: datatwo35,
	}
	if err := coll.InsertOne(ctx, service35Data); err != nil {
		return Service35Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service36.MethodOtherOther36(ctx, id35, data35, datatwo35); err != nil {
		return Service35Data{}, err
	}

	return service35Data, nil
}
