// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service397Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service397 interface {
	Method397(ctx context.Context, id string, data string, datatwo string) (Service397Data, error)
	MethodOther397(ctx context.Context, id string, data string, datatwo string) (Service397Data, error)
	MethodOtherOther397(ctx context.Context, id string, data string, datatwo string) (Service397Data, error)
}

type Service397Impl struct {
	service397DB backend.NoSQLDatabase
	service398 Service398
}

func NewService397Impl(ctx context.Context, service397DB backend.NoSQLDatabase, service398 Service398) (Service397, error) {
	return &Service397Impl{
		service397DB: service397DB,
		service398: service398,
	}, nil
}

func (s *Service397Impl) Method397(ctx context.Context, id397 string, data397 string, datatwo397 string) (Service397Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service397DB.GetCollection(ctx, "service397_db", "service397_data")
	if err != nil {
		return Service397Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id397},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service397Data{}, err
	}
	var service397Data Service397Data
	exists, err := res.One(ctx, &service397Data)
	if err != nil {
		return Service397Data{}, err
	}
	if exists {
		return service397Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service397DB.GetCollection(ctx, "service397_db", "service397_data")
	if err != nil {
		return Service397Data{}, err
	}
	service397Data = Service397Data{
		ID:   id397,
		Data: data397,
	}
	if err := coll.InsertOne(ctx, service397Data); err != nil {
		return Service397Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service397DB.GetCollection(ctx, "service397_db", "service397_data")
	if err != nil {
		return Service397Data{}, err
	}
	service397Data = Service397Data{
		ID:   id397,
		DataTwo: datatwo397,
	}
	if err := coll.InsertOne(ctx, service397Data); err != nil {
		return Service397Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service398.Method398(ctx, id397, data397, datatwo397); err != nil {
		return Service397Data{}, err
	}

	return service397Data, nil
}

func (s *Service397Impl) MethodOther397(ctx context.Context, id397 string, data397 string, datatwo397 string) (Service397Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service397DB.GetCollection(ctx, "service397_db", "service397_data")
	if err != nil {
		return Service397Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id397},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service397Data{}, err
	}
	var service397Data Service397Data
	exists, err := res.One(ctx, &service397Data)
	if err != nil {
		return Service397Data{}, err
	}
	if exists {
		return service397Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service397DB.GetCollection(ctx, "service397_db", "service397_data")
	if err != nil {
		return Service397Data{}, err
	}
	service397Data = Service397Data{
		ID:   id397,
		DataOther: data397,
	}
	if err := coll.InsertOne(ctx, service397Data); err != nil {
		return Service397Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service397DB.GetCollection(ctx, "service397_db", "service397_data")
	if err != nil {
		return Service397Data{}, err
	}
	service397Data = Service397Data{
		ID:   id397,
		DataOtherTwo: datatwo397,
	}
	if err := coll.InsertOne(ctx, service397Data); err != nil {
		return Service397Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service398.MethodOther398(ctx, id397, data397, datatwo397); err != nil {
		return Service397Data{}, err
	}

	return service397Data, nil
}

func (s *Service397Impl) MethodOtherOther397(ctx context.Context, id397 string, data397 string, datatwo397 string) (Service397Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service397DB.GetCollection(ctx, "service397_db", "service397_data")
	if err != nil {
		return Service397Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id397},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service397Data{}, err
	}
	var service397Data Service397Data
	exists, err := res.One(ctx, &service397Data)
	if err != nil {
		return Service397Data{}, err
	}
	if exists {
		return service397Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service397DB.GetCollection(ctx, "service397_db", "service397_data")
	if err != nil {
		return Service397Data{}, err
	}
	service397Data = Service397Data{
		ID:   id397,
		DataOtherOther: data397,
	}
	if err := coll.InsertOne(ctx, service397Data); err != nil {
		return Service397Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service397DB.GetCollection(ctx, "service397_db", "service397_data")
	if err != nil {
		return Service397Data{}, err
	}
	service397Data = Service397Data{
		ID:   id397,
		DataOtherOtherTwo: datatwo397,
	}
	if err := coll.InsertOne(ctx, service397Data); err != nil {
		return Service397Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service398.MethodOtherOther398(ctx, id397, data397, datatwo397); err != nil {
		return Service397Data{}, err
	}

	return service397Data, nil
}
