// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service419Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service419 interface {
	Method419(ctx context.Context, id string, data string, datatwo string) (Service419Data, error)
	MethodOther419(ctx context.Context, id string, data string, datatwo string) (Service419Data, error)
	MethodOtherOther419(ctx context.Context, id string, data string, datatwo string) (Service419Data, error)
}

type Service419Impl struct {
	service419DB backend.NoSQLDatabase
	service420 Service420
}

func NewService419Impl(ctx context.Context, service419DB backend.NoSQLDatabase, service420 Service420) (Service419, error) {
	return &Service419Impl{
		service419DB: service419DB,
		service420: service420,
	}, nil
}

func (s *Service419Impl) Method419(ctx context.Context, id419 string, data419 string, datatwo419 string) (Service419Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service419DB.GetCollection(ctx, "service419_db", "service419_data")
	if err != nil {
		return Service419Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id419},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service419Data{}, err
	}
	var service419Data Service419Data
	exists, err := res.One(ctx, &service419Data)
	if err != nil {
		return Service419Data{}, err
	}
	if exists {
		return service419Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service419DB.GetCollection(ctx, "service419_db", "service419_data")
	if err != nil {
		return Service419Data{}, err
	}
	service419Data = Service419Data{
		ID:   id419,
		Data: data419,
	}
	if err := coll.InsertOne(ctx, service419Data); err != nil {
		return Service419Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service419DB.GetCollection(ctx, "service419_db", "service419_data")
	if err != nil {
		return Service419Data{}, err
	}
	service419Data = Service419Data{
		ID:   id419,
		DataTwo: datatwo419,
	}
	if err := coll.InsertOne(ctx, service419Data); err != nil {
		return Service419Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service420.Method420(ctx, id419, data419, datatwo419); err != nil {
		return Service419Data{}, err
	}

	return service419Data, nil
}

func (s *Service419Impl) MethodOther419(ctx context.Context, id419 string, data419 string, datatwo419 string) (Service419Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service419DB.GetCollection(ctx, "service419_db", "service419_data")
	if err != nil {
		return Service419Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id419},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service419Data{}, err
	}
	var service419Data Service419Data
	exists, err := res.One(ctx, &service419Data)
	if err != nil {
		return Service419Data{}, err
	}
	if exists {
		return service419Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service419DB.GetCollection(ctx, "service419_db", "service419_data")
	if err != nil {
		return Service419Data{}, err
	}
	service419Data = Service419Data{
		ID:   id419,
		DataOther: data419,
	}
	if err := coll.InsertOne(ctx, service419Data); err != nil {
		return Service419Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service419DB.GetCollection(ctx, "service419_db", "service419_data")
	if err != nil {
		return Service419Data{}, err
	}
	service419Data = Service419Data{
		ID:   id419,
		DataOtherTwo: datatwo419,
	}
	if err := coll.InsertOne(ctx, service419Data); err != nil {
		return Service419Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service420.MethodOther420(ctx, id419, data419, datatwo419); err != nil {
		return Service419Data{}, err
	}

	return service419Data, nil
}

func (s *Service419Impl) MethodOtherOther419(ctx context.Context, id419 string, data419 string, datatwo419 string) (Service419Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service419DB.GetCollection(ctx, "service419_db", "service419_data")
	if err != nil {
		return Service419Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id419},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service419Data{}, err
	}
	var service419Data Service419Data
	exists, err := res.One(ctx, &service419Data)
	if err != nil {
		return Service419Data{}, err
	}
	if exists {
		return service419Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service419DB.GetCollection(ctx, "service419_db", "service419_data")
	if err != nil {
		return Service419Data{}, err
	}
	service419Data = Service419Data{
		ID:   id419,
		DataOtherOther: data419,
	}
	if err := coll.InsertOne(ctx, service419Data); err != nil {
		return Service419Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service419DB.GetCollection(ctx, "service419_db", "service419_data")
	if err != nil {
		return Service419Data{}, err
	}
	service419Data = Service419Data{
		ID:   id419,
		DataOtherOtherTwo: datatwo419,
	}
	if err := coll.InsertOne(ctx, service419Data); err != nil {
		return Service419Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service420.MethodOtherOther420(ctx, id419, data419, datatwo419); err != nil {
		return Service419Data{}, err
	}

	return service419Data, nil
}
