// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service182Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service182 interface {
	Method182(ctx context.Context, id string, data string, datatwo string) (Service182Data, error)
	MethodOther182(ctx context.Context, id string, data string, datatwo string) (Service182Data, error)
	MethodOtherOther182(ctx context.Context, id string, data string, datatwo string) (Service182Data, error)
}

type Service182Impl struct {
	service182DB backend.NoSQLDatabase
	service183 Service183
}

func NewService182Impl(ctx context.Context, service182DB backend.NoSQLDatabase, service183 Service183) (Service182, error) {
	return &Service182Impl{
		service182DB: service182DB,
		service183: service183,
	}, nil
}

func (s *Service182Impl) Method182(ctx context.Context, id182 string, data182 string, datatwo182 string) (Service182Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service182DB.GetCollection(ctx, "service182_db", "service182_data")
	if err != nil {
		return Service182Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id182},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service182Data{}, err
	}
	var service182Data Service182Data
	exists, err := res.One(ctx, &service182Data)
	if err != nil {
		return Service182Data{}, err
	}
	if exists {
		return service182Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service182DB.GetCollection(ctx, "service182_db", "service182_data")
	if err != nil {
		return Service182Data{}, err
	}
	service182Data = Service182Data{
		ID:   id182,
		Data: data182,
	}
	if err := coll.InsertOne(ctx, service182Data); err != nil {
		return Service182Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service182DB.GetCollection(ctx, "service182_db", "service182_data")
	if err != nil {
		return Service182Data{}, err
	}
	service182Data = Service182Data{
		ID:   id182,
		DataTwo: datatwo182,
	}
	if err := coll.InsertOne(ctx, service182Data); err != nil {
		return Service182Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service183.Method183(ctx, id182, data182, datatwo182); err != nil {
		return Service182Data{}, err
	}

	return service182Data, nil
}

func (s *Service182Impl) MethodOther182(ctx context.Context, id182 string, data182 string, datatwo182 string) (Service182Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service182DB.GetCollection(ctx, "service182_db", "service182_data")
	if err != nil {
		return Service182Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id182},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service182Data{}, err
	}
	var service182Data Service182Data
	exists, err := res.One(ctx, &service182Data)
	if err != nil {
		return Service182Data{}, err
	}
	if exists {
		return service182Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service182DB.GetCollection(ctx, "service182_db", "service182_data")
	if err != nil {
		return Service182Data{}, err
	}
	service182Data = Service182Data{
		ID:   id182,
		DataOther: data182,
	}
	if err := coll.InsertOne(ctx, service182Data); err != nil {
		return Service182Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service182DB.GetCollection(ctx, "service182_db", "service182_data")
	if err != nil {
		return Service182Data{}, err
	}
	service182Data = Service182Data{
		ID:   id182,
		DataOtherTwo: datatwo182,
	}
	if err := coll.InsertOne(ctx, service182Data); err != nil {
		return Service182Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service183.MethodOther183(ctx, id182, data182, datatwo182); err != nil {
		return Service182Data{}, err
	}

	return service182Data, nil
}

func (s *Service182Impl) MethodOtherOther182(ctx context.Context, id182 string, data182 string, datatwo182 string) (Service182Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service182DB.GetCollection(ctx, "service182_db", "service182_data")
	if err != nil {
		return Service182Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id182},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service182Data{}, err
	}
	var service182Data Service182Data
	exists, err := res.One(ctx, &service182Data)
	if err != nil {
		return Service182Data{}, err
	}
	if exists {
		return service182Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service182DB.GetCollection(ctx, "service182_db", "service182_data")
	if err != nil {
		return Service182Data{}, err
	}
	service182Data = Service182Data{
		ID:   id182,
		DataOtherOther: data182,
	}
	if err := coll.InsertOne(ctx, service182Data); err != nil {
		return Service182Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service182DB.GetCollection(ctx, "service182_db", "service182_data")
	if err != nil {
		return Service182Data{}, err
	}
	service182Data = Service182Data{
		ID:   id182,
		DataOtherOtherTwo: datatwo182,
	}
	if err := coll.InsertOne(ctx, service182Data); err != nil {
		return Service182Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service183.MethodOtherOther183(ctx, id182, data182, datatwo182); err != nil {
		return Service182Data{}, err
	}

	return service182Data, nil
}
