// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service299Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service299 interface {
	Method299(ctx context.Context, id string, data string, datatwo string) (Service299Data, error)
	MethodOther299(ctx context.Context, id string, data string, datatwo string) (Service299Data, error)
	MethodOtherOther299(ctx context.Context, id string, data string, datatwo string) (Service299Data, error)
}

type Service299Impl struct {
	service299DB backend.NoSQLDatabase
	service300 Service300
}

func NewService299Impl(ctx context.Context, service299DB backend.NoSQLDatabase, service300 Service300) (Service299, error) {
	return &Service299Impl{
		service299DB: service299DB,
		service300: service300,
	}, nil
}

func (s *Service299Impl) Method299(ctx context.Context, id299 string, data299 string, datatwo299 string) (Service299Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service299DB.GetCollection(ctx, "service299_db", "service299_data")
	if err != nil {
		return Service299Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id299},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service299Data{}, err
	}
	var service299Data Service299Data
	exists, err := res.One(ctx, &service299Data)
	if err != nil {
		return Service299Data{}, err
	}
	if exists {
		return service299Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service299DB.GetCollection(ctx, "service299_db", "service299_data")
	if err != nil {
		return Service299Data{}, err
	}
	service299Data = Service299Data{
		ID:   id299,
		Data: data299,
	}
	if err := coll.InsertOne(ctx, service299Data); err != nil {
		return Service299Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service299DB.GetCollection(ctx, "service299_db", "service299_data")
	if err != nil {
		return Service299Data{}, err
	}
	service299Data = Service299Data{
		ID:   id299,
		DataTwo: datatwo299,
	}
	if err := coll.InsertOne(ctx, service299Data); err != nil {
		return Service299Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service300.Method300(ctx, id299, data299, datatwo299); err != nil {
		return Service299Data{}, err
	}

	return service299Data, nil
}

func (s *Service299Impl) MethodOther299(ctx context.Context, id299 string, data299 string, datatwo299 string) (Service299Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service299DB.GetCollection(ctx, "service299_db", "service299_data")
	if err != nil {
		return Service299Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id299},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service299Data{}, err
	}
	var service299Data Service299Data
	exists, err := res.One(ctx, &service299Data)
	if err != nil {
		return Service299Data{}, err
	}
	if exists {
		return service299Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service299DB.GetCollection(ctx, "service299_db", "service299_data")
	if err != nil {
		return Service299Data{}, err
	}
	service299Data = Service299Data{
		ID:   id299,
		DataOther: data299,
	}
	if err := coll.InsertOne(ctx, service299Data); err != nil {
		return Service299Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service299DB.GetCollection(ctx, "service299_db", "service299_data")
	if err != nil {
		return Service299Data{}, err
	}
	service299Data = Service299Data{
		ID:   id299,
		DataOtherTwo: datatwo299,
	}
	if err := coll.InsertOne(ctx, service299Data); err != nil {
		return Service299Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service300.MethodOther300(ctx, id299, data299, datatwo299); err != nil {
		return Service299Data{}, err
	}

	return service299Data, nil
}

func (s *Service299Impl) MethodOtherOther299(ctx context.Context, id299 string, data299 string, datatwo299 string) (Service299Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service299DB.GetCollection(ctx, "service299_db", "service299_data")
	if err != nil {
		return Service299Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id299},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service299Data{}, err
	}
	var service299Data Service299Data
	exists, err := res.One(ctx, &service299Data)
	if err != nil {
		return Service299Data{}, err
	}
	if exists {
		return service299Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service299DB.GetCollection(ctx, "service299_db", "service299_data")
	if err != nil {
		return Service299Data{}, err
	}
	service299Data = Service299Data{
		ID:   id299,
		DataOtherOther: data299,
	}
	if err := coll.InsertOne(ctx, service299Data); err != nil {
		return Service299Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service299DB.GetCollection(ctx, "service299_db", "service299_data")
	if err != nil {
		return Service299Data{}, err
	}
	service299Data = Service299Data{
		ID:   id299,
		DataOtherOtherTwo: datatwo299,
	}
	if err := coll.InsertOne(ctx, service299Data); err != nil {
		return Service299Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service300.MethodOtherOther300(ctx, id299, data299, datatwo299); err != nil {
		return Service299Data{}, err
	}

	return service299Data, nil
}
