// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service486Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service486 interface {
	Method486(ctx context.Context, id string, data string, datatwo string) (Service486Data, error)
	MethodOther486(ctx context.Context, id string, data string, datatwo string) (Service486Data, error)
	MethodOtherOther486(ctx context.Context, id string, data string, datatwo string) (Service486Data, error)
}

type Service486Impl struct {
	service486DB backend.NoSQLDatabase
	service487 Service487
}

func NewService486Impl(ctx context.Context, service486DB backend.NoSQLDatabase, service487 Service487) (Service486, error) {
	return &Service486Impl{
		service486DB: service486DB,
		service487: service487,
	}, nil
}

func (s *Service486Impl) Method486(ctx context.Context, id486 string, data486 string, datatwo486 string) (Service486Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service486DB.GetCollection(ctx, "service486_db", "service486_data")
	if err != nil {
		return Service486Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id486},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service486Data{}, err
	}
	var service486Data Service486Data
	exists, err := res.One(ctx, &service486Data)
	if err != nil {
		return Service486Data{}, err
	}
	if exists {
		return service486Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service486DB.GetCollection(ctx, "service486_db", "service486_data")
	if err != nil {
		return Service486Data{}, err
	}
	service486Data = Service486Data{
		ID:   id486,
		Data: data486,
	}
	if err := coll.InsertOne(ctx, service486Data); err != nil {
		return Service486Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service486DB.GetCollection(ctx, "service486_db", "service486_data")
	if err != nil {
		return Service486Data{}, err
	}
	service486Data = Service486Data{
		ID:   id486,
		DataTwo: datatwo486,
	}
	if err := coll.InsertOne(ctx, service486Data); err != nil {
		return Service486Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service487.Method487(ctx, id486, data486, datatwo486); err != nil {
		return Service486Data{}, err
	}

	return service486Data, nil
}

func (s *Service486Impl) MethodOther486(ctx context.Context, id486 string, data486 string, datatwo486 string) (Service486Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service486DB.GetCollection(ctx, "service486_db", "service486_data")
	if err != nil {
		return Service486Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id486},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service486Data{}, err
	}
	var service486Data Service486Data
	exists, err := res.One(ctx, &service486Data)
	if err != nil {
		return Service486Data{}, err
	}
	if exists {
		return service486Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service486DB.GetCollection(ctx, "service486_db", "service486_data")
	if err != nil {
		return Service486Data{}, err
	}
	service486Data = Service486Data{
		ID:   id486,
		DataOther: data486,
	}
	if err := coll.InsertOne(ctx, service486Data); err != nil {
		return Service486Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service486DB.GetCollection(ctx, "service486_db", "service486_data")
	if err != nil {
		return Service486Data{}, err
	}
	service486Data = Service486Data{
		ID:   id486,
		DataOtherTwo: datatwo486,
	}
	if err := coll.InsertOne(ctx, service486Data); err != nil {
		return Service486Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service487.MethodOther487(ctx, id486, data486, datatwo486); err != nil {
		return Service486Data{}, err
	}

	return service486Data, nil
}

func (s *Service486Impl) MethodOtherOther486(ctx context.Context, id486 string, data486 string, datatwo486 string) (Service486Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service486DB.GetCollection(ctx, "service486_db", "service486_data")
	if err != nil {
		return Service486Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id486},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service486Data{}, err
	}
	var service486Data Service486Data
	exists, err := res.One(ctx, &service486Data)
	if err != nil {
		return Service486Data{}, err
	}
	if exists {
		return service486Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service486DB.GetCollection(ctx, "service486_db", "service486_data")
	if err != nil {
		return Service486Data{}, err
	}
	service486Data = Service486Data{
		ID:   id486,
		DataOtherOther: data486,
	}
	if err := coll.InsertOne(ctx, service486Data); err != nil {
		return Service486Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service486DB.GetCollection(ctx, "service486_db", "service486_data")
	if err != nil {
		return Service486Data{}, err
	}
	service486Data = Service486Data{
		ID:   id486,
		DataOtherOtherTwo: datatwo486,
	}
	if err := coll.InsertOne(ctx, service486Data); err != nil {
		return Service486Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service487.MethodOtherOther487(ctx, id486, data486, datatwo486); err != nil {
		return Service486Data{}, err
	}

	return service486Data, nil
}
