// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service284Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service284 interface {
	Method284(ctx context.Context, id string, data string, datatwo string) (Service284Data, error)
	MethodOther284(ctx context.Context, id string, data string, datatwo string) (Service284Data, error)
	MethodOtherOther284(ctx context.Context, id string, data string, datatwo string) (Service284Data, error)
}

type Service284Impl struct {
	service284DB backend.NoSQLDatabase
	service285 Service285
}

func NewService284Impl(ctx context.Context, service284DB backend.NoSQLDatabase, service285 Service285) (Service284, error) {
	return &Service284Impl{
		service284DB: service284DB,
		service285: service285,
	}, nil
}

func (s *Service284Impl) Method284(ctx context.Context, id284 string, data284 string, datatwo284 string) (Service284Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service284DB.GetCollection(ctx, "service284_db", "service284_data")
	if err != nil {
		return Service284Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id284},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service284Data{}, err
	}
	var service284Data Service284Data
	exists, err := res.One(ctx, &service284Data)
	if err != nil {
		return Service284Data{}, err
	}
	if exists {
		return service284Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service284DB.GetCollection(ctx, "service284_db", "service284_data")
	if err != nil {
		return Service284Data{}, err
	}
	service284Data = Service284Data{
		ID:   id284,
		Data: data284,
	}
	if err := coll.InsertOne(ctx, service284Data); err != nil {
		return Service284Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service284DB.GetCollection(ctx, "service284_db", "service284_data")
	if err != nil {
		return Service284Data{}, err
	}
	service284Data = Service284Data{
		ID:   id284,
		DataTwo: datatwo284,
	}
	if err := coll.InsertOne(ctx, service284Data); err != nil {
		return Service284Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service285.Method285(ctx, id284, data284, datatwo284); err != nil {
		return Service284Data{}, err
	}

	return service284Data, nil
}

func (s *Service284Impl) MethodOther284(ctx context.Context, id284 string, data284 string, datatwo284 string) (Service284Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service284DB.GetCollection(ctx, "service284_db", "service284_data")
	if err != nil {
		return Service284Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id284},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service284Data{}, err
	}
	var service284Data Service284Data
	exists, err := res.One(ctx, &service284Data)
	if err != nil {
		return Service284Data{}, err
	}
	if exists {
		return service284Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service284DB.GetCollection(ctx, "service284_db", "service284_data")
	if err != nil {
		return Service284Data{}, err
	}
	service284Data = Service284Data{
		ID:   id284,
		DataOther: data284,
	}
	if err := coll.InsertOne(ctx, service284Data); err != nil {
		return Service284Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service284DB.GetCollection(ctx, "service284_db", "service284_data")
	if err != nil {
		return Service284Data{}, err
	}
	service284Data = Service284Data{
		ID:   id284,
		DataOtherTwo: datatwo284,
	}
	if err := coll.InsertOne(ctx, service284Data); err != nil {
		return Service284Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service285.MethodOther285(ctx, id284, data284, datatwo284); err != nil {
		return Service284Data{}, err
	}

	return service284Data, nil
}

func (s *Service284Impl) MethodOtherOther284(ctx context.Context, id284 string, data284 string, datatwo284 string) (Service284Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service284DB.GetCollection(ctx, "service284_db", "service284_data")
	if err != nil {
		return Service284Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id284},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service284Data{}, err
	}
	var service284Data Service284Data
	exists, err := res.One(ctx, &service284Data)
	if err != nil {
		return Service284Data{}, err
	}
	if exists {
		return service284Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service284DB.GetCollection(ctx, "service284_db", "service284_data")
	if err != nil {
		return Service284Data{}, err
	}
	service284Data = Service284Data{
		ID:   id284,
		DataOtherOther: data284,
	}
	if err := coll.InsertOne(ctx, service284Data); err != nil {
		return Service284Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service284DB.GetCollection(ctx, "service284_db", "service284_data")
	if err != nil {
		return Service284Data{}, err
	}
	service284Data = Service284Data{
		ID:   id284,
		DataOtherOtherTwo: datatwo284,
	}
	if err := coll.InsertOne(ctx, service284Data); err != nil {
		return Service284Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service285.MethodOtherOther285(ctx, id284, data284, datatwo284); err != nil {
		return Service284Data{}, err
	}

	return service284Data, nil
}
