// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service147Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service147 interface {
	Method147(ctx context.Context, id string, data string, datatwo string) (Service147Data, error)
	MethodOther147(ctx context.Context, id string, data string, datatwo string) (Service147Data, error)
	MethodOtherOther147(ctx context.Context, id string, data string, datatwo string) (Service147Data, error)
}

type Service147Impl struct {
	service147DB backend.NoSQLDatabase
	service148 Service148
}

func NewService147Impl(ctx context.Context, service147DB backend.NoSQLDatabase, service148 Service148) (Service147, error) {
	return &Service147Impl{
		service147DB: service147DB,
		service148: service148,
	}, nil
}

func (s *Service147Impl) Method147(ctx context.Context, id147 string, data147 string, datatwo147 string) (Service147Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service147DB.GetCollection(ctx, "service147_db", "service147_data")
	if err != nil {
		return Service147Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id147},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service147Data{}, err
	}
	var service147Data Service147Data
	exists, err := res.One(ctx, &service147Data)
	if err != nil {
		return Service147Data{}, err
	}
	if exists {
		return service147Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service147DB.GetCollection(ctx, "service147_db", "service147_data")
	if err != nil {
		return Service147Data{}, err
	}
	service147Data = Service147Data{
		ID:   id147,
		Data: data147,
	}
	if err := coll.InsertOne(ctx, service147Data); err != nil {
		return Service147Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service147DB.GetCollection(ctx, "service147_db", "service147_data")
	if err != nil {
		return Service147Data{}, err
	}
	service147Data = Service147Data{
		ID:   id147,
		DataTwo: datatwo147,
	}
	if err := coll.InsertOne(ctx, service147Data); err != nil {
		return Service147Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service148.Method148(ctx, id147, data147, datatwo147); err != nil {
		return Service147Data{}, err
	}

	return service147Data, nil
}

func (s *Service147Impl) MethodOther147(ctx context.Context, id147 string, data147 string, datatwo147 string) (Service147Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service147DB.GetCollection(ctx, "service147_db", "service147_data")
	if err != nil {
		return Service147Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id147},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service147Data{}, err
	}
	var service147Data Service147Data
	exists, err := res.One(ctx, &service147Data)
	if err != nil {
		return Service147Data{}, err
	}
	if exists {
		return service147Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service147DB.GetCollection(ctx, "service147_db", "service147_data")
	if err != nil {
		return Service147Data{}, err
	}
	service147Data = Service147Data{
		ID:   id147,
		DataOther: data147,
	}
	if err := coll.InsertOne(ctx, service147Data); err != nil {
		return Service147Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service147DB.GetCollection(ctx, "service147_db", "service147_data")
	if err != nil {
		return Service147Data{}, err
	}
	service147Data = Service147Data{
		ID:   id147,
		DataOtherTwo: datatwo147,
	}
	if err := coll.InsertOne(ctx, service147Data); err != nil {
		return Service147Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service148.MethodOther148(ctx, id147, data147, datatwo147); err != nil {
		return Service147Data{}, err
	}

	return service147Data, nil
}

func (s *Service147Impl) MethodOtherOther147(ctx context.Context, id147 string, data147 string, datatwo147 string) (Service147Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service147DB.GetCollection(ctx, "service147_db", "service147_data")
	if err != nil {
		return Service147Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id147},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service147Data{}, err
	}
	var service147Data Service147Data
	exists, err := res.One(ctx, &service147Data)
	if err != nil {
		return Service147Data{}, err
	}
	if exists {
		return service147Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service147DB.GetCollection(ctx, "service147_db", "service147_data")
	if err != nil {
		return Service147Data{}, err
	}
	service147Data = Service147Data{
		ID:   id147,
		DataOtherOther: data147,
	}
	if err := coll.InsertOne(ctx, service147Data); err != nil {
		return Service147Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service147DB.GetCollection(ctx, "service147_db", "service147_data")
	if err != nil {
		return Service147Data{}, err
	}
	service147Data = Service147Data{
		ID:   id147,
		DataOtherOtherTwo: datatwo147,
	}
	if err := coll.InsertOne(ctx, service147Data); err != nil {
		return Service147Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service148.MethodOtherOther148(ctx, id147, data147, datatwo147); err != nil {
		return Service147Data{}, err
	}

	return service147Data, nil
}
