// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service145Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service145 interface {
	Method145(ctx context.Context, id string, data string, datatwo string) (Service145Data, error)
	MethodOther145(ctx context.Context, id string, data string, datatwo string) (Service145Data, error)
	MethodOtherOther145(ctx context.Context, id string, data string, datatwo string) (Service145Data, error)
}

type Service145Impl struct {
	service145DB backend.NoSQLDatabase
	service146 Service146
}

func NewService145Impl(ctx context.Context, service145DB backend.NoSQLDatabase, service146 Service146) (Service145, error) {
	return &Service145Impl{
		service145DB: service145DB,
		service146: service146,
	}, nil
}

func (s *Service145Impl) Method145(ctx context.Context, id145 string, data145 string, datatwo145 string) (Service145Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service145DB.GetCollection(ctx, "service145_db", "service145_data")
	if err != nil {
		return Service145Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id145},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service145Data{}, err
	}
	var service145Data Service145Data
	exists, err := res.One(ctx, &service145Data)
	if err != nil {
		return Service145Data{}, err
	}
	if exists {
		return service145Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service145DB.GetCollection(ctx, "service145_db", "service145_data")
	if err != nil {
		return Service145Data{}, err
	}
	service145Data = Service145Data{
		ID:   id145,
		Data: data145,
	}
	if err := coll.InsertOne(ctx, service145Data); err != nil {
		return Service145Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service145DB.GetCollection(ctx, "service145_db", "service145_data")
	if err != nil {
		return Service145Data{}, err
	}
	service145Data = Service145Data{
		ID:   id145,
		DataTwo: datatwo145,
	}
	if err := coll.InsertOne(ctx, service145Data); err != nil {
		return Service145Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service146.Method146(ctx, id145, data145, datatwo145); err != nil {
		return Service145Data{}, err
	}

	return service145Data, nil
}

func (s *Service145Impl) MethodOther145(ctx context.Context, id145 string, data145 string, datatwo145 string) (Service145Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service145DB.GetCollection(ctx, "service145_db", "service145_data")
	if err != nil {
		return Service145Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id145},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service145Data{}, err
	}
	var service145Data Service145Data
	exists, err := res.One(ctx, &service145Data)
	if err != nil {
		return Service145Data{}, err
	}
	if exists {
		return service145Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service145DB.GetCollection(ctx, "service145_db", "service145_data")
	if err != nil {
		return Service145Data{}, err
	}
	service145Data = Service145Data{
		ID:   id145,
		DataOther: data145,
	}
	if err := coll.InsertOne(ctx, service145Data); err != nil {
		return Service145Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service145DB.GetCollection(ctx, "service145_db", "service145_data")
	if err != nil {
		return Service145Data{}, err
	}
	service145Data = Service145Data{
		ID:   id145,
		DataOtherTwo: datatwo145,
	}
	if err := coll.InsertOne(ctx, service145Data); err != nil {
		return Service145Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service146.MethodOther146(ctx, id145, data145, datatwo145); err != nil {
		return Service145Data{}, err
	}

	return service145Data, nil
}

func (s *Service145Impl) MethodOtherOther145(ctx context.Context, id145 string, data145 string, datatwo145 string) (Service145Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service145DB.GetCollection(ctx, "service145_db", "service145_data")
	if err != nil {
		return Service145Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id145},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service145Data{}, err
	}
	var service145Data Service145Data
	exists, err := res.One(ctx, &service145Data)
	if err != nil {
		return Service145Data{}, err
	}
	if exists {
		return service145Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service145DB.GetCollection(ctx, "service145_db", "service145_data")
	if err != nil {
		return Service145Data{}, err
	}
	service145Data = Service145Data{
		ID:   id145,
		DataOtherOther: data145,
	}
	if err := coll.InsertOne(ctx, service145Data); err != nil {
		return Service145Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service145DB.GetCollection(ctx, "service145_db", "service145_data")
	if err != nil {
		return Service145Data{}, err
	}
	service145Data = Service145Data{
		ID:   id145,
		DataOtherOtherTwo: datatwo145,
	}
	if err := coll.InsertOne(ctx, service145Data); err != nil {
		return Service145Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service146.MethodOtherOther146(ctx, id145, data145, datatwo145); err != nil {
		return Service145Data{}, err
	}

	return service145Data, nil
}
