// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service498Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service498 interface {
	Method498(ctx context.Context, id string, data string, datatwo string) (Service498Data, error)
	MethodOther498(ctx context.Context, id string, data string, datatwo string) (Service498Data, error)
	MethodOtherOther498(ctx context.Context, id string, data string, datatwo string) (Service498Data, error)
}

type Service498Impl struct {
	service498DB backend.NoSQLDatabase
	service499 Service499
}

func NewService498Impl(ctx context.Context, service498DB backend.NoSQLDatabase, service499 Service499) (Service498, error) {
	return &Service498Impl{
		service498DB: service498DB,
		service499: service499,
	}, nil
}

func (s *Service498Impl) Method498(ctx context.Context, id498 string, data498 string, datatwo498 string) (Service498Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service498DB.GetCollection(ctx, "service498_db", "service498_data")
	if err != nil {
		return Service498Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id498},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service498Data{}, err
	}
	var service498Data Service498Data
	exists, err := res.One(ctx, &service498Data)
	if err != nil {
		return Service498Data{}, err
	}
	if exists {
		return service498Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service498DB.GetCollection(ctx, "service498_db", "service498_data")
	if err != nil {
		return Service498Data{}, err
	}
	service498Data = Service498Data{
		ID:   id498,
		Data: data498,
	}
	if err := coll.InsertOne(ctx, service498Data); err != nil {
		return Service498Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service498DB.GetCollection(ctx, "service498_db", "service498_data")
	if err != nil {
		return Service498Data{}, err
	}
	service498Data = Service498Data{
		ID:   id498,
		DataTwo: datatwo498,
	}
	if err := coll.InsertOne(ctx, service498Data); err != nil {
		return Service498Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service499.Method499(ctx, id498, data498, datatwo498); err != nil {
		return Service498Data{}, err
	}

	return service498Data, nil
}

func (s *Service498Impl) MethodOther498(ctx context.Context, id498 string, data498 string, datatwo498 string) (Service498Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service498DB.GetCollection(ctx, "service498_db", "service498_data")
	if err != nil {
		return Service498Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id498},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service498Data{}, err
	}
	var service498Data Service498Data
	exists, err := res.One(ctx, &service498Data)
	if err != nil {
		return Service498Data{}, err
	}
	if exists {
		return service498Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service498DB.GetCollection(ctx, "service498_db", "service498_data")
	if err != nil {
		return Service498Data{}, err
	}
	service498Data = Service498Data{
		ID:   id498,
		DataOther: data498,
	}
	if err := coll.InsertOne(ctx, service498Data); err != nil {
		return Service498Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service498DB.GetCollection(ctx, "service498_db", "service498_data")
	if err != nil {
		return Service498Data{}, err
	}
	service498Data = Service498Data{
		ID:   id498,
		DataOtherTwo: datatwo498,
	}
	if err := coll.InsertOne(ctx, service498Data); err != nil {
		return Service498Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service499.MethodOther499(ctx, id498, data498, datatwo498); err != nil {
		return Service498Data{}, err
	}

	return service498Data, nil
}

func (s *Service498Impl) MethodOtherOther498(ctx context.Context, id498 string, data498 string, datatwo498 string) (Service498Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service498DB.GetCollection(ctx, "service498_db", "service498_data")
	if err != nil {
		return Service498Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id498},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service498Data{}, err
	}
	var service498Data Service498Data
	exists, err := res.One(ctx, &service498Data)
	if err != nil {
		return Service498Data{}, err
	}
	if exists {
		return service498Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service498DB.GetCollection(ctx, "service498_db", "service498_data")
	if err != nil {
		return Service498Data{}, err
	}
	service498Data = Service498Data{
		ID:   id498,
		DataOtherOther: data498,
	}
	if err := coll.InsertOne(ctx, service498Data); err != nil {
		return Service498Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service498DB.GetCollection(ctx, "service498_db", "service498_data")
	if err != nil {
		return Service498Data{}, err
	}
	service498Data = Service498Data{
		ID:   id498,
		DataOtherOtherTwo: datatwo498,
	}
	if err := coll.InsertOne(ctx, service498Data); err != nil {
		return Service498Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service499.MethodOtherOther499(ctx, id498, data498, datatwo498); err != nil {
		return Service498Data{}, err
	}

	return service498Data, nil
}
