// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service364Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service364 interface {
	Method364(ctx context.Context, id string, data string, datatwo string) (Service364Data, error)
	MethodOther364(ctx context.Context, id string, data string, datatwo string) (Service364Data, error)
	MethodOtherOther364(ctx context.Context, id string, data string, datatwo string) (Service364Data, error)
}

type Service364Impl struct {
	service364DB backend.NoSQLDatabase
	service365 Service365
}

func NewService364Impl(ctx context.Context, service364DB backend.NoSQLDatabase, service365 Service365) (Service364, error) {
	return &Service364Impl{
		service364DB: service364DB,
		service365: service365,
	}, nil
}

func (s *Service364Impl) Method364(ctx context.Context, id364 string, data364 string, datatwo364 string) (Service364Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service364DB.GetCollection(ctx, "service364_db", "service364_data")
	if err != nil {
		return Service364Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id364},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service364Data{}, err
	}
	var service364Data Service364Data
	exists, err := res.One(ctx, &service364Data)
	if err != nil {
		return Service364Data{}, err
	}
	if exists {
		return service364Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service364DB.GetCollection(ctx, "service364_db", "service364_data")
	if err != nil {
		return Service364Data{}, err
	}
	service364Data = Service364Data{
		ID:   id364,
		Data: data364,
	}
	if err := coll.InsertOne(ctx, service364Data); err != nil {
		return Service364Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service364DB.GetCollection(ctx, "service364_db", "service364_data")
	if err != nil {
		return Service364Data{}, err
	}
	service364Data = Service364Data{
		ID:   id364,
		DataTwo: datatwo364,
	}
	if err := coll.InsertOne(ctx, service364Data); err != nil {
		return Service364Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service365.Method365(ctx, id364, data364, datatwo364); err != nil {
		return Service364Data{}, err
	}

	return service364Data, nil
}

func (s *Service364Impl) MethodOther364(ctx context.Context, id364 string, data364 string, datatwo364 string) (Service364Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service364DB.GetCollection(ctx, "service364_db", "service364_data")
	if err != nil {
		return Service364Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id364},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service364Data{}, err
	}
	var service364Data Service364Data
	exists, err := res.One(ctx, &service364Data)
	if err != nil {
		return Service364Data{}, err
	}
	if exists {
		return service364Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service364DB.GetCollection(ctx, "service364_db", "service364_data")
	if err != nil {
		return Service364Data{}, err
	}
	service364Data = Service364Data{
		ID:   id364,
		DataOther: data364,
	}
	if err := coll.InsertOne(ctx, service364Data); err != nil {
		return Service364Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service364DB.GetCollection(ctx, "service364_db", "service364_data")
	if err != nil {
		return Service364Data{}, err
	}
	service364Data = Service364Data{
		ID:   id364,
		DataOtherTwo: datatwo364,
	}
	if err := coll.InsertOne(ctx, service364Data); err != nil {
		return Service364Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service365.MethodOther365(ctx, id364, data364, datatwo364); err != nil {
		return Service364Data{}, err
	}

	return service364Data, nil
}

func (s *Service364Impl) MethodOtherOther364(ctx context.Context, id364 string, data364 string, datatwo364 string) (Service364Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service364DB.GetCollection(ctx, "service364_db", "service364_data")
	if err != nil {
		return Service364Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id364},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service364Data{}, err
	}
	var service364Data Service364Data
	exists, err := res.One(ctx, &service364Data)
	if err != nil {
		return Service364Data{}, err
	}
	if exists {
		return service364Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service364DB.GetCollection(ctx, "service364_db", "service364_data")
	if err != nil {
		return Service364Data{}, err
	}
	service364Data = Service364Data{
		ID:   id364,
		DataOtherOther: data364,
	}
	if err := coll.InsertOne(ctx, service364Data); err != nil {
		return Service364Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service364DB.GetCollection(ctx, "service364_db", "service364_data")
	if err != nil {
		return Service364Data{}, err
	}
	service364Data = Service364Data{
		ID:   id364,
		DataOtherOtherTwo: datatwo364,
	}
	if err := coll.InsertOne(ctx, service364Data); err != nil {
		return Service364Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service365.MethodOtherOther365(ctx, id364, data364, datatwo364); err != nil {
		return Service364Data{}, err
	}

	return service364Data, nil
}
