// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service223Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service223 interface {
	Method223(ctx context.Context, id string, data string, datatwo string) (Service223Data, error)
	MethodOther223(ctx context.Context, id string, data string, datatwo string) (Service223Data, error)
	MethodOtherOther223(ctx context.Context, id string, data string, datatwo string) (Service223Data, error)
}

type Service223Impl struct {
	service223DB backend.NoSQLDatabase
	service224 Service224
}

func NewService223Impl(ctx context.Context, service223DB backend.NoSQLDatabase, service224 Service224) (Service223, error) {
	return &Service223Impl{
		service223DB: service223DB,
		service224: service224,
	}, nil
}

func (s *Service223Impl) Method223(ctx context.Context, id223 string, data223 string, datatwo223 string) (Service223Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service223DB.GetCollection(ctx, "service223_db", "service223_data")
	if err != nil {
		return Service223Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id223},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service223Data{}, err
	}
	var service223Data Service223Data
	exists, err := res.One(ctx, &service223Data)
	if err != nil {
		return Service223Data{}, err
	}
	if exists {
		return service223Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service223DB.GetCollection(ctx, "service223_db", "service223_data")
	if err != nil {
		return Service223Data{}, err
	}
	service223Data = Service223Data{
		ID:   id223,
		Data: data223,
	}
	if err := coll.InsertOne(ctx, service223Data); err != nil {
		return Service223Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service223DB.GetCollection(ctx, "service223_db", "service223_data")
	if err != nil {
		return Service223Data{}, err
	}
	service223Data = Service223Data{
		ID:   id223,
		DataTwo: datatwo223,
	}
	if err := coll.InsertOne(ctx, service223Data); err != nil {
		return Service223Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service224.Method224(ctx, id223, data223, datatwo223); err != nil {
		return Service223Data{}, err
	}

	return service223Data, nil
}

func (s *Service223Impl) MethodOther223(ctx context.Context, id223 string, data223 string, datatwo223 string) (Service223Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service223DB.GetCollection(ctx, "service223_db", "service223_data")
	if err != nil {
		return Service223Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id223},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service223Data{}, err
	}
	var service223Data Service223Data
	exists, err := res.One(ctx, &service223Data)
	if err != nil {
		return Service223Data{}, err
	}
	if exists {
		return service223Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service223DB.GetCollection(ctx, "service223_db", "service223_data")
	if err != nil {
		return Service223Data{}, err
	}
	service223Data = Service223Data{
		ID:   id223,
		DataOther: data223,
	}
	if err := coll.InsertOne(ctx, service223Data); err != nil {
		return Service223Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service223DB.GetCollection(ctx, "service223_db", "service223_data")
	if err != nil {
		return Service223Data{}, err
	}
	service223Data = Service223Data{
		ID:   id223,
		DataOtherTwo: datatwo223,
	}
	if err := coll.InsertOne(ctx, service223Data); err != nil {
		return Service223Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service224.MethodOther224(ctx, id223, data223, datatwo223); err != nil {
		return Service223Data{}, err
	}

	return service223Data, nil
}

func (s *Service223Impl) MethodOtherOther223(ctx context.Context, id223 string, data223 string, datatwo223 string) (Service223Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service223DB.GetCollection(ctx, "service223_db", "service223_data")
	if err != nil {
		return Service223Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id223},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service223Data{}, err
	}
	var service223Data Service223Data
	exists, err := res.One(ctx, &service223Data)
	if err != nil {
		return Service223Data{}, err
	}
	if exists {
		return service223Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service223DB.GetCollection(ctx, "service223_db", "service223_data")
	if err != nil {
		return Service223Data{}, err
	}
	service223Data = Service223Data{
		ID:   id223,
		DataOtherOther: data223,
	}
	if err := coll.InsertOne(ctx, service223Data); err != nil {
		return Service223Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service223DB.GetCollection(ctx, "service223_db", "service223_data")
	if err != nil {
		return Service223Data{}, err
	}
	service223Data = Service223Data{
		ID:   id223,
		DataOtherOtherTwo: datatwo223,
	}
	if err := coll.InsertOne(ctx, service223Data); err != nil {
		return Service223Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service224.MethodOtherOther224(ctx, id223, data223, datatwo223); err != nil {
		return Service223Data{}, err
	}

	return service223Data, nil
}
