// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service376Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service376 interface {
	Method376(ctx context.Context, id string, data string, datatwo string) (Service376Data, error)
	MethodOther376(ctx context.Context, id string, data string, datatwo string) (Service376Data, error)
	MethodOtherOther376(ctx context.Context, id string, data string, datatwo string) (Service376Data, error)
}

type Service376Impl struct {
	service376DB backend.NoSQLDatabase
	service377 Service377
}

func NewService376Impl(ctx context.Context, service376DB backend.NoSQLDatabase, service377 Service377) (Service376, error) {
	return &Service376Impl{
		service376DB: service376DB,
		service377: service377,
	}, nil
}

func (s *Service376Impl) Method376(ctx context.Context, id376 string, data376 string, datatwo376 string) (Service376Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service376DB.GetCollection(ctx, "service376_db", "service376_data")
	if err != nil {
		return Service376Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id376},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service376Data{}, err
	}
	var service376Data Service376Data
	exists, err := res.One(ctx, &service376Data)
	if err != nil {
		return Service376Data{}, err
	}
	if exists {
		return service376Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service376DB.GetCollection(ctx, "service376_db", "service376_data")
	if err != nil {
		return Service376Data{}, err
	}
	service376Data = Service376Data{
		ID:   id376,
		Data: data376,
	}
	if err := coll.InsertOne(ctx, service376Data); err != nil {
		return Service376Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service376DB.GetCollection(ctx, "service376_db", "service376_data")
	if err != nil {
		return Service376Data{}, err
	}
	service376Data = Service376Data{
		ID:   id376,
		DataTwo: datatwo376,
	}
	if err := coll.InsertOne(ctx, service376Data); err != nil {
		return Service376Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service377.Method377(ctx, id376, data376, datatwo376); err != nil {
		return Service376Data{}, err
	}

	return service376Data, nil
}

func (s *Service376Impl) MethodOther376(ctx context.Context, id376 string, data376 string, datatwo376 string) (Service376Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service376DB.GetCollection(ctx, "service376_db", "service376_data")
	if err != nil {
		return Service376Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id376},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service376Data{}, err
	}
	var service376Data Service376Data
	exists, err := res.One(ctx, &service376Data)
	if err != nil {
		return Service376Data{}, err
	}
	if exists {
		return service376Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service376DB.GetCollection(ctx, "service376_db", "service376_data")
	if err != nil {
		return Service376Data{}, err
	}
	service376Data = Service376Data{
		ID:   id376,
		DataOther: data376,
	}
	if err := coll.InsertOne(ctx, service376Data); err != nil {
		return Service376Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service376DB.GetCollection(ctx, "service376_db", "service376_data")
	if err != nil {
		return Service376Data{}, err
	}
	service376Data = Service376Data{
		ID:   id376,
		DataOtherTwo: datatwo376,
	}
	if err := coll.InsertOne(ctx, service376Data); err != nil {
		return Service376Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service377.MethodOther377(ctx, id376, data376, datatwo376); err != nil {
		return Service376Data{}, err
	}

	return service376Data, nil
}

func (s *Service376Impl) MethodOtherOther376(ctx context.Context, id376 string, data376 string, datatwo376 string) (Service376Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service376DB.GetCollection(ctx, "service376_db", "service376_data")
	if err != nil {
		return Service376Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id376},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service376Data{}, err
	}
	var service376Data Service376Data
	exists, err := res.One(ctx, &service376Data)
	if err != nil {
		return Service376Data{}, err
	}
	if exists {
		return service376Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service376DB.GetCollection(ctx, "service376_db", "service376_data")
	if err != nil {
		return Service376Data{}, err
	}
	service376Data = Service376Data{
		ID:   id376,
		DataOtherOther: data376,
	}
	if err := coll.InsertOne(ctx, service376Data); err != nil {
		return Service376Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service376DB.GetCollection(ctx, "service376_db", "service376_data")
	if err != nil {
		return Service376Data{}, err
	}
	service376Data = Service376Data{
		ID:   id376,
		DataOtherOtherTwo: datatwo376,
	}
	if err := coll.InsertOne(ctx, service376Data); err != nil {
		return Service376Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service377.MethodOtherOther377(ctx, id376, data376, datatwo376); err != nil {
		return Service376Data{}, err
	}

	return service376Data, nil
}
