// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service477Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service477 interface {
	Method477(ctx context.Context, id string, data string, datatwo string) (Service477Data, error)
	MethodOther477(ctx context.Context, id string, data string, datatwo string) (Service477Data, error)
	MethodOtherOther477(ctx context.Context, id string, data string, datatwo string) (Service477Data, error)
}

type Service477Impl struct {
	service477DB backend.NoSQLDatabase
	service478 Service478
}

func NewService477Impl(ctx context.Context, service477DB backend.NoSQLDatabase, service478 Service478) (Service477, error) {
	return &Service477Impl{
		service477DB: service477DB,
		service478: service478,
	}, nil
}

func (s *Service477Impl) Method477(ctx context.Context, id477 string, data477 string, datatwo477 string) (Service477Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service477DB.GetCollection(ctx, "service477_db", "service477_data")
	if err != nil {
		return Service477Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id477},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service477Data{}, err
	}
	var service477Data Service477Data
	exists, err := res.One(ctx, &service477Data)
	if err != nil {
		return Service477Data{}, err
	}
	if exists {
		return service477Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service477DB.GetCollection(ctx, "service477_db", "service477_data")
	if err != nil {
		return Service477Data{}, err
	}
	service477Data = Service477Data{
		ID:   id477,
		Data: data477,
	}
	if err := coll.InsertOne(ctx, service477Data); err != nil {
		return Service477Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service477DB.GetCollection(ctx, "service477_db", "service477_data")
	if err != nil {
		return Service477Data{}, err
	}
	service477Data = Service477Data{
		ID:   id477,
		DataTwo: datatwo477,
	}
	if err := coll.InsertOne(ctx, service477Data); err != nil {
		return Service477Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service478.Method478(ctx, id477, data477, datatwo477); err != nil {
		return Service477Data{}, err
	}

	return service477Data, nil
}

func (s *Service477Impl) MethodOther477(ctx context.Context, id477 string, data477 string, datatwo477 string) (Service477Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service477DB.GetCollection(ctx, "service477_db", "service477_data")
	if err != nil {
		return Service477Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id477},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service477Data{}, err
	}
	var service477Data Service477Data
	exists, err := res.One(ctx, &service477Data)
	if err != nil {
		return Service477Data{}, err
	}
	if exists {
		return service477Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service477DB.GetCollection(ctx, "service477_db", "service477_data")
	if err != nil {
		return Service477Data{}, err
	}
	service477Data = Service477Data{
		ID:   id477,
		DataOther: data477,
	}
	if err := coll.InsertOne(ctx, service477Data); err != nil {
		return Service477Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service477DB.GetCollection(ctx, "service477_db", "service477_data")
	if err != nil {
		return Service477Data{}, err
	}
	service477Data = Service477Data{
		ID:   id477,
		DataOtherTwo: datatwo477,
	}
	if err := coll.InsertOne(ctx, service477Data); err != nil {
		return Service477Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service478.MethodOther478(ctx, id477, data477, datatwo477); err != nil {
		return Service477Data{}, err
	}

	return service477Data, nil
}

func (s *Service477Impl) MethodOtherOther477(ctx context.Context, id477 string, data477 string, datatwo477 string) (Service477Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service477DB.GetCollection(ctx, "service477_db", "service477_data")
	if err != nil {
		return Service477Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id477},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service477Data{}, err
	}
	var service477Data Service477Data
	exists, err := res.One(ctx, &service477Data)
	if err != nil {
		return Service477Data{}, err
	}
	if exists {
		return service477Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service477DB.GetCollection(ctx, "service477_db", "service477_data")
	if err != nil {
		return Service477Data{}, err
	}
	service477Data = Service477Data{
		ID:   id477,
		DataOtherOther: data477,
	}
	if err := coll.InsertOne(ctx, service477Data); err != nil {
		return Service477Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service477DB.GetCollection(ctx, "service477_db", "service477_data")
	if err != nil {
		return Service477Data{}, err
	}
	service477Data = Service477Data{
		ID:   id477,
		DataOtherOtherTwo: datatwo477,
	}
	if err := coll.InsertOne(ctx, service477Data); err != nil {
		return Service477Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service478.MethodOtherOther478(ctx, id477, data477, datatwo477); err != nil {
		return Service477Data{}, err
	}

	return service477Data, nil
}
