// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service162Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service162 interface {
	Method162(ctx context.Context, id string, data string, datatwo string) (Service162Data, error)
	MethodOther162(ctx context.Context, id string, data string, datatwo string) (Service162Data, error)
	MethodOtherOther162(ctx context.Context, id string, data string, datatwo string) (Service162Data, error)
}

type Service162Impl struct {
	service162DB backend.NoSQLDatabase
	service163 Service163
}

func NewService162Impl(ctx context.Context, service162DB backend.NoSQLDatabase, service163 Service163) (Service162, error) {
	return &Service162Impl{
		service162DB: service162DB,
		service163: service163,
	}, nil
}

func (s *Service162Impl) Method162(ctx context.Context, id162 string, data162 string, datatwo162 string) (Service162Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service162DB.GetCollection(ctx, "service162_db", "service162_data")
	if err != nil {
		return Service162Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id162},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service162Data{}, err
	}
	var service162Data Service162Data
	exists, err := res.One(ctx, &service162Data)
	if err != nil {
		return Service162Data{}, err
	}
	if exists {
		return service162Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service162DB.GetCollection(ctx, "service162_db", "service162_data")
	if err != nil {
		return Service162Data{}, err
	}
	service162Data = Service162Data{
		ID:   id162,
		Data: data162,
	}
	if err := coll.InsertOne(ctx, service162Data); err != nil {
		return Service162Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service162DB.GetCollection(ctx, "service162_db", "service162_data")
	if err != nil {
		return Service162Data{}, err
	}
	service162Data = Service162Data{
		ID:   id162,
		DataTwo: datatwo162,
	}
	if err := coll.InsertOne(ctx, service162Data); err != nil {
		return Service162Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service163.Method163(ctx, id162, data162, datatwo162); err != nil {
		return Service162Data{}, err
	}

	return service162Data, nil
}

func (s *Service162Impl) MethodOther162(ctx context.Context, id162 string, data162 string, datatwo162 string) (Service162Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service162DB.GetCollection(ctx, "service162_db", "service162_data")
	if err != nil {
		return Service162Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id162},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service162Data{}, err
	}
	var service162Data Service162Data
	exists, err := res.One(ctx, &service162Data)
	if err != nil {
		return Service162Data{}, err
	}
	if exists {
		return service162Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service162DB.GetCollection(ctx, "service162_db", "service162_data")
	if err != nil {
		return Service162Data{}, err
	}
	service162Data = Service162Data{
		ID:   id162,
		DataOther: data162,
	}
	if err := coll.InsertOne(ctx, service162Data); err != nil {
		return Service162Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service162DB.GetCollection(ctx, "service162_db", "service162_data")
	if err != nil {
		return Service162Data{}, err
	}
	service162Data = Service162Data{
		ID:   id162,
		DataOtherTwo: datatwo162,
	}
	if err := coll.InsertOne(ctx, service162Data); err != nil {
		return Service162Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service163.MethodOther163(ctx, id162, data162, datatwo162); err != nil {
		return Service162Data{}, err
	}

	return service162Data, nil
}

func (s *Service162Impl) MethodOtherOther162(ctx context.Context, id162 string, data162 string, datatwo162 string) (Service162Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service162DB.GetCollection(ctx, "service162_db", "service162_data")
	if err != nil {
		return Service162Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id162},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service162Data{}, err
	}
	var service162Data Service162Data
	exists, err := res.One(ctx, &service162Data)
	if err != nil {
		return Service162Data{}, err
	}
	if exists {
		return service162Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service162DB.GetCollection(ctx, "service162_db", "service162_data")
	if err != nil {
		return Service162Data{}, err
	}
	service162Data = Service162Data{
		ID:   id162,
		DataOtherOther: data162,
	}
	if err := coll.InsertOne(ctx, service162Data); err != nil {
		return Service162Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service162DB.GetCollection(ctx, "service162_db", "service162_data")
	if err != nil {
		return Service162Data{}, err
	}
	service162Data = Service162Data{
		ID:   id162,
		DataOtherOtherTwo: datatwo162,
	}
	if err := coll.InsertOne(ctx, service162Data); err != nil {
		return Service162Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service163.MethodOtherOther163(ctx, id162, data162, datatwo162); err != nil {
		return Service162Data{}, err
	}

	return service162Data, nil
}
