// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service128Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service128 interface {
	Method128(ctx context.Context, id string, data string, datatwo string) (Service128Data, error)
	MethodOther128(ctx context.Context, id string, data string, datatwo string) (Service128Data, error)
	MethodOtherOther128(ctx context.Context, id string, data string, datatwo string) (Service128Data, error)
}

type Service128Impl struct {
	service128DB backend.NoSQLDatabase
	service129 Service129
}

func NewService128Impl(ctx context.Context, service128DB backend.NoSQLDatabase, service129 Service129) (Service128, error) {
	return &Service128Impl{
		service128DB: service128DB,
		service129: service129,
	}, nil
}

func (s *Service128Impl) Method128(ctx context.Context, id128 string, data128 string, datatwo128 string) (Service128Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service128DB.GetCollection(ctx, "service128_db", "service128_data")
	if err != nil {
		return Service128Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id128},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service128Data{}, err
	}
	var service128Data Service128Data
	exists, err := res.One(ctx, &service128Data)
	if err != nil {
		return Service128Data{}, err
	}
	if exists {
		return service128Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service128DB.GetCollection(ctx, "service128_db", "service128_data")
	if err != nil {
		return Service128Data{}, err
	}
	service128Data = Service128Data{
		ID:   id128,
		Data: data128,
	}
	if err := coll.InsertOne(ctx, service128Data); err != nil {
		return Service128Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service128DB.GetCollection(ctx, "service128_db", "service128_data")
	if err != nil {
		return Service128Data{}, err
	}
	service128Data = Service128Data{
		ID:   id128,
		DataTwo: datatwo128,
	}
	if err := coll.InsertOne(ctx, service128Data); err != nil {
		return Service128Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service129.Method129(ctx, id128, data128, datatwo128); err != nil {
		return Service128Data{}, err
	}

	return service128Data, nil
}

func (s *Service128Impl) MethodOther128(ctx context.Context, id128 string, data128 string, datatwo128 string) (Service128Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service128DB.GetCollection(ctx, "service128_db", "service128_data")
	if err != nil {
		return Service128Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id128},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service128Data{}, err
	}
	var service128Data Service128Data
	exists, err := res.One(ctx, &service128Data)
	if err != nil {
		return Service128Data{}, err
	}
	if exists {
		return service128Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service128DB.GetCollection(ctx, "service128_db", "service128_data")
	if err != nil {
		return Service128Data{}, err
	}
	service128Data = Service128Data{
		ID:   id128,
		DataOther: data128,
	}
	if err := coll.InsertOne(ctx, service128Data); err != nil {
		return Service128Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service128DB.GetCollection(ctx, "service128_db", "service128_data")
	if err != nil {
		return Service128Data{}, err
	}
	service128Data = Service128Data{
		ID:   id128,
		DataOtherTwo: datatwo128,
	}
	if err := coll.InsertOne(ctx, service128Data); err != nil {
		return Service128Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service129.MethodOther129(ctx, id128, data128, datatwo128); err != nil {
		return Service128Data{}, err
	}

	return service128Data, nil
}

func (s *Service128Impl) MethodOtherOther128(ctx context.Context, id128 string, data128 string, datatwo128 string) (Service128Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service128DB.GetCollection(ctx, "service128_db", "service128_data")
	if err != nil {
		return Service128Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id128},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service128Data{}, err
	}
	var service128Data Service128Data
	exists, err := res.One(ctx, &service128Data)
	if err != nil {
		return Service128Data{}, err
	}
	if exists {
		return service128Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service128DB.GetCollection(ctx, "service128_db", "service128_data")
	if err != nil {
		return Service128Data{}, err
	}
	service128Data = Service128Data{
		ID:   id128,
		DataOtherOther: data128,
	}
	if err := coll.InsertOne(ctx, service128Data); err != nil {
		return Service128Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service128DB.GetCollection(ctx, "service128_db", "service128_data")
	if err != nil {
		return Service128Data{}, err
	}
	service128Data = Service128Data{
		ID:   id128,
		DataOtherOtherTwo: datatwo128,
	}
	if err := coll.InsertOne(ctx, service128Data); err != nil {
		return Service128Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service129.MethodOtherOther129(ctx, id128, data128, datatwo128); err != nil {
		return Service128Data{}, err
	}

	return service128Data, nil
}
