// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service219Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service219 interface {
	Method219(ctx context.Context, id string, data string, datatwo string) (Service219Data, error)
	MethodOther219(ctx context.Context, id string, data string, datatwo string) (Service219Data, error)
	MethodOtherOther219(ctx context.Context, id string, data string, datatwo string) (Service219Data, error)
}

type Service219Impl struct {
	service219DB backend.NoSQLDatabase
	service220 Service220
}

func NewService219Impl(ctx context.Context, service219DB backend.NoSQLDatabase, service220 Service220) (Service219, error) {
	return &Service219Impl{
		service219DB: service219DB,
		service220: service220,
	}, nil
}

func (s *Service219Impl) Method219(ctx context.Context, id219 string, data219 string, datatwo219 string) (Service219Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service219DB.GetCollection(ctx, "service219_db", "service219_data")
	if err != nil {
		return Service219Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id219},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service219Data{}, err
	}
	var service219Data Service219Data
	exists, err := res.One(ctx, &service219Data)
	if err != nil {
		return Service219Data{}, err
	}
	if exists {
		return service219Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service219DB.GetCollection(ctx, "service219_db", "service219_data")
	if err != nil {
		return Service219Data{}, err
	}
	service219Data = Service219Data{
		ID:   id219,
		Data: data219,
	}
	if err := coll.InsertOne(ctx, service219Data); err != nil {
		return Service219Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service219DB.GetCollection(ctx, "service219_db", "service219_data")
	if err != nil {
		return Service219Data{}, err
	}
	service219Data = Service219Data{
		ID:   id219,
		DataTwo: datatwo219,
	}
	if err := coll.InsertOne(ctx, service219Data); err != nil {
		return Service219Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service220.Method220(ctx, id219, data219, datatwo219); err != nil {
		return Service219Data{}, err
	}

	return service219Data, nil
}

func (s *Service219Impl) MethodOther219(ctx context.Context, id219 string, data219 string, datatwo219 string) (Service219Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service219DB.GetCollection(ctx, "service219_db", "service219_data")
	if err != nil {
		return Service219Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id219},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service219Data{}, err
	}
	var service219Data Service219Data
	exists, err := res.One(ctx, &service219Data)
	if err != nil {
		return Service219Data{}, err
	}
	if exists {
		return service219Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service219DB.GetCollection(ctx, "service219_db", "service219_data")
	if err != nil {
		return Service219Data{}, err
	}
	service219Data = Service219Data{
		ID:   id219,
		DataOther: data219,
	}
	if err := coll.InsertOne(ctx, service219Data); err != nil {
		return Service219Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service219DB.GetCollection(ctx, "service219_db", "service219_data")
	if err != nil {
		return Service219Data{}, err
	}
	service219Data = Service219Data{
		ID:   id219,
		DataOtherTwo: datatwo219,
	}
	if err := coll.InsertOne(ctx, service219Data); err != nil {
		return Service219Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service220.MethodOther220(ctx, id219, data219, datatwo219); err != nil {
		return Service219Data{}, err
	}

	return service219Data, nil
}

func (s *Service219Impl) MethodOtherOther219(ctx context.Context, id219 string, data219 string, datatwo219 string) (Service219Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service219DB.GetCollection(ctx, "service219_db", "service219_data")
	if err != nil {
		return Service219Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id219},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service219Data{}, err
	}
	var service219Data Service219Data
	exists, err := res.One(ctx, &service219Data)
	if err != nil {
		return Service219Data{}, err
	}
	if exists {
		return service219Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service219DB.GetCollection(ctx, "service219_db", "service219_data")
	if err != nil {
		return Service219Data{}, err
	}
	service219Data = Service219Data{
		ID:   id219,
		DataOtherOther: data219,
	}
	if err := coll.InsertOne(ctx, service219Data); err != nil {
		return Service219Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service219DB.GetCollection(ctx, "service219_db", "service219_data")
	if err != nil {
		return Service219Data{}, err
	}
	service219Data = Service219Data{
		ID:   id219,
		DataOtherOtherTwo: datatwo219,
	}
	if err := coll.InsertOne(ctx, service219Data); err != nil {
		return Service219Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service220.MethodOtherOther220(ctx, id219, data219, datatwo219); err != nil {
		return Service219Data{}, err
	}

	return service219Data, nil
}
