// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service42Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service42 interface {
	Method42(ctx context.Context, id string, data string, datatwo string) (Service42Data, error)
	MethodOther42(ctx context.Context, id string, data string, datatwo string) (Service42Data, error)
	MethodOtherOther42(ctx context.Context, id string, data string, datatwo string) (Service42Data, error)
}

type Service42Impl struct {
	service42DB backend.NoSQLDatabase
	service43 Service43
}

func NewService42Impl(ctx context.Context, service42DB backend.NoSQLDatabase, service43 Service43) (Service42, error) {
	return &Service42Impl{
		service42DB: service42DB,
		service43: service43,
	}, nil
}

func (s *Service42Impl) Method42(ctx context.Context, id42 string, data42 string, datatwo42 string) (Service42Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service42DB.GetCollection(ctx, "service42_db", "service42_data")
	if err != nil {
		return Service42Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id42},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service42Data{}, err
	}
	var service42Data Service42Data
	exists, err := res.One(ctx, &service42Data)
	if err != nil {
		return Service42Data{}, err
	}
	if exists {
		return service42Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service42DB.GetCollection(ctx, "service42_db", "service42_data")
	if err != nil {
		return Service42Data{}, err
	}
	service42Data = Service42Data{
		ID:   id42,
		Data: data42,
	}
	if err := coll.InsertOne(ctx, service42Data); err != nil {
		return Service42Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service42DB.GetCollection(ctx, "service42_db", "service42_data")
	if err != nil {
		return Service42Data{}, err
	}
	service42Data = Service42Data{
		ID:   id42,
		DataTwo: datatwo42,
	}
	if err := coll.InsertOne(ctx, service42Data); err != nil {
		return Service42Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service43.Method43(ctx, id42, data42, datatwo42); err != nil {
		return Service42Data{}, err
	}

	return service42Data, nil
}

func (s *Service42Impl) MethodOther42(ctx context.Context, id42 string, data42 string, datatwo42 string) (Service42Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service42DB.GetCollection(ctx, "service42_db", "service42_data")
	if err != nil {
		return Service42Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id42},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service42Data{}, err
	}
	var service42Data Service42Data
	exists, err := res.One(ctx, &service42Data)
	if err != nil {
		return Service42Data{}, err
	}
	if exists {
		return service42Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service42DB.GetCollection(ctx, "service42_db", "service42_data")
	if err != nil {
		return Service42Data{}, err
	}
	service42Data = Service42Data{
		ID:   id42,
		DataOther: data42,
	}
	if err := coll.InsertOne(ctx, service42Data); err != nil {
		return Service42Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service42DB.GetCollection(ctx, "service42_db", "service42_data")
	if err != nil {
		return Service42Data{}, err
	}
	service42Data = Service42Data{
		ID:   id42,
		DataOtherTwo: datatwo42,
	}
	if err := coll.InsertOne(ctx, service42Data); err != nil {
		return Service42Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service43.MethodOther43(ctx, id42, data42, datatwo42); err != nil {
		return Service42Data{}, err
	}

	return service42Data, nil
}

func (s *Service42Impl) MethodOtherOther42(ctx context.Context, id42 string, data42 string, datatwo42 string) (Service42Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service42DB.GetCollection(ctx, "service42_db", "service42_data")
	if err != nil {
		return Service42Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id42},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service42Data{}, err
	}
	var service42Data Service42Data
	exists, err := res.One(ctx, &service42Data)
	if err != nil {
		return Service42Data{}, err
	}
	if exists {
		return service42Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service42DB.GetCollection(ctx, "service42_db", "service42_data")
	if err != nil {
		return Service42Data{}, err
	}
	service42Data = Service42Data{
		ID:   id42,
		DataOtherOther: data42,
	}
	if err := coll.InsertOne(ctx, service42Data); err != nil {
		return Service42Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service42DB.GetCollection(ctx, "service42_db", "service42_data")
	if err != nil {
		return Service42Data{}, err
	}
	service42Data = Service42Data{
		ID:   id42,
		DataOtherOtherTwo: datatwo42,
	}
	if err := coll.InsertOne(ctx, service42Data); err != nil {
		return Service42Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service43.MethodOtherOther43(ctx, id42, data42, datatwo42); err != nil {
		return Service42Data{}, err
	}

	return service42Data, nil
}
