// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service461Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service461 interface {
	Method461(ctx context.Context, id string, data string, datatwo string) (Service461Data, error)
	MethodOther461(ctx context.Context, id string, data string, datatwo string) (Service461Data, error)
	MethodOtherOther461(ctx context.Context, id string, data string, datatwo string) (Service461Data, error)
}

type Service461Impl struct {
	service461DB backend.NoSQLDatabase
	service462 Service462
}

func NewService461Impl(ctx context.Context, service461DB backend.NoSQLDatabase, service462 Service462) (Service461, error) {
	return &Service461Impl{
		service461DB: service461DB,
		service462: service462,
	}, nil
}

func (s *Service461Impl) Method461(ctx context.Context, id461 string, data461 string, datatwo461 string) (Service461Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service461DB.GetCollection(ctx, "service461_db", "service461_data")
	if err != nil {
		return Service461Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id461},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service461Data{}, err
	}
	var service461Data Service461Data
	exists, err := res.One(ctx, &service461Data)
	if err != nil {
		return Service461Data{}, err
	}
	if exists {
		return service461Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service461DB.GetCollection(ctx, "service461_db", "service461_data")
	if err != nil {
		return Service461Data{}, err
	}
	service461Data = Service461Data{
		ID:   id461,
		Data: data461,
	}
	if err := coll.InsertOne(ctx, service461Data); err != nil {
		return Service461Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service461DB.GetCollection(ctx, "service461_db", "service461_data")
	if err != nil {
		return Service461Data{}, err
	}
	service461Data = Service461Data{
		ID:   id461,
		DataTwo: datatwo461,
	}
	if err := coll.InsertOne(ctx, service461Data); err != nil {
		return Service461Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service462.Method462(ctx, id461, data461, datatwo461); err != nil {
		return Service461Data{}, err
	}

	return service461Data, nil
}

func (s *Service461Impl) MethodOther461(ctx context.Context, id461 string, data461 string, datatwo461 string) (Service461Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service461DB.GetCollection(ctx, "service461_db", "service461_data")
	if err != nil {
		return Service461Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id461},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service461Data{}, err
	}
	var service461Data Service461Data
	exists, err := res.One(ctx, &service461Data)
	if err != nil {
		return Service461Data{}, err
	}
	if exists {
		return service461Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service461DB.GetCollection(ctx, "service461_db", "service461_data")
	if err != nil {
		return Service461Data{}, err
	}
	service461Data = Service461Data{
		ID:   id461,
		DataOther: data461,
	}
	if err := coll.InsertOne(ctx, service461Data); err != nil {
		return Service461Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service461DB.GetCollection(ctx, "service461_db", "service461_data")
	if err != nil {
		return Service461Data{}, err
	}
	service461Data = Service461Data{
		ID:   id461,
		DataOtherTwo: datatwo461,
	}
	if err := coll.InsertOne(ctx, service461Data); err != nil {
		return Service461Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service462.MethodOther462(ctx, id461, data461, datatwo461); err != nil {
		return Service461Data{}, err
	}

	return service461Data, nil
}

func (s *Service461Impl) MethodOtherOther461(ctx context.Context, id461 string, data461 string, datatwo461 string) (Service461Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service461DB.GetCollection(ctx, "service461_db", "service461_data")
	if err != nil {
		return Service461Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id461},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service461Data{}, err
	}
	var service461Data Service461Data
	exists, err := res.One(ctx, &service461Data)
	if err != nil {
		return Service461Data{}, err
	}
	if exists {
		return service461Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service461DB.GetCollection(ctx, "service461_db", "service461_data")
	if err != nil {
		return Service461Data{}, err
	}
	service461Data = Service461Data{
		ID:   id461,
		DataOtherOther: data461,
	}
	if err := coll.InsertOne(ctx, service461Data); err != nil {
		return Service461Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service461DB.GetCollection(ctx, "service461_db", "service461_data")
	if err != nil {
		return Service461Data{}, err
	}
	service461Data = Service461Data{
		ID:   id461,
		DataOtherOtherTwo: datatwo461,
	}
	if err := coll.InsertOne(ctx, service461Data); err != nil {
		return Service461Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service462.MethodOtherOther462(ctx, id461, data461, datatwo461); err != nil {
		return Service461Data{}, err
	}

	return service461Data, nil
}
