// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service383Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service383 interface {
	Method383(ctx context.Context, id string, data string, datatwo string) (Service383Data, error)
	MethodOther383(ctx context.Context, id string, data string, datatwo string) (Service383Data, error)
	MethodOtherOther383(ctx context.Context, id string, data string, datatwo string) (Service383Data, error)
}

type Service383Impl struct {
	service383DB backend.NoSQLDatabase
	service384 Service384
}

func NewService383Impl(ctx context.Context, service383DB backend.NoSQLDatabase, service384 Service384) (Service383, error) {
	return &Service383Impl{
		service383DB: service383DB,
		service384: service384,
	}, nil
}

func (s *Service383Impl) Method383(ctx context.Context, id383 string, data383 string, datatwo383 string) (Service383Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service383DB.GetCollection(ctx, "service383_db", "service383_data")
	if err != nil {
		return Service383Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id383},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service383Data{}, err
	}
	var service383Data Service383Data
	exists, err := res.One(ctx, &service383Data)
	if err != nil {
		return Service383Data{}, err
	}
	if exists {
		return service383Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service383DB.GetCollection(ctx, "service383_db", "service383_data")
	if err != nil {
		return Service383Data{}, err
	}
	service383Data = Service383Data{
		ID:   id383,
		Data: data383,
	}
	if err := coll.InsertOne(ctx, service383Data); err != nil {
		return Service383Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service383DB.GetCollection(ctx, "service383_db", "service383_data")
	if err != nil {
		return Service383Data{}, err
	}
	service383Data = Service383Data{
		ID:   id383,
		DataTwo: datatwo383,
	}
	if err := coll.InsertOne(ctx, service383Data); err != nil {
		return Service383Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service384.Method384(ctx, id383, data383, datatwo383); err != nil {
		return Service383Data{}, err
	}

	return service383Data, nil
}

func (s *Service383Impl) MethodOther383(ctx context.Context, id383 string, data383 string, datatwo383 string) (Service383Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service383DB.GetCollection(ctx, "service383_db", "service383_data")
	if err != nil {
		return Service383Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id383},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service383Data{}, err
	}
	var service383Data Service383Data
	exists, err := res.One(ctx, &service383Data)
	if err != nil {
		return Service383Data{}, err
	}
	if exists {
		return service383Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service383DB.GetCollection(ctx, "service383_db", "service383_data")
	if err != nil {
		return Service383Data{}, err
	}
	service383Data = Service383Data{
		ID:   id383,
		DataOther: data383,
	}
	if err := coll.InsertOne(ctx, service383Data); err != nil {
		return Service383Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service383DB.GetCollection(ctx, "service383_db", "service383_data")
	if err != nil {
		return Service383Data{}, err
	}
	service383Data = Service383Data{
		ID:   id383,
		DataOtherTwo: datatwo383,
	}
	if err := coll.InsertOne(ctx, service383Data); err != nil {
		return Service383Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service384.MethodOther384(ctx, id383, data383, datatwo383); err != nil {
		return Service383Data{}, err
	}

	return service383Data, nil
}

func (s *Service383Impl) MethodOtherOther383(ctx context.Context, id383 string, data383 string, datatwo383 string) (Service383Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service383DB.GetCollection(ctx, "service383_db", "service383_data")
	if err != nil {
		return Service383Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id383},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service383Data{}, err
	}
	var service383Data Service383Data
	exists, err := res.One(ctx, &service383Data)
	if err != nil {
		return Service383Data{}, err
	}
	if exists {
		return service383Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service383DB.GetCollection(ctx, "service383_db", "service383_data")
	if err != nil {
		return Service383Data{}, err
	}
	service383Data = Service383Data{
		ID:   id383,
		DataOtherOther: data383,
	}
	if err := coll.InsertOne(ctx, service383Data); err != nil {
		return Service383Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service383DB.GetCollection(ctx, "service383_db", "service383_data")
	if err != nil {
		return Service383Data{}, err
	}
	service383Data = Service383Data{
		ID:   id383,
		DataOtherOtherTwo: datatwo383,
	}
	if err := coll.InsertOne(ctx, service383Data); err != nil {
		return Service383Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service384.MethodOtherOther384(ctx, id383, data383, datatwo383); err != nil {
		return Service383Data{}, err
	}

	return service383Data, nil
}
