// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service125Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service125 interface {
	Method125(ctx context.Context, id string, data string, datatwo string) (Service125Data, error)
	MethodOther125(ctx context.Context, id string, data string, datatwo string) (Service125Data, error)
	MethodOtherOther125(ctx context.Context, id string, data string, datatwo string) (Service125Data, error)
}

type Service125Impl struct {
	service125DB backend.NoSQLDatabase
	service126 Service126
}

func NewService125Impl(ctx context.Context, service125DB backend.NoSQLDatabase, service126 Service126) (Service125, error) {
	return &Service125Impl{
		service125DB: service125DB,
		service126: service126,
	}, nil
}

func (s *Service125Impl) Method125(ctx context.Context, id125 string, data125 string, datatwo125 string) (Service125Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service125DB.GetCollection(ctx, "service125_db", "service125_data")
	if err != nil {
		return Service125Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id125},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service125Data{}, err
	}
	var service125Data Service125Data
	exists, err := res.One(ctx, &service125Data)
	if err != nil {
		return Service125Data{}, err
	}
	if exists {
		return service125Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service125DB.GetCollection(ctx, "service125_db", "service125_data")
	if err != nil {
		return Service125Data{}, err
	}
	service125Data = Service125Data{
		ID:   id125,
		Data: data125,
	}
	if err := coll.InsertOne(ctx, service125Data); err != nil {
		return Service125Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service125DB.GetCollection(ctx, "service125_db", "service125_data")
	if err != nil {
		return Service125Data{}, err
	}
	service125Data = Service125Data{
		ID:   id125,
		DataTwo: datatwo125,
	}
	if err := coll.InsertOne(ctx, service125Data); err != nil {
		return Service125Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service126.Method126(ctx, id125, data125, datatwo125); err != nil {
		return Service125Data{}, err
	}

	return service125Data, nil
}

func (s *Service125Impl) MethodOther125(ctx context.Context, id125 string, data125 string, datatwo125 string) (Service125Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service125DB.GetCollection(ctx, "service125_db", "service125_data")
	if err != nil {
		return Service125Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id125},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service125Data{}, err
	}
	var service125Data Service125Data
	exists, err := res.One(ctx, &service125Data)
	if err != nil {
		return Service125Data{}, err
	}
	if exists {
		return service125Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service125DB.GetCollection(ctx, "service125_db", "service125_data")
	if err != nil {
		return Service125Data{}, err
	}
	service125Data = Service125Data{
		ID:   id125,
		DataOther: data125,
	}
	if err := coll.InsertOne(ctx, service125Data); err != nil {
		return Service125Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service125DB.GetCollection(ctx, "service125_db", "service125_data")
	if err != nil {
		return Service125Data{}, err
	}
	service125Data = Service125Data{
		ID:   id125,
		DataOtherTwo: datatwo125,
	}
	if err := coll.InsertOne(ctx, service125Data); err != nil {
		return Service125Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service126.MethodOther126(ctx, id125, data125, datatwo125); err != nil {
		return Service125Data{}, err
	}

	return service125Data, nil
}

func (s *Service125Impl) MethodOtherOther125(ctx context.Context, id125 string, data125 string, datatwo125 string) (Service125Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service125DB.GetCollection(ctx, "service125_db", "service125_data")
	if err != nil {
		return Service125Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id125},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service125Data{}, err
	}
	var service125Data Service125Data
	exists, err := res.One(ctx, &service125Data)
	if err != nil {
		return Service125Data{}, err
	}
	if exists {
		return service125Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service125DB.GetCollection(ctx, "service125_db", "service125_data")
	if err != nil {
		return Service125Data{}, err
	}
	service125Data = Service125Data{
		ID:   id125,
		DataOtherOther: data125,
	}
	if err := coll.InsertOne(ctx, service125Data); err != nil {
		return Service125Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service125DB.GetCollection(ctx, "service125_db", "service125_data")
	if err != nil {
		return Service125Data{}, err
	}
	service125Data = Service125Data{
		ID:   id125,
		DataOtherOtherTwo: datatwo125,
	}
	if err := coll.InsertOne(ctx, service125Data); err != nil {
		return Service125Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service126.MethodOtherOther126(ctx, id125, data125, datatwo125); err != nil {
		return Service125Data{}, err
	}

	return service125Data, nil
}
