// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service59Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service59 interface {
	Method59(ctx context.Context, id string, data string, datatwo string) (Service59Data, error)
	MethodOther59(ctx context.Context, id string, data string, datatwo string) (Service59Data, error)
	MethodOtherOther59(ctx context.Context, id string, data string, datatwo string) (Service59Data, error)
}

type Service59Impl struct {
	service59DB backend.NoSQLDatabase
	service60 Service60
}

func NewService59Impl(ctx context.Context, service59DB backend.NoSQLDatabase, service60 Service60) (Service59, error) {
	return &Service59Impl{
		service59DB: service59DB,
		service60: service60,
	}, nil
}

func (s *Service59Impl) Method59(ctx context.Context, id59 string, data59 string, datatwo59 string) (Service59Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service59DB.GetCollection(ctx, "service59_db", "service59_data")
	if err != nil {
		return Service59Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id59},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service59Data{}, err
	}
	var service59Data Service59Data
	exists, err := res.One(ctx, &service59Data)
	if err != nil {
		return Service59Data{}, err
	}
	if exists {
		return service59Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service59DB.GetCollection(ctx, "service59_db", "service59_data")
	if err != nil {
		return Service59Data{}, err
	}
	service59Data = Service59Data{
		ID:   id59,
		Data: data59,
	}
	if err := coll.InsertOne(ctx, service59Data); err != nil {
		return Service59Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service59DB.GetCollection(ctx, "service59_db", "service59_data")
	if err != nil {
		return Service59Data{}, err
	}
	service59Data = Service59Data{
		ID:   id59,
		DataTwo: datatwo59,
	}
	if err := coll.InsertOne(ctx, service59Data); err != nil {
		return Service59Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service60.Method60(ctx, id59, data59, datatwo59); err != nil {
		return Service59Data{}, err
	}

	return service59Data, nil
}

func (s *Service59Impl) MethodOther59(ctx context.Context, id59 string, data59 string, datatwo59 string) (Service59Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service59DB.GetCollection(ctx, "service59_db", "service59_data")
	if err != nil {
		return Service59Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id59},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service59Data{}, err
	}
	var service59Data Service59Data
	exists, err := res.One(ctx, &service59Data)
	if err != nil {
		return Service59Data{}, err
	}
	if exists {
		return service59Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service59DB.GetCollection(ctx, "service59_db", "service59_data")
	if err != nil {
		return Service59Data{}, err
	}
	service59Data = Service59Data{
		ID:   id59,
		DataOther: data59,
	}
	if err := coll.InsertOne(ctx, service59Data); err != nil {
		return Service59Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service59DB.GetCollection(ctx, "service59_db", "service59_data")
	if err != nil {
		return Service59Data{}, err
	}
	service59Data = Service59Data{
		ID:   id59,
		DataOtherTwo: datatwo59,
	}
	if err := coll.InsertOne(ctx, service59Data); err != nil {
		return Service59Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service60.MethodOther60(ctx, id59, data59, datatwo59); err != nil {
		return Service59Data{}, err
	}

	return service59Data, nil
}

func (s *Service59Impl) MethodOtherOther59(ctx context.Context, id59 string, data59 string, datatwo59 string) (Service59Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service59DB.GetCollection(ctx, "service59_db", "service59_data")
	if err != nil {
		return Service59Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id59},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service59Data{}, err
	}
	var service59Data Service59Data
	exists, err := res.One(ctx, &service59Data)
	if err != nil {
		return Service59Data{}, err
	}
	if exists {
		return service59Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service59DB.GetCollection(ctx, "service59_db", "service59_data")
	if err != nil {
		return Service59Data{}, err
	}
	service59Data = Service59Data{
		ID:   id59,
		DataOtherOther: data59,
	}
	if err := coll.InsertOne(ctx, service59Data); err != nil {
		return Service59Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service59DB.GetCollection(ctx, "service59_db", "service59_data")
	if err != nil {
		return Service59Data{}, err
	}
	service59Data = Service59Data{
		ID:   id59,
		DataOtherOtherTwo: datatwo59,
	}
	if err := coll.InsertOne(ctx, service59Data); err != nil {
		return Service59Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service60.MethodOtherOther60(ctx, id59, data59, datatwo59); err != nil {
		return Service59Data{}, err
	}

	return service59Data, nil
}
