// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service386Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service386 interface {
	Method386(ctx context.Context, id string, data string, datatwo string) (Service386Data, error)
	MethodOther386(ctx context.Context, id string, data string, datatwo string) (Service386Data, error)
	MethodOtherOther386(ctx context.Context, id string, data string, datatwo string) (Service386Data, error)
}

type Service386Impl struct {
	service386DB backend.NoSQLDatabase
	service387 Service387
}

func NewService386Impl(ctx context.Context, service386DB backend.NoSQLDatabase, service387 Service387) (Service386, error) {
	return &Service386Impl{
		service386DB: service386DB,
		service387: service387,
	}, nil
}

func (s *Service386Impl) Method386(ctx context.Context, id386 string, data386 string, datatwo386 string) (Service386Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service386DB.GetCollection(ctx, "service386_db", "service386_data")
	if err != nil {
		return Service386Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id386},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service386Data{}, err
	}
	var service386Data Service386Data
	exists, err := res.One(ctx, &service386Data)
	if err != nil {
		return Service386Data{}, err
	}
	if exists {
		return service386Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service386DB.GetCollection(ctx, "service386_db", "service386_data")
	if err != nil {
		return Service386Data{}, err
	}
	service386Data = Service386Data{
		ID:   id386,
		Data: data386,
	}
	if err := coll.InsertOne(ctx, service386Data); err != nil {
		return Service386Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service386DB.GetCollection(ctx, "service386_db", "service386_data")
	if err != nil {
		return Service386Data{}, err
	}
	service386Data = Service386Data{
		ID:   id386,
		DataTwo: datatwo386,
	}
	if err := coll.InsertOne(ctx, service386Data); err != nil {
		return Service386Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service387.Method387(ctx, id386, data386, datatwo386); err != nil {
		return Service386Data{}, err
	}

	return service386Data, nil
}

func (s *Service386Impl) MethodOther386(ctx context.Context, id386 string, data386 string, datatwo386 string) (Service386Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service386DB.GetCollection(ctx, "service386_db", "service386_data")
	if err != nil {
		return Service386Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id386},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service386Data{}, err
	}
	var service386Data Service386Data
	exists, err := res.One(ctx, &service386Data)
	if err != nil {
		return Service386Data{}, err
	}
	if exists {
		return service386Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service386DB.GetCollection(ctx, "service386_db", "service386_data")
	if err != nil {
		return Service386Data{}, err
	}
	service386Data = Service386Data{
		ID:   id386,
		DataOther: data386,
	}
	if err := coll.InsertOne(ctx, service386Data); err != nil {
		return Service386Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service386DB.GetCollection(ctx, "service386_db", "service386_data")
	if err != nil {
		return Service386Data{}, err
	}
	service386Data = Service386Data{
		ID:   id386,
		DataOtherTwo: datatwo386,
	}
	if err := coll.InsertOne(ctx, service386Data); err != nil {
		return Service386Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service387.MethodOther387(ctx, id386, data386, datatwo386); err != nil {
		return Service386Data{}, err
	}

	return service386Data, nil
}

func (s *Service386Impl) MethodOtherOther386(ctx context.Context, id386 string, data386 string, datatwo386 string) (Service386Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service386DB.GetCollection(ctx, "service386_db", "service386_data")
	if err != nil {
		return Service386Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id386},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service386Data{}, err
	}
	var service386Data Service386Data
	exists, err := res.One(ctx, &service386Data)
	if err != nil {
		return Service386Data{}, err
	}
	if exists {
		return service386Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service386DB.GetCollection(ctx, "service386_db", "service386_data")
	if err != nil {
		return Service386Data{}, err
	}
	service386Data = Service386Data{
		ID:   id386,
		DataOtherOther: data386,
	}
	if err := coll.InsertOne(ctx, service386Data); err != nil {
		return Service386Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service386DB.GetCollection(ctx, "service386_db", "service386_data")
	if err != nil {
		return Service386Data{}, err
	}
	service386Data = Service386Data{
		ID:   id386,
		DataOtherOtherTwo: datatwo386,
	}
	if err := coll.InsertOne(ctx, service386Data); err != nil {
		return Service386Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service387.MethodOtherOther387(ctx, id386, data386, datatwo386); err != nil {
		return Service386Data{}, err
	}

	return service386Data, nil
}
