// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service102Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service102 interface {
	Method102(ctx context.Context, id string, data string, datatwo string) (Service102Data, error)
	MethodOther102(ctx context.Context, id string, data string, datatwo string) (Service102Data, error)
	MethodOtherOther102(ctx context.Context, id string, data string, datatwo string) (Service102Data, error)
}

type Service102Impl struct {
	service102DB backend.NoSQLDatabase
	service103 Service103
}

func NewService102Impl(ctx context.Context, service102DB backend.NoSQLDatabase, service103 Service103) (Service102, error) {
	return &Service102Impl{
		service102DB: service102DB,
		service103: service103,
	}, nil
}

func (s *Service102Impl) Method102(ctx context.Context, id102 string, data102 string, datatwo102 string) (Service102Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service102DB.GetCollection(ctx, "service102_db", "service102_data")
	if err != nil {
		return Service102Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id102},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service102Data{}, err
	}
	var service102Data Service102Data
	exists, err := res.One(ctx, &service102Data)
	if err != nil {
		return Service102Data{}, err
	}
	if exists {
		return service102Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service102DB.GetCollection(ctx, "service102_db", "service102_data")
	if err != nil {
		return Service102Data{}, err
	}
	service102Data = Service102Data{
		ID:   id102,
		Data: data102,
	}
	if err := coll.InsertOne(ctx, service102Data); err != nil {
		return Service102Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service102DB.GetCollection(ctx, "service102_db", "service102_data")
	if err != nil {
		return Service102Data{}, err
	}
	service102Data = Service102Data{
		ID:   id102,
		DataTwo: datatwo102,
	}
	if err := coll.InsertOne(ctx, service102Data); err != nil {
		return Service102Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service103.Method103(ctx, id102, data102, datatwo102); err != nil {
		return Service102Data{}, err
	}

	return service102Data, nil
}

func (s *Service102Impl) MethodOther102(ctx context.Context, id102 string, data102 string, datatwo102 string) (Service102Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service102DB.GetCollection(ctx, "service102_db", "service102_data")
	if err != nil {
		return Service102Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id102},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service102Data{}, err
	}
	var service102Data Service102Data
	exists, err := res.One(ctx, &service102Data)
	if err != nil {
		return Service102Data{}, err
	}
	if exists {
		return service102Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service102DB.GetCollection(ctx, "service102_db", "service102_data")
	if err != nil {
		return Service102Data{}, err
	}
	service102Data = Service102Data{
		ID:   id102,
		DataOther: data102,
	}
	if err := coll.InsertOne(ctx, service102Data); err != nil {
		return Service102Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service102DB.GetCollection(ctx, "service102_db", "service102_data")
	if err != nil {
		return Service102Data{}, err
	}
	service102Data = Service102Data{
		ID:   id102,
		DataOtherTwo: datatwo102,
	}
	if err := coll.InsertOne(ctx, service102Data); err != nil {
		return Service102Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service103.MethodOther103(ctx, id102, data102, datatwo102); err != nil {
		return Service102Data{}, err
	}

	return service102Data, nil
}

func (s *Service102Impl) MethodOtherOther102(ctx context.Context, id102 string, data102 string, datatwo102 string) (Service102Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service102DB.GetCollection(ctx, "service102_db", "service102_data")
	if err != nil {
		return Service102Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id102},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service102Data{}, err
	}
	var service102Data Service102Data
	exists, err := res.One(ctx, &service102Data)
	if err != nil {
		return Service102Data{}, err
	}
	if exists {
		return service102Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service102DB.GetCollection(ctx, "service102_db", "service102_data")
	if err != nil {
		return Service102Data{}, err
	}
	service102Data = Service102Data{
		ID:   id102,
		DataOtherOther: data102,
	}
	if err := coll.InsertOne(ctx, service102Data); err != nil {
		return Service102Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service102DB.GetCollection(ctx, "service102_db", "service102_data")
	if err != nil {
		return Service102Data{}, err
	}
	service102Data = Service102Data{
		ID:   id102,
		DataOtherOtherTwo: datatwo102,
	}
	if err := coll.InsertOne(ctx, service102Data); err != nil {
		return Service102Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service103.MethodOtherOther103(ctx, id102, data102, datatwo102); err != nil {
		return Service102Data{}, err
	}

	return service102Data, nil
}
