// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service268Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service268 interface {
	Method268(ctx context.Context, id string, data string, datatwo string) (Service268Data, error)
	MethodOther268(ctx context.Context, id string, data string, datatwo string) (Service268Data, error)
	MethodOtherOther268(ctx context.Context, id string, data string, datatwo string) (Service268Data, error)
}

type Service268Impl struct {
	service268DB backend.NoSQLDatabase
	service269 Service269
}

func NewService268Impl(ctx context.Context, service268DB backend.NoSQLDatabase, service269 Service269) (Service268, error) {
	return &Service268Impl{
		service268DB: service268DB,
		service269: service269,
	}, nil
}

func (s *Service268Impl) Method268(ctx context.Context, id268 string, data268 string, datatwo268 string) (Service268Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service268DB.GetCollection(ctx, "service268_db", "service268_data")
	if err != nil {
		return Service268Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id268},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service268Data{}, err
	}
	var service268Data Service268Data
	exists, err := res.One(ctx, &service268Data)
	if err != nil {
		return Service268Data{}, err
	}
	if exists {
		return service268Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service268DB.GetCollection(ctx, "service268_db", "service268_data")
	if err != nil {
		return Service268Data{}, err
	}
	service268Data = Service268Data{
		ID:   id268,
		Data: data268,
	}
	if err := coll.InsertOne(ctx, service268Data); err != nil {
		return Service268Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service268DB.GetCollection(ctx, "service268_db", "service268_data")
	if err != nil {
		return Service268Data{}, err
	}
	service268Data = Service268Data{
		ID:   id268,
		DataTwo: datatwo268,
	}
	if err := coll.InsertOne(ctx, service268Data); err != nil {
		return Service268Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service269.Method269(ctx, id268, data268, datatwo268); err != nil {
		return Service268Data{}, err
	}

	return service268Data, nil
}

func (s *Service268Impl) MethodOther268(ctx context.Context, id268 string, data268 string, datatwo268 string) (Service268Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service268DB.GetCollection(ctx, "service268_db", "service268_data")
	if err != nil {
		return Service268Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id268},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service268Data{}, err
	}
	var service268Data Service268Data
	exists, err := res.One(ctx, &service268Data)
	if err != nil {
		return Service268Data{}, err
	}
	if exists {
		return service268Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service268DB.GetCollection(ctx, "service268_db", "service268_data")
	if err != nil {
		return Service268Data{}, err
	}
	service268Data = Service268Data{
		ID:   id268,
		DataOther: data268,
	}
	if err := coll.InsertOne(ctx, service268Data); err != nil {
		return Service268Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service268DB.GetCollection(ctx, "service268_db", "service268_data")
	if err != nil {
		return Service268Data{}, err
	}
	service268Data = Service268Data{
		ID:   id268,
		DataOtherTwo: datatwo268,
	}
	if err := coll.InsertOne(ctx, service268Data); err != nil {
		return Service268Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service269.MethodOther269(ctx, id268, data268, datatwo268); err != nil {
		return Service268Data{}, err
	}

	return service268Data, nil
}

func (s *Service268Impl) MethodOtherOther268(ctx context.Context, id268 string, data268 string, datatwo268 string) (Service268Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service268DB.GetCollection(ctx, "service268_db", "service268_data")
	if err != nil {
		return Service268Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id268},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service268Data{}, err
	}
	var service268Data Service268Data
	exists, err := res.One(ctx, &service268Data)
	if err != nil {
		return Service268Data{}, err
	}
	if exists {
		return service268Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service268DB.GetCollection(ctx, "service268_db", "service268_data")
	if err != nil {
		return Service268Data{}, err
	}
	service268Data = Service268Data{
		ID:   id268,
		DataOtherOther: data268,
	}
	if err := coll.InsertOne(ctx, service268Data); err != nil {
		return Service268Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service268DB.GetCollection(ctx, "service268_db", "service268_data")
	if err != nil {
		return Service268Data{}, err
	}
	service268Data = Service268Data{
		ID:   id268,
		DataOtherOtherTwo: datatwo268,
	}
	if err := coll.InsertOne(ctx, service268Data); err != nil {
		return Service268Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service269.MethodOtherOther269(ctx, id268, data268, datatwo268); err != nil {
		return Service268Data{}, err
	}

	return service268Data, nil
}
