// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service295Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service295 interface {
	Method295(ctx context.Context, id string, data string, datatwo string) (Service295Data, error)
	MethodOther295(ctx context.Context, id string, data string, datatwo string) (Service295Data, error)
	MethodOtherOther295(ctx context.Context, id string, data string, datatwo string) (Service295Data, error)
}

type Service295Impl struct {
	service295DB backend.NoSQLDatabase
	service296 Service296
}

func NewService295Impl(ctx context.Context, service295DB backend.NoSQLDatabase, service296 Service296) (Service295, error) {
	return &Service295Impl{
		service295DB: service295DB,
		service296: service296,
	}, nil
}

func (s *Service295Impl) Method295(ctx context.Context, id295 string, data295 string, datatwo295 string) (Service295Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service295DB.GetCollection(ctx, "service295_db", "service295_data")
	if err != nil {
		return Service295Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id295},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service295Data{}, err
	}
	var service295Data Service295Data
	exists, err := res.One(ctx, &service295Data)
	if err != nil {
		return Service295Data{}, err
	}
	if exists {
		return service295Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service295DB.GetCollection(ctx, "service295_db", "service295_data")
	if err != nil {
		return Service295Data{}, err
	}
	service295Data = Service295Data{
		ID:   id295,
		Data: data295,
	}
	if err := coll.InsertOne(ctx, service295Data); err != nil {
		return Service295Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service295DB.GetCollection(ctx, "service295_db", "service295_data")
	if err != nil {
		return Service295Data{}, err
	}
	service295Data = Service295Data{
		ID:   id295,
		DataTwo: datatwo295,
	}
	if err := coll.InsertOne(ctx, service295Data); err != nil {
		return Service295Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service296.Method296(ctx, id295, data295, datatwo295); err != nil {
		return Service295Data{}, err
	}

	return service295Data, nil
}

func (s *Service295Impl) MethodOther295(ctx context.Context, id295 string, data295 string, datatwo295 string) (Service295Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service295DB.GetCollection(ctx, "service295_db", "service295_data")
	if err != nil {
		return Service295Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id295},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service295Data{}, err
	}
	var service295Data Service295Data
	exists, err := res.One(ctx, &service295Data)
	if err != nil {
		return Service295Data{}, err
	}
	if exists {
		return service295Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service295DB.GetCollection(ctx, "service295_db", "service295_data")
	if err != nil {
		return Service295Data{}, err
	}
	service295Data = Service295Data{
		ID:   id295,
		DataOther: data295,
	}
	if err := coll.InsertOne(ctx, service295Data); err != nil {
		return Service295Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service295DB.GetCollection(ctx, "service295_db", "service295_data")
	if err != nil {
		return Service295Data{}, err
	}
	service295Data = Service295Data{
		ID:   id295,
		DataOtherTwo: datatwo295,
	}
	if err := coll.InsertOne(ctx, service295Data); err != nil {
		return Service295Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service296.MethodOther296(ctx, id295, data295, datatwo295); err != nil {
		return Service295Data{}, err
	}

	return service295Data, nil
}

func (s *Service295Impl) MethodOtherOther295(ctx context.Context, id295 string, data295 string, datatwo295 string) (Service295Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service295DB.GetCollection(ctx, "service295_db", "service295_data")
	if err != nil {
		return Service295Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id295},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service295Data{}, err
	}
	var service295Data Service295Data
	exists, err := res.One(ctx, &service295Data)
	if err != nil {
		return Service295Data{}, err
	}
	if exists {
		return service295Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service295DB.GetCollection(ctx, "service295_db", "service295_data")
	if err != nil {
		return Service295Data{}, err
	}
	service295Data = Service295Data{
		ID:   id295,
		DataOtherOther: data295,
	}
	if err := coll.InsertOne(ctx, service295Data); err != nil {
		return Service295Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service295DB.GetCollection(ctx, "service295_db", "service295_data")
	if err != nil {
		return Service295Data{}, err
	}
	service295Data = Service295Data{
		ID:   id295,
		DataOtherOtherTwo: datatwo295,
	}
	if err := coll.InsertOne(ctx, service295Data); err != nil {
		return Service295Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service296.MethodOtherOther296(ctx, id295, data295, datatwo295); err != nil {
		return Service295Data{}, err
	}

	return service295Data, nil
}
