// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service402Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service402 interface {
	Method402(ctx context.Context, id string, data string, datatwo string) (Service402Data, error)
	MethodOther402(ctx context.Context, id string, data string, datatwo string) (Service402Data, error)
	MethodOtherOther402(ctx context.Context, id string, data string, datatwo string) (Service402Data, error)
}

type Service402Impl struct {
	service402DB backend.NoSQLDatabase
	service403 Service403
}

func NewService402Impl(ctx context.Context, service402DB backend.NoSQLDatabase, service403 Service403) (Service402, error) {
	return &Service402Impl{
		service402DB: service402DB,
		service403: service403,
	}, nil
}

func (s *Service402Impl) Method402(ctx context.Context, id402 string, data402 string, datatwo402 string) (Service402Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service402DB.GetCollection(ctx, "service402_db", "service402_data")
	if err != nil {
		return Service402Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id402},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service402Data{}, err
	}
	var service402Data Service402Data
	exists, err := res.One(ctx, &service402Data)
	if err != nil {
		return Service402Data{}, err
	}
	if exists {
		return service402Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service402DB.GetCollection(ctx, "service402_db", "service402_data")
	if err != nil {
		return Service402Data{}, err
	}
	service402Data = Service402Data{
		ID:   id402,
		Data: data402,
	}
	if err := coll.InsertOne(ctx, service402Data); err != nil {
		return Service402Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service402DB.GetCollection(ctx, "service402_db", "service402_data")
	if err != nil {
		return Service402Data{}, err
	}
	service402Data = Service402Data{
		ID:   id402,
		DataTwo: datatwo402,
	}
	if err := coll.InsertOne(ctx, service402Data); err != nil {
		return Service402Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service403.Method403(ctx, id402, data402, datatwo402); err != nil {
		return Service402Data{}, err
	}

	return service402Data, nil
}

func (s *Service402Impl) MethodOther402(ctx context.Context, id402 string, data402 string, datatwo402 string) (Service402Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service402DB.GetCollection(ctx, "service402_db", "service402_data")
	if err != nil {
		return Service402Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id402},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service402Data{}, err
	}
	var service402Data Service402Data
	exists, err := res.One(ctx, &service402Data)
	if err != nil {
		return Service402Data{}, err
	}
	if exists {
		return service402Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service402DB.GetCollection(ctx, "service402_db", "service402_data")
	if err != nil {
		return Service402Data{}, err
	}
	service402Data = Service402Data{
		ID:   id402,
		DataOther: data402,
	}
	if err := coll.InsertOne(ctx, service402Data); err != nil {
		return Service402Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service402DB.GetCollection(ctx, "service402_db", "service402_data")
	if err != nil {
		return Service402Data{}, err
	}
	service402Data = Service402Data{
		ID:   id402,
		DataOtherTwo: datatwo402,
	}
	if err := coll.InsertOne(ctx, service402Data); err != nil {
		return Service402Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service403.MethodOther403(ctx, id402, data402, datatwo402); err != nil {
		return Service402Data{}, err
	}

	return service402Data, nil
}

func (s *Service402Impl) MethodOtherOther402(ctx context.Context, id402 string, data402 string, datatwo402 string) (Service402Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service402DB.GetCollection(ctx, "service402_db", "service402_data")
	if err != nil {
		return Service402Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id402},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service402Data{}, err
	}
	var service402Data Service402Data
	exists, err := res.One(ctx, &service402Data)
	if err != nil {
		return Service402Data{}, err
	}
	if exists {
		return service402Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service402DB.GetCollection(ctx, "service402_db", "service402_data")
	if err != nil {
		return Service402Data{}, err
	}
	service402Data = Service402Data{
		ID:   id402,
		DataOtherOther: data402,
	}
	if err := coll.InsertOne(ctx, service402Data); err != nil {
		return Service402Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service402DB.GetCollection(ctx, "service402_db", "service402_data")
	if err != nil {
		return Service402Data{}, err
	}
	service402Data = Service402Data{
		ID:   id402,
		DataOtherOtherTwo: datatwo402,
	}
	if err := coll.InsertOne(ctx, service402Data); err != nil {
		return Service402Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service403.MethodOtherOther403(ctx, id402, data402, datatwo402); err != nil {
		return Service402Data{}, err
	}

	return service402Data, nil
}
