// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service79Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service79 interface {
	Method79(ctx context.Context, id string, data string, datatwo string) (Service79Data, error)
	MethodOther79(ctx context.Context, id string, data string, datatwo string) (Service79Data, error)
	MethodOtherOther79(ctx context.Context, id string, data string, datatwo string) (Service79Data, error)
}

type Service79Impl struct {
	service79DB backend.NoSQLDatabase
	service80 Service80
}

func NewService79Impl(ctx context.Context, service79DB backend.NoSQLDatabase, service80 Service80) (Service79, error) {
	return &Service79Impl{
		service79DB: service79DB,
		service80: service80,
	}, nil
}

func (s *Service79Impl) Method79(ctx context.Context, id79 string, data79 string, datatwo79 string) (Service79Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service79DB.GetCollection(ctx, "service79_db", "service79_data")
	if err != nil {
		return Service79Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id79},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service79Data{}, err
	}
	var service79Data Service79Data
	exists, err := res.One(ctx, &service79Data)
	if err != nil {
		return Service79Data{}, err
	}
	if exists {
		return service79Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service79DB.GetCollection(ctx, "service79_db", "service79_data")
	if err != nil {
		return Service79Data{}, err
	}
	service79Data = Service79Data{
		ID:   id79,
		Data: data79,
	}
	if err := coll.InsertOne(ctx, service79Data); err != nil {
		return Service79Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service79DB.GetCollection(ctx, "service79_db", "service79_data")
	if err != nil {
		return Service79Data{}, err
	}
	service79Data = Service79Data{
		ID:   id79,
		DataTwo: datatwo79,
	}
	if err := coll.InsertOne(ctx, service79Data); err != nil {
		return Service79Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service80.Method80(ctx, id79, data79, datatwo79); err != nil {
		return Service79Data{}, err
	}

	return service79Data, nil
}

func (s *Service79Impl) MethodOther79(ctx context.Context, id79 string, data79 string, datatwo79 string) (Service79Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service79DB.GetCollection(ctx, "service79_db", "service79_data")
	if err != nil {
		return Service79Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id79},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service79Data{}, err
	}
	var service79Data Service79Data
	exists, err := res.One(ctx, &service79Data)
	if err != nil {
		return Service79Data{}, err
	}
	if exists {
		return service79Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service79DB.GetCollection(ctx, "service79_db", "service79_data")
	if err != nil {
		return Service79Data{}, err
	}
	service79Data = Service79Data{
		ID:   id79,
		DataOther: data79,
	}
	if err := coll.InsertOne(ctx, service79Data); err != nil {
		return Service79Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service79DB.GetCollection(ctx, "service79_db", "service79_data")
	if err != nil {
		return Service79Data{}, err
	}
	service79Data = Service79Data{
		ID:   id79,
		DataOtherTwo: datatwo79,
	}
	if err := coll.InsertOne(ctx, service79Data); err != nil {
		return Service79Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service80.MethodOther80(ctx, id79, data79, datatwo79); err != nil {
		return Service79Data{}, err
	}

	return service79Data, nil
}

func (s *Service79Impl) MethodOtherOther79(ctx context.Context, id79 string, data79 string, datatwo79 string) (Service79Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service79DB.GetCollection(ctx, "service79_db", "service79_data")
	if err != nil {
		return Service79Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id79},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service79Data{}, err
	}
	var service79Data Service79Data
	exists, err := res.One(ctx, &service79Data)
	if err != nil {
		return Service79Data{}, err
	}
	if exists {
		return service79Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service79DB.GetCollection(ctx, "service79_db", "service79_data")
	if err != nil {
		return Service79Data{}, err
	}
	service79Data = Service79Data{
		ID:   id79,
		DataOtherOther: data79,
	}
	if err := coll.InsertOne(ctx, service79Data); err != nil {
		return Service79Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service79DB.GetCollection(ctx, "service79_db", "service79_data")
	if err != nil {
		return Service79Data{}, err
	}
	service79Data = Service79Data{
		ID:   id79,
		DataOtherOtherTwo: datatwo79,
	}
	if err := coll.InsertOne(ctx, service79Data); err != nil {
		return Service79Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service80.MethodOtherOther80(ctx, id79, data79, datatwo79); err != nil {
		return Service79Data{}, err
	}

	return service79Data, nil
}
