// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service373Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service373 interface {
	Method373(ctx context.Context, id string, data string, datatwo string) (Service373Data, error)
	MethodOther373(ctx context.Context, id string, data string, datatwo string) (Service373Data, error)
	MethodOtherOther373(ctx context.Context, id string, data string, datatwo string) (Service373Data, error)
}

type Service373Impl struct {
	service373DB backend.NoSQLDatabase
	service374 Service374
}

func NewService373Impl(ctx context.Context, service373DB backend.NoSQLDatabase, service374 Service374) (Service373, error) {
	return &Service373Impl{
		service373DB: service373DB,
		service374: service374,
	}, nil
}

func (s *Service373Impl) Method373(ctx context.Context, id373 string, data373 string, datatwo373 string) (Service373Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service373DB.GetCollection(ctx, "service373_db", "service373_data")
	if err != nil {
		return Service373Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id373},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service373Data{}, err
	}
	var service373Data Service373Data
	exists, err := res.One(ctx, &service373Data)
	if err != nil {
		return Service373Data{}, err
	}
	if exists {
		return service373Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service373DB.GetCollection(ctx, "service373_db", "service373_data")
	if err != nil {
		return Service373Data{}, err
	}
	service373Data = Service373Data{
		ID:   id373,
		Data: data373,
	}
	if err := coll.InsertOne(ctx, service373Data); err != nil {
		return Service373Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service373DB.GetCollection(ctx, "service373_db", "service373_data")
	if err != nil {
		return Service373Data{}, err
	}
	service373Data = Service373Data{
		ID:   id373,
		DataTwo: datatwo373,
	}
	if err := coll.InsertOne(ctx, service373Data); err != nil {
		return Service373Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service374.Method374(ctx, id373, data373, datatwo373); err != nil {
		return Service373Data{}, err
	}

	return service373Data, nil
}

func (s *Service373Impl) MethodOther373(ctx context.Context, id373 string, data373 string, datatwo373 string) (Service373Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service373DB.GetCollection(ctx, "service373_db", "service373_data")
	if err != nil {
		return Service373Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id373},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service373Data{}, err
	}
	var service373Data Service373Data
	exists, err := res.One(ctx, &service373Data)
	if err != nil {
		return Service373Data{}, err
	}
	if exists {
		return service373Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service373DB.GetCollection(ctx, "service373_db", "service373_data")
	if err != nil {
		return Service373Data{}, err
	}
	service373Data = Service373Data{
		ID:   id373,
		DataOther: data373,
	}
	if err := coll.InsertOne(ctx, service373Data); err != nil {
		return Service373Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service373DB.GetCollection(ctx, "service373_db", "service373_data")
	if err != nil {
		return Service373Data{}, err
	}
	service373Data = Service373Data{
		ID:   id373,
		DataOtherTwo: datatwo373,
	}
	if err := coll.InsertOne(ctx, service373Data); err != nil {
		return Service373Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service374.MethodOther374(ctx, id373, data373, datatwo373); err != nil {
		return Service373Data{}, err
	}

	return service373Data, nil
}

func (s *Service373Impl) MethodOtherOther373(ctx context.Context, id373 string, data373 string, datatwo373 string) (Service373Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service373DB.GetCollection(ctx, "service373_db", "service373_data")
	if err != nil {
		return Service373Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id373},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service373Data{}, err
	}
	var service373Data Service373Data
	exists, err := res.One(ctx, &service373Data)
	if err != nil {
		return Service373Data{}, err
	}
	if exists {
		return service373Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service373DB.GetCollection(ctx, "service373_db", "service373_data")
	if err != nil {
		return Service373Data{}, err
	}
	service373Data = Service373Data{
		ID:   id373,
		DataOtherOther: data373,
	}
	if err := coll.InsertOne(ctx, service373Data); err != nil {
		return Service373Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service373DB.GetCollection(ctx, "service373_db", "service373_data")
	if err != nil {
		return Service373Data{}, err
	}
	service373Data = Service373Data{
		ID:   id373,
		DataOtherOtherTwo: datatwo373,
	}
	if err := coll.InsertOne(ctx, service373Data); err != nil {
		return Service373Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service374.MethodOtherOther374(ctx, id373, data373, datatwo373); err != nil {
		return Service373Data{}, err
	}

	return service373Data, nil
}
