// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service358Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service358 interface {
	Method358(ctx context.Context, id string, data string, datatwo string) (Service358Data, error)
	MethodOther358(ctx context.Context, id string, data string, datatwo string) (Service358Data, error)
	MethodOtherOther358(ctx context.Context, id string, data string, datatwo string) (Service358Data, error)
}

type Service358Impl struct {
	service358DB backend.NoSQLDatabase
	service359 Service359
}

func NewService358Impl(ctx context.Context, service358DB backend.NoSQLDatabase, service359 Service359) (Service358, error) {
	return &Service358Impl{
		service358DB: service358DB,
		service359: service359,
	}, nil
}

func (s *Service358Impl) Method358(ctx context.Context, id358 string, data358 string, datatwo358 string) (Service358Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service358DB.GetCollection(ctx, "service358_db", "service358_data")
	if err != nil {
		return Service358Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id358},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service358Data{}, err
	}
	var service358Data Service358Data
	exists, err := res.One(ctx, &service358Data)
	if err != nil {
		return Service358Data{}, err
	}
	if exists {
		return service358Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service358DB.GetCollection(ctx, "service358_db", "service358_data")
	if err != nil {
		return Service358Data{}, err
	}
	service358Data = Service358Data{
		ID:   id358,
		Data: data358,
	}
	if err := coll.InsertOne(ctx, service358Data); err != nil {
		return Service358Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service358DB.GetCollection(ctx, "service358_db", "service358_data")
	if err != nil {
		return Service358Data{}, err
	}
	service358Data = Service358Data{
		ID:   id358,
		DataTwo: datatwo358,
	}
	if err := coll.InsertOne(ctx, service358Data); err != nil {
		return Service358Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service359.Method359(ctx, id358, data358, datatwo358); err != nil {
		return Service358Data{}, err
	}

	return service358Data, nil
}

func (s *Service358Impl) MethodOther358(ctx context.Context, id358 string, data358 string, datatwo358 string) (Service358Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service358DB.GetCollection(ctx, "service358_db", "service358_data")
	if err != nil {
		return Service358Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id358},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service358Data{}, err
	}
	var service358Data Service358Data
	exists, err := res.One(ctx, &service358Data)
	if err != nil {
		return Service358Data{}, err
	}
	if exists {
		return service358Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service358DB.GetCollection(ctx, "service358_db", "service358_data")
	if err != nil {
		return Service358Data{}, err
	}
	service358Data = Service358Data{
		ID:   id358,
		DataOther: data358,
	}
	if err := coll.InsertOne(ctx, service358Data); err != nil {
		return Service358Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service358DB.GetCollection(ctx, "service358_db", "service358_data")
	if err != nil {
		return Service358Data{}, err
	}
	service358Data = Service358Data{
		ID:   id358,
		DataOtherTwo: datatwo358,
	}
	if err := coll.InsertOne(ctx, service358Data); err != nil {
		return Service358Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service359.MethodOther359(ctx, id358, data358, datatwo358); err != nil {
		return Service358Data{}, err
	}

	return service358Data, nil
}

func (s *Service358Impl) MethodOtherOther358(ctx context.Context, id358 string, data358 string, datatwo358 string) (Service358Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service358DB.GetCollection(ctx, "service358_db", "service358_data")
	if err != nil {
		return Service358Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id358},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service358Data{}, err
	}
	var service358Data Service358Data
	exists, err := res.One(ctx, &service358Data)
	if err != nil {
		return Service358Data{}, err
	}
	if exists {
		return service358Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service358DB.GetCollection(ctx, "service358_db", "service358_data")
	if err != nil {
		return Service358Data{}, err
	}
	service358Data = Service358Data{
		ID:   id358,
		DataOtherOther: data358,
	}
	if err := coll.InsertOne(ctx, service358Data); err != nil {
		return Service358Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service358DB.GetCollection(ctx, "service358_db", "service358_data")
	if err != nil {
		return Service358Data{}, err
	}
	service358Data = Service358Data{
		ID:   id358,
		DataOtherOtherTwo: datatwo358,
	}
	if err := coll.InsertOne(ctx, service358Data); err != nil {
		return Service358Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service359.MethodOtherOther359(ctx, id358, data358, datatwo358); err != nil {
		return Service358Data{}, err
	}

	return service358Data, nil
}
