// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service75Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service75 interface {
	Method75(ctx context.Context, id string, data string, datatwo string) (Service75Data, error)
	MethodOther75(ctx context.Context, id string, data string, datatwo string) (Service75Data, error)
	MethodOtherOther75(ctx context.Context, id string, data string, datatwo string) (Service75Data, error)
}

type Service75Impl struct {
	service75DB backend.NoSQLDatabase
	service76 Service76
}

func NewService75Impl(ctx context.Context, service75DB backend.NoSQLDatabase, service76 Service76) (Service75, error) {
	return &Service75Impl{
		service75DB: service75DB,
		service76: service76,
	}, nil
}

func (s *Service75Impl) Method75(ctx context.Context, id75 string, data75 string, datatwo75 string) (Service75Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service75DB.GetCollection(ctx, "service75_db", "service75_data")
	if err != nil {
		return Service75Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id75},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service75Data{}, err
	}
	var service75Data Service75Data
	exists, err := res.One(ctx, &service75Data)
	if err != nil {
		return Service75Data{}, err
	}
	if exists {
		return service75Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service75DB.GetCollection(ctx, "service75_db", "service75_data")
	if err != nil {
		return Service75Data{}, err
	}
	service75Data = Service75Data{
		ID:   id75,
		Data: data75,
	}
	if err := coll.InsertOne(ctx, service75Data); err != nil {
		return Service75Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service75DB.GetCollection(ctx, "service75_db", "service75_data")
	if err != nil {
		return Service75Data{}, err
	}
	service75Data = Service75Data{
		ID:   id75,
		DataTwo: datatwo75,
	}
	if err := coll.InsertOne(ctx, service75Data); err != nil {
		return Service75Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service76.Method76(ctx, id75, data75, datatwo75); err != nil {
		return Service75Data{}, err
	}

	return service75Data, nil
}

func (s *Service75Impl) MethodOther75(ctx context.Context, id75 string, data75 string, datatwo75 string) (Service75Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service75DB.GetCollection(ctx, "service75_db", "service75_data")
	if err != nil {
		return Service75Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id75},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service75Data{}, err
	}
	var service75Data Service75Data
	exists, err := res.One(ctx, &service75Data)
	if err != nil {
		return Service75Data{}, err
	}
	if exists {
		return service75Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service75DB.GetCollection(ctx, "service75_db", "service75_data")
	if err != nil {
		return Service75Data{}, err
	}
	service75Data = Service75Data{
		ID:   id75,
		DataOther: data75,
	}
	if err := coll.InsertOne(ctx, service75Data); err != nil {
		return Service75Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service75DB.GetCollection(ctx, "service75_db", "service75_data")
	if err != nil {
		return Service75Data{}, err
	}
	service75Data = Service75Data{
		ID:   id75,
		DataOtherTwo: datatwo75,
	}
	if err := coll.InsertOne(ctx, service75Data); err != nil {
		return Service75Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service76.MethodOther76(ctx, id75, data75, datatwo75); err != nil {
		return Service75Data{}, err
	}

	return service75Data, nil
}

func (s *Service75Impl) MethodOtherOther75(ctx context.Context, id75 string, data75 string, datatwo75 string) (Service75Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service75DB.GetCollection(ctx, "service75_db", "service75_data")
	if err != nil {
		return Service75Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id75},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service75Data{}, err
	}
	var service75Data Service75Data
	exists, err := res.One(ctx, &service75Data)
	if err != nil {
		return Service75Data{}, err
	}
	if exists {
		return service75Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service75DB.GetCollection(ctx, "service75_db", "service75_data")
	if err != nil {
		return Service75Data{}, err
	}
	service75Data = Service75Data{
		ID:   id75,
		DataOtherOther: data75,
	}
	if err := coll.InsertOne(ctx, service75Data); err != nil {
		return Service75Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service75DB.GetCollection(ctx, "service75_db", "service75_data")
	if err != nil {
		return Service75Data{}, err
	}
	service75Data = Service75Data{
		ID:   id75,
		DataOtherOtherTwo: datatwo75,
	}
	if err := coll.InsertOne(ctx, service75Data); err != nil {
		return Service75Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service76.MethodOtherOther76(ctx, id75, data75, datatwo75); err != nil {
		return Service75Data{}, err
	}

	return service75Data, nil
}
