// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service247Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service247 interface {
	Method247(ctx context.Context, id string, data string, datatwo string) (Service247Data, error)
	MethodOther247(ctx context.Context, id string, data string, datatwo string) (Service247Data, error)
	MethodOtherOther247(ctx context.Context, id string, data string, datatwo string) (Service247Data, error)
}

type Service247Impl struct {
	service247DB backend.NoSQLDatabase
	service248 Service248
}

func NewService247Impl(ctx context.Context, service247DB backend.NoSQLDatabase, service248 Service248) (Service247, error) {
	return &Service247Impl{
		service247DB: service247DB,
		service248: service248,
	}, nil
}

func (s *Service247Impl) Method247(ctx context.Context, id247 string, data247 string, datatwo247 string) (Service247Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service247DB.GetCollection(ctx, "service247_db", "service247_data")
	if err != nil {
		return Service247Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id247},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service247Data{}, err
	}
	var service247Data Service247Data
	exists, err := res.One(ctx, &service247Data)
	if err != nil {
		return Service247Data{}, err
	}
	if exists {
		return service247Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service247DB.GetCollection(ctx, "service247_db", "service247_data")
	if err != nil {
		return Service247Data{}, err
	}
	service247Data = Service247Data{
		ID:   id247,
		Data: data247,
	}
	if err := coll.InsertOne(ctx, service247Data); err != nil {
		return Service247Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service247DB.GetCollection(ctx, "service247_db", "service247_data")
	if err != nil {
		return Service247Data{}, err
	}
	service247Data = Service247Data{
		ID:   id247,
		DataTwo: datatwo247,
	}
	if err := coll.InsertOne(ctx, service247Data); err != nil {
		return Service247Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service248.Method248(ctx, id247, data247, datatwo247); err != nil {
		return Service247Data{}, err
	}

	return service247Data, nil
}

func (s *Service247Impl) MethodOther247(ctx context.Context, id247 string, data247 string, datatwo247 string) (Service247Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service247DB.GetCollection(ctx, "service247_db", "service247_data")
	if err != nil {
		return Service247Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id247},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service247Data{}, err
	}
	var service247Data Service247Data
	exists, err := res.One(ctx, &service247Data)
	if err != nil {
		return Service247Data{}, err
	}
	if exists {
		return service247Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service247DB.GetCollection(ctx, "service247_db", "service247_data")
	if err != nil {
		return Service247Data{}, err
	}
	service247Data = Service247Data{
		ID:   id247,
		DataOther: data247,
	}
	if err := coll.InsertOne(ctx, service247Data); err != nil {
		return Service247Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service247DB.GetCollection(ctx, "service247_db", "service247_data")
	if err != nil {
		return Service247Data{}, err
	}
	service247Data = Service247Data{
		ID:   id247,
		DataOtherTwo: datatwo247,
	}
	if err := coll.InsertOne(ctx, service247Data); err != nil {
		return Service247Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service248.MethodOther248(ctx, id247, data247, datatwo247); err != nil {
		return Service247Data{}, err
	}

	return service247Data, nil
}

func (s *Service247Impl) MethodOtherOther247(ctx context.Context, id247 string, data247 string, datatwo247 string) (Service247Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service247DB.GetCollection(ctx, "service247_db", "service247_data")
	if err != nil {
		return Service247Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id247},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service247Data{}, err
	}
	var service247Data Service247Data
	exists, err := res.One(ctx, &service247Data)
	if err != nil {
		return Service247Data{}, err
	}
	if exists {
		return service247Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service247DB.GetCollection(ctx, "service247_db", "service247_data")
	if err != nil {
		return Service247Data{}, err
	}
	service247Data = Service247Data{
		ID:   id247,
		DataOtherOther: data247,
	}
	if err := coll.InsertOne(ctx, service247Data); err != nil {
		return Service247Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service247DB.GetCollection(ctx, "service247_db", "service247_data")
	if err != nil {
		return Service247Data{}, err
	}
	service247Data = Service247Data{
		ID:   id247,
		DataOtherOtherTwo: datatwo247,
	}
	if err := coll.InsertOne(ctx, service247Data); err != nil {
		return Service247Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service248.MethodOtherOther248(ctx, id247, data247, datatwo247); err != nil {
		return Service247Data{}, err
	}

	return service247Data, nil
}
