// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service305Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service305 interface {
	Method305(ctx context.Context, id string, data string, datatwo string) (Service305Data, error)
	MethodOther305(ctx context.Context, id string, data string, datatwo string) (Service305Data, error)
	MethodOtherOther305(ctx context.Context, id string, data string, datatwo string) (Service305Data, error)
}

type Service305Impl struct {
	service305DB backend.NoSQLDatabase
	service306 Service306
}

func NewService305Impl(ctx context.Context, service305DB backend.NoSQLDatabase, service306 Service306) (Service305, error) {
	return &Service305Impl{
		service305DB: service305DB,
		service306: service306,
	}, nil
}

func (s *Service305Impl) Method305(ctx context.Context, id305 string, data305 string, datatwo305 string) (Service305Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service305DB.GetCollection(ctx, "service305_db", "service305_data")
	if err != nil {
		return Service305Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id305},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service305Data{}, err
	}
	var service305Data Service305Data
	exists, err := res.One(ctx, &service305Data)
	if err != nil {
		return Service305Data{}, err
	}
	if exists {
		return service305Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service305DB.GetCollection(ctx, "service305_db", "service305_data")
	if err != nil {
		return Service305Data{}, err
	}
	service305Data = Service305Data{
		ID:   id305,
		Data: data305,
	}
	if err := coll.InsertOne(ctx, service305Data); err != nil {
		return Service305Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service305DB.GetCollection(ctx, "service305_db", "service305_data")
	if err != nil {
		return Service305Data{}, err
	}
	service305Data = Service305Data{
		ID:   id305,
		DataTwo: datatwo305,
	}
	if err := coll.InsertOne(ctx, service305Data); err != nil {
		return Service305Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service306.Method306(ctx, id305, data305, datatwo305); err != nil {
		return Service305Data{}, err
	}

	return service305Data, nil
}

func (s *Service305Impl) MethodOther305(ctx context.Context, id305 string, data305 string, datatwo305 string) (Service305Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service305DB.GetCollection(ctx, "service305_db", "service305_data")
	if err != nil {
		return Service305Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id305},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service305Data{}, err
	}
	var service305Data Service305Data
	exists, err := res.One(ctx, &service305Data)
	if err != nil {
		return Service305Data{}, err
	}
	if exists {
		return service305Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service305DB.GetCollection(ctx, "service305_db", "service305_data")
	if err != nil {
		return Service305Data{}, err
	}
	service305Data = Service305Data{
		ID:   id305,
		DataOther: data305,
	}
	if err := coll.InsertOne(ctx, service305Data); err != nil {
		return Service305Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service305DB.GetCollection(ctx, "service305_db", "service305_data")
	if err != nil {
		return Service305Data{}, err
	}
	service305Data = Service305Data{
		ID:   id305,
		DataOtherTwo: datatwo305,
	}
	if err := coll.InsertOne(ctx, service305Data); err != nil {
		return Service305Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service306.MethodOther306(ctx, id305, data305, datatwo305); err != nil {
		return Service305Data{}, err
	}

	return service305Data, nil
}

func (s *Service305Impl) MethodOtherOther305(ctx context.Context, id305 string, data305 string, datatwo305 string) (Service305Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service305DB.GetCollection(ctx, "service305_db", "service305_data")
	if err != nil {
		return Service305Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id305},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service305Data{}, err
	}
	var service305Data Service305Data
	exists, err := res.One(ctx, &service305Data)
	if err != nil {
		return Service305Data{}, err
	}
	if exists {
		return service305Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service305DB.GetCollection(ctx, "service305_db", "service305_data")
	if err != nil {
		return Service305Data{}, err
	}
	service305Data = Service305Data{
		ID:   id305,
		DataOtherOther: data305,
	}
	if err := coll.InsertOne(ctx, service305Data); err != nil {
		return Service305Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service305DB.GetCollection(ctx, "service305_db", "service305_data")
	if err != nil {
		return Service305Data{}, err
	}
	service305Data = Service305Data{
		ID:   id305,
		DataOtherOtherTwo: datatwo305,
	}
	if err := coll.InsertOne(ctx, service305Data); err != nil {
		return Service305Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service306.MethodOtherOther306(ctx, id305, data305, datatwo305); err != nil {
		return Service305Data{}, err
	}

	return service305Data, nil
}
