// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service231Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service231 interface {
	Method231(ctx context.Context, id string, data string, datatwo string) (Service231Data, error)
	MethodOther231(ctx context.Context, id string, data string, datatwo string) (Service231Data, error)
	MethodOtherOther231(ctx context.Context, id string, data string, datatwo string) (Service231Data, error)
}

type Service231Impl struct {
	service231DB backend.NoSQLDatabase
	service232 Service232
}

func NewService231Impl(ctx context.Context, service231DB backend.NoSQLDatabase, service232 Service232) (Service231, error) {
	return &Service231Impl{
		service231DB: service231DB,
		service232: service232,
	}, nil
}

func (s *Service231Impl) Method231(ctx context.Context, id231 string, data231 string, datatwo231 string) (Service231Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service231DB.GetCollection(ctx, "service231_db", "service231_data")
	if err != nil {
		return Service231Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id231},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service231Data{}, err
	}
	var service231Data Service231Data
	exists, err := res.One(ctx, &service231Data)
	if err != nil {
		return Service231Data{}, err
	}
	if exists {
		return service231Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service231DB.GetCollection(ctx, "service231_db", "service231_data")
	if err != nil {
		return Service231Data{}, err
	}
	service231Data = Service231Data{
		ID:   id231,
		Data: data231,
	}
	if err := coll.InsertOne(ctx, service231Data); err != nil {
		return Service231Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service231DB.GetCollection(ctx, "service231_db", "service231_data")
	if err != nil {
		return Service231Data{}, err
	}
	service231Data = Service231Data{
		ID:   id231,
		DataTwo: datatwo231,
	}
	if err := coll.InsertOne(ctx, service231Data); err != nil {
		return Service231Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service232.Method232(ctx, id231, data231, datatwo231); err != nil {
		return Service231Data{}, err
	}

	return service231Data, nil
}

func (s *Service231Impl) MethodOther231(ctx context.Context, id231 string, data231 string, datatwo231 string) (Service231Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service231DB.GetCollection(ctx, "service231_db", "service231_data")
	if err != nil {
		return Service231Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id231},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service231Data{}, err
	}
	var service231Data Service231Data
	exists, err := res.One(ctx, &service231Data)
	if err != nil {
		return Service231Data{}, err
	}
	if exists {
		return service231Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service231DB.GetCollection(ctx, "service231_db", "service231_data")
	if err != nil {
		return Service231Data{}, err
	}
	service231Data = Service231Data{
		ID:   id231,
		DataOther: data231,
	}
	if err := coll.InsertOne(ctx, service231Data); err != nil {
		return Service231Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service231DB.GetCollection(ctx, "service231_db", "service231_data")
	if err != nil {
		return Service231Data{}, err
	}
	service231Data = Service231Data{
		ID:   id231,
		DataOtherTwo: datatwo231,
	}
	if err := coll.InsertOne(ctx, service231Data); err != nil {
		return Service231Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service232.MethodOther232(ctx, id231, data231, datatwo231); err != nil {
		return Service231Data{}, err
	}

	return service231Data, nil
}

func (s *Service231Impl) MethodOtherOther231(ctx context.Context, id231 string, data231 string, datatwo231 string) (Service231Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service231DB.GetCollection(ctx, "service231_db", "service231_data")
	if err != nil {
		return Service231Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id231},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service231Data{}, err
	}
	var service231Data Service231Data
	exists, err := res.One(ctx, &service231Data)
	if err != nil {
		return Service231Data{}, err
	}
	if exists {
		return service231Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service231DB.GetCollection(ctx, "service231_db", "service231_data")
	if err != nil {
		return Service231Data{}, err
	}
	service231Data = Service231Data{
		ID:   id231,
		DataOtherOther: data231,
	}
	if err := coll.InsertOne(ctx, service231Data); err != nil {
		return Service231Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service231DB.GetCollection(ctx, "service231_db", "service231_data")
	if err != nil {
		return Service231Data{}, err
	}
	service231Data = Service231Data{
		ID:   id231,
		DataOtherOtherTwo: datatwo231,
	}
	if err := coll.InsertOne(ctx, service231Data); err != nil {
		return Service231Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service232.MethodOtherOther232(ctx, id231, data231, datatwo231); err != nil {
		return Service231Data{}, err
	}

	return service231Data, nil
}
