// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service414Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service414 interface {
	Method414(ctx context.Context, id string, data string, datatwo string) (Service414Data, error)
	MethodOther414(ctx context.Context, id string, data string, datatwo string) (Service414Data, error)
	MethodOtherOther414(ctx context.Context, id string, data string, datatwo string) (Service414Data, error)
}

type Service414Impl struct {
	service414DB backend.NoSQLDatabase
	service415 Service415
}

func NewService414Impl(ctx context.Context, service414DB backend.NoSQLDatabase, service415 Service415) (Service414, error) {
	return &Service414Impl{
		service414DB: service414DB,
		service415: service415,
	}, nil
}

func (s *Service414Impl) Method414(ctx context.Context, id414 string, data414 string, datatwo414 string) (Service414Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service414DB.GetCollection(ctx, "service414_db", "service414_data")
	if err != nil {
		return Service414Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id414},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service414Data{}, err
	}
	var service414Data Service414Data
	exists, err := res.One(ctx, &service414Data)
	if err != nil {
		return Service414Data{}, err
	}
	if exists {
		return service414Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service414DB.GetCollection(ctx, "service414_db", "service414_data")
	if err != nil {
		return Service414Data{}, err
	}
	service414Data = Service414Data{
		ID:   id414,
		Data: data414,
	}
	if err := coll.InsertOne(ctx, service414Data); err != nil {
		return Service414Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service414DB.GetCollection(ctx, "service414_db", "service414_data")
	if err != nil {
		return Service414Data{}, err
	}
	service414Data = Service414Data{
		ID:   id414,
		DataTwo: datatwo414,
	}
	if err := coll.InsertOne(ctx, service414Data); err != nil {
		return Service414Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service415.Method415(ctx, id414, data414, datatwo414); err != nil {
		return Service414Data{}, err
	}

	return service414Data, nil
}

func (s *Service414Impl) MethodOther414(ctx context.Context, id414 string, data414 string, datatwo414 string) (Service414Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service414DB.GetCollection(ctx, "service414_db", "service414_data")
	if err != nil {
		return Service414Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id414},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service414Data{}, err
	}
	var service414Data Service414Data
	exists, err := res.One(ctx, &service414Data)
	if err != nil {
		return Service414Data{}, err
	}
	if exists {
		return service414Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service414DB.GetCollection(ctx, "service414_db", "service414_data")
	if err != nil {
		return Service414Data{}, err
	}
	service414Data = Service414Data{
		ID:   id414,
		DataOther: data414,
	}
	if err := coll.InsertOne(ctx, service414Data); err != nil {
		return Service414Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service414DB.GetCollection(ctx, "service414_db", "service414_data")
	if err != nil {
		return Service414Data{}, err
	}
	service414Data = Service414Data{
		ID:   id414,
		DataOtherTwo: datatwo414,
	}
	if err := coll.InsertOne(ctx, service414Data); err != nil {
		return Service414Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service415.MethodOther415(ctx, id414, data414, datatwo414); err != nil {
		return Service414Data{}, err
	}

	return service414Data, nil
}

func (s *Service414Impl) MethodOtherOther414(ctx context.Context, id414 string, data414 string, datatwo414 string) (Service414Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service414DB.GetCollection(ctx, "service414_db", "service414_data")
	if err != nil {
		return Service414Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id414},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service414Data{}, err
	}
	var service414Data Service414Data
	exists, err := res.One(ctx, &service414Data)
	if err != nil {
		return Service414Data{}, err
	}
	if exists {
		return service414Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service414DB.GetCollection(ctx, "service414_db", "service414_data")
	if err != nil {
		return Service414Data{}, err
	}
	service414Data = Service414Data{
		ID:   id414,
		DataOtherOther: data414,
	}
	if err := coll.InsertOne(ctx, service414Data); err != nil {
		return Service414Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service414DB.GetCollection(ctx, "service414_db", "service414_data")
	if err != nil {
		return Service414Data{}, err
	}
	service414Data = Service414Data{
		ID:   id414,
		DataOtherOtherTwo: datatwo414,
	}
	if err := coll.InsertOne(ctx, service414Data); err != nil {
		return Service414Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service415.MethodOtherOther415(ctx, id414, data414, datatwo414); err != nil {
		return Service414Data{}, err
	}

	return service414Data, nil
}
