// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service294Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service294 interface {
	Method294(ctx context.Context, id string, data string, datatwo string) (Service294Data, error)
	MethodOther294(ctx context.Context, id string, data string, datatwo string) (Service294Data, error)
	MethodOtherOther294(ctx context.Context, id string, data string, datatwo string) (Service294Data, error)
}

type Service294Impl struct {
	service294DB backend.NoSQLDatabase
	service295 Service295
}

func NewService294Impl(ctx context.Context, service294DB backend.NoSQLDatabase, service295 Service295) (Service294, error) {
	return &Service294Impl{
		service294DB: service294DB,
		service295: service295,
	}, nil
}

func (s *Service294Impl) Method294(ctx context.Context, id294 string, data294 string, datatwo294 string) (Service294Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service294DB.GetCollection(ctx, "service294_db", "service294_data")
	if err != nil {
		return Service294Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id294},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service294Data{}, err
	}
	var service294Data Service294Data
	exists, err := res.One(ctx, &service294Data)
	if err != nil {
		return Service294Data{}, err
	}
	if exists {
		return service294Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service294DB.GetCollection(ctx, "service294_db", "service294_data")
	if err != nil {
		return Service294Data{}, err
	}
	service294Data = Service294Data{
		ID:   id294,
		Data: data294,
	}
	if err := coll.InsertOne(ctx, service294Data); err != nil {
		return Service294Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service294DB.GetCollection(ctx, "service294_db", "service294_data")
	if err != nil {
		return Service294Data{}, err
	}
	service294Data = Service294Data{
		ID:   id294,
		DataTwo: datatwo294,
	}
	if err := coll.InsertOne(ctx, service294Data); err != nil {
		return Service294Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service295.Method295(ctx, id294, data294, datatwo294); err != nil {
		return Service294Data{}, err
	}

	return service294Data, nil
}

func (s *Service294Impl) MethodOther294(ctx context.Context, id294 string, data294 string, datatwo294 string) (Service294Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service294DB.GetCollection(ctx, "service294_db", "service294_data")
	if err != nil {
		return Service294Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id294},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service294Data{}, err
	}
	var service294Data Service294Data
	exists, err := res.One(ctx, &service294Data)
	if err != nil {
		return Service294Data{}, err
	}
	if exists {
		return service294Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service294DB.GetCollection(ctx, "service294_db", "service294_data")
	if err != nil {
		return Service294Data{}, err
	}
	service294Data = Service294Data{
		ID:   id294,
		DataOther: data294,
	}
	if err := coll.InsertOne(ctx, service294Data); err != nil {
		return Service294Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service294DB.GetCollection(ctx, "service294_db", "service294_data")
	if err != nil {
		return Service294Data{}, err
	}
	service294Data = Service294Data{
		ID:   id294,
		DataOtherTwo: datatwo294,
	}
	if err := coll.InsertOne(ctx, service294Data); err != nil {
		return Service294Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service295.MethodOther295(ctx, id294, data294, datatwo294); err != nil {
		return Service294Data{}, err
	}

	return service294Data, nil
}

func (s *Service294Impl) MethodOtherOther294(ctx context.Context, id294 string, data294 string, datatwo294 string) (Service294Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service294DB.GetCollection(ctx, "service294_db", "service294_data")
	if err != nil {
		return Service294Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id294},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service294Data{}, err
	}
	var service294Data Service294Data
	exists, err := res.One(ctx, &service294Data)
	if err != nil {
		return Service294Data{}, err
	}
	if exists {
		return service294Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service294DB.GetCollection(ctx, "service294_db", "service294_data")
	if err != nil {
		return Service294Data{}, err
	}
	service294Data = Service294Data{
		ID:   id294,
		DataOtherOther: data294,
	}
	if err := coll.InsertOne(ctx, service294Data); err != nil {
		return Service294Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service294DB.GetCollection(ctx, "service294_db", "service294_data")
	if err != nil {
		return Service294Data{}, err
	}
	service294Data = Service294Data{
		ID:   id294,
		DataOtherOtherTwo: datatwo294,
	}
	if err := coll.InsertOne(ctx, service294Data); err != nil {
		return Service294Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service295.MethodOtherOther295(ctx, id294, data294, datatwo294); err != nil {
		return Service294Data{}, err
	}

	return service294Data, nil
}
