// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service472Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service472 interface {
	Method472(ctx context.Context, id string, data string, datatwo string) (Service472Data, error)
	MethodOther472(ctx context.Context, id string, data string, datatwo string) (Service472Data, error)
	MethodOtherOther472(ctx context.Context, id string, data string, datatwo string) (Service472Data, error)
}

type Service472Impl struct {
	service472DB backend.NoSQLDatabase
	service473 Service473
}

func NewService472Impl(ctx context.Context, service472DB backend.NoSQLDatabase, service473 Service473) (Service472, error) {
	return &Service472Impl{
		service472DB: service472DB,
		service473: service473,
	}, nil
}

func (s *Service472Impl) Method472(ctx context.Context, id472 string, data472 string, datatwo472 string) (Service472Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service472DB.GetCollection(ctx, "service472_db", "service472_data")
	if err != nil {
		return Service472Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id472},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service472Data{}, err
	}
	var service472Data Service472Data
	exists, err := res.One(ctx, &service472Data)
	if err != nil {
		return Service472Data{}, err
	}
	if exists {
		return service472Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service472DB.GetCollection(ctx, "service472_db", "service472_data")
	if err != nil {
		return Service472Data{}, err
	}
	service472Data = Service472Data{
		ID:   id472,
		Data: data472,
	}
	if err := coll.InsertOne(ctx, service472Data); err != nil {
		return Service472Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service472DB.GetCollection(ctx, "service472_db", "service472_data")
	if err != nil {
		return Service472Data{}, err
	}
	service472Data = Service472Data{
		ID:   id472,
		DataTwo: datatwo472,
	}
	if err := coll.InsertOne(ctx, service472Data); err != nil {
		return Service472Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service473.Method473(ctx, id472, data472, datatwo472); err != nil {
		return Service472Data{}, err
	}

	return service472Data, nil
}

func (s *Service472Impl) MethodOther472(ctx context.Context, id472 string, data472 string, datatwo472 string) (Service472Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service472DB.GetCollection(ctx, "service472_db", "service472_data")
	if err != nil {
		return Service472Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id472},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service472Data{}, err
	}
	var service472Data Service472Data
	exists, err := res.One(ctx, &service472Data)
	if err != nil {
		return Service472Data{}, err
	}
	if exists {
		return service472Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service472DB.GetCollection(ctx, "service472_db", "service472_data")
	if err != nil {
		return Service472Data{}, err
	}
	service472Data = Service472Data{
		ID:   id472,
		DataOther: data472,
	}
	if err := coll.InsertOne(ctx, service472Data); err != nil {
		return Service472Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service472DB.GetCollection(ctx, "service472_db", "service472_data")
	if err != nil {
		return Service472Data{}, err
	}
	service472Data = Service472Data{
		ID:   id472,
		DataOtherTwo: datatwo472,
	}
	if err := coll.InsertOne(ctx, service472Data); err != nil {
		return Service472Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service473.MethodOther473(ctx, id472, data472, datatwo472); err != nil {
		return Service472Data{}, err
	}

	return service472Data, nil
}

func (s *Service472Impl) MethodOtherOther472(ctx context.Context, id472 string, data472 string, datatwo472 string) (Service472Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service472DB.GetCollection(ctx, "service472_db", "service472_data")
	if err != nil {
		return Service472Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id472},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service472Data{}, err
	}
	var service472Data Service472Data
	exists, err := res.One(ctx, &service472Data)
	if err != nil {
		return Service472Data{}, err
	}
	if exists {
		return service472Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service472DB.GetCollection(ctx, "service472_db", "service472_data")
	if err != nil {
		return Service472Data{}, err
	}
	service472Data = Service472Data{
		ID:   id472,
		DataOtherOther: data472,
	}
	if err := coll.InsertOne(ctx, service472Data); err != nil {
		return Service472Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service472DB.GetCollection(ctx, "service472_db", "service472_data")
	if err != nil {
		return Service472Data{}, err
	}
	service472Data = Service472Data{
		ID:   id472,
		DataOtherOtherTwo: datatwo472,
	}
	if err := coll.InsertOne(ctx, service472Data); err != nil {
		return Service472Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service473.MethodOtherOther473(ctx, id472, data472, datatwo472); err != nil {
		return Service472Data{}, err
	}

	return service472Data, nil
}
