// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service100Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service100 interface {
	Method100(ctx context.Context, id string, data string, datatwo string) (Service100Data, error)
	MethodOther100(ctx context.Context, id string, data string, datatwo string) (Service100Data, error)
	MethodOtherOther100(ctx context.Context, id string, data string, datatwo string) (Service100Data, error)
}

type Service100Impl struct {
	service100DB backend.NoSQLDatabase
	service101 Service101
}

func NewService100Impl(ctx context.Context, service100DB backend.NoSQLDatabase, service101 Service101) (Service100, error) {
	return &Service100Impl{
		service100DB: service100DB,
		service101: service101,
	}, nil
}

func (s *Service100Impl) Method100(ctx context.Context, id100 string, data100 string, datatwo100 string) (Service100Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service100DB.GetCollection(ctx, "service100_db", "service100_data")
	if err != nil {
		return Service100Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id100},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service100Data{}, err
	}
	var service100Data Service100Data
	exists, err := res.One(ctx, &service100Data)
	if err != nil {
		return Service100Data{}, err
	}
	if exists {
		return service100Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service100DB.GetCollection(ctx, "service100_db", "service100_data")
	if err != nil {
		return Service100Data{}, err
	}
	service100Data = Service100Data{
		ID:   id100,
		Data: data100,
	}
	if err := coll.InsertOne(ctx, service100Data); err != nil {
		return Service100Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service100DB.GetCollection(ctx, "service100_db", "service100_data")
	if err != nil {
		return Service100Data{}, err
	}
	service100Data = Service100Data{
		ID:   id100,
		DataTwo: datatwo100,
	}
	if err := coll.InsertOne(ctx, service100Data); err != nil {
		return Service100Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service101.Method101(ctx, id100, data100, datatwo100); err != nil {
		return Service100Data{}, err
	}

	return service100Data, nil
}

func (s *Service100Impl) MethodOther100(ctx context.Context, id100 string, data100 string, datatwo100 string) (Service100Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service100DB.GetCollection(ctx, "service100_db", "service100_data")
	if err != nil {
		return Service100Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id100},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service100Data{}, err
	}
	var service100Data Service100Data
	exists, err := res.One(ctx, &service100Data)
	if err != nil {
		return Service100Data{}, err
	}
	if exists {
		return service100Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service100DB.GetCollection(ctx, "service100_db", "service100_data")
	if err != nil {
		return Service100Data{}, err
	}
	service100Data = Service100Data{
		ID:   id100,
		DataOther: data100,
	}
	if err := coll.InsertOne(ctx, service100Data); err != nil {
		return Service100Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service100DB.GetCollection(ctx, "service100_db", "service100_data")
	if err != nil {
		return Service100Data{}, err
	}
	service100Data = Service100Data{
		ID:   id100,
		DataOtherTwo: datatwo100,
	}
	if err := coll.InsertOne(ctx, service100Data); err != nil {
		return Service100Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service101.MethodOther101(ctx, id100, data100, datatwo100); err != nil {
		return Service100Data{}, err
	}

	return service100Data, nil
}

func (s *Service100Impl) MethodOtherOther100(ctx context.Context, id100 string, data100 string, datatwo100 string) (Service100Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service100DB.GetCollection(ctx, "service100_db", "service100_data")
	if err != nil {
		return Service100Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id100},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service100Data{}, err
	}
	var service100Data Service100Data
	exists, err := res.One(ctx, &service100Data)
	if err != nil {
		return Service100Data{}, err
	}
	if exists {
		return service100Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service100DB.GetCollection(ctx, "service100_db", "service100_data")
	if err != nil {
		return Service100Data{}, err
	}
	service100Data = Service100Data{
		ID:   id100,
		DataOtherOther: data100,
	}
	if err := coll.InsertOne(ctx, service100Data); err != nil {
		return Service100Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service100DB.GetCollection(ctx, "service100_db", "service100_data")
	if err != nil {
		return Service100Data{}, err
	}
	service100Data = Service100Data{
		ID:   id100,
		DataOtherOtherTwo: datatwo100,
	}
	if err := coll.InsertOne(ctx, service100Data); err != nil {
		return Service100Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service101.MethodOtherOther101(ctx, id100, data100, datatwo100); err != nil {
		return Service100Data{}, err
	}

	return service100Data, nil
}
