// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service464Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service464 interface {
	Method464(ctx context.Context, id string, data string, datatwo string) (Service464Data, error)
	MethodOther464(ctx context.Context, id string, data string, datatwo string) (Service464Data, error)
	MethodOtherOther464(ctx context.Context, id string, data string, datatwo string) (Service464Data, error)
}

type Service464Impl struct {
	service464DB backend.NoSQLDatabase
	service465 Service465
}

func NewService464Impl(ctx context.Context, service464DB backend.NoSQLDatabase, service465 Service465) (Service464, error) {
	return &Service464Impl{
		service464DB: service464DB,
		service465: service465,
	}, nil
}

func (s *Service464Impl) Method464(ctx context.Context, id464 string, data464 string, datatwo464 string) (Service464Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service464DB.GetCollection(ctx, "service464_db", "service464_data")
	if err != nil {
		return Service464Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id464},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service464Data{}, err
	}
	var service464Data Service464Data
	exists, err := res.One(ctx, &service464Data)
	if err != nil {
		return Service464Data{}, err
	}
	if exists {
		return service464Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service464DB.GetCollection(ctx, "service464_db", "service464_data")
	if err != nil {
		return Service464Data{}, err
	}
	service464Data = Service464Data{
		ID:   id464,
		Data: data464,
	}
	if err := coll.InsertOne(ctx, service464Data); err != nil {
		return Service464Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service464DB.GetCollection(ctx, "service464_db", "service464_data")
	if err != nil {
		return Service464Data{}, err
	}
	service464Data = Service464Data{
		ID:   id464,
		DataTwo: datatwo464,
	}
	if err := coll.InsertOne(ctx, service464Data); err != nil {
		return Service464Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service465.Method465(ctx, id464, data464, datatwo464); err != nil {
		return Service464Data{}, err
	}

	return service464Data, nil
}

func (s *Service464Impl) MethodOther464(ctx context.Context, id464 string, data464 string, datatwo464 string) (Service464Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service464DB.GetCollection(ctx, "service464_db", "service464_data")
	if err != nil {
		return Service464Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id464},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service464Data{}, err
	}
	var service464Data Service464Data
	exists, err := res.One(ctx, &service464Data)
	if err != nil {
		return Service464Data{}, err
	}
	if exists {
		return service464Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service464DB.GetCollection(ctx, "service464_db", "service464_data")
	if err != nil {
		return Service464Data{}, err
	}
	service464Data = Service464Data{
		ID:   id464,
		DataOther: data464,
	}
	if err := coll.InsertOne(ctx, service464Data); err != nil {
		return Service464Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service464DB.GetCollection(ctx, "service464_db", "service464_data")
	if err != nil {
		return Service464Data{}, err
	}
	service464Data = Service464Data{
		ID:   id464,
		DataOtherTwo: datatwo464,
	}
	if err := coll.InsertOne(ctx, service464Data); err != nil {
		return Service464Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service465.MethodOther465(ctx, id464, data464, datatwo464); err != nil {
		return Service464Data{}, err
	}

	return service464Data, nil
}

func (s *Service464Impl) MethodOtherOther464(ctx context.Context, id464 string, data464 string, datatwo464 string) (Service464Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service464DB.GetCollection(ctx, "service464_db", "service464_data")
	if err != nil {
		return Service464Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id464},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service464Data{}, err
	}
	var service464Data Service464Data
	exists, err := res.One(ctx, &service464Data)
	if err != nil {
		return Service464Data{}, err
	}
	if exists {
		return service464Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service464DB.GetCollection(ctx, "service464_db", "service464_data")
	if err != nil {
		return Service464Data{}, err
	}
	service464Data = Service464Data{
		ID:   id464,
		DataOtherOther: data464,
	}
	if err := coll.InsertOne(ctx, service464Data); err != nil {
		return Service464Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service464DB.GetCollection(ctx, "service464_db", "service464_data")
	if err != nil {
		return Service464Data{}, err
	}
	service464Data = Service464Data{
		ID:   id464,
		DataOtherOtherTwo: datatwo464,
	}
	if err := coll.InsertOne(ctx, service464Data); err != nil {
		return Service464Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service465.MethodOtherOther465(ctx, id464, data464, datatwo464); err != nil {
		return Service464Data{}, err
	}

	return service464Data, nil
}
