// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service443Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service443 interface {
	Method443(ctx context.Context, id string, data string, datatwo string) (Service443Data, error)
	MethodOther443(ctx context.Context, id string, data string, datatwo string) (Service443Data, error)
	MethodOtherOther443(ctx context.Context, id string, data string, datatwo string) (Service443Data, error)
}

type Service443Impl struct {
	service443DB backend.NoSQLDatabase
	service444 Service444
}

func NewService443Impl(ctx context.Context, service443DB backend.NoSQLDatabase, service444 Service444) (Service443, error) {
	return &Service443Impl{
		service443DB: service443DB,
		service444: service444,
	}, nil
}

func (s *Service443Impl) Method443(ctx context.Context, id443 string, data443 string, datatwo443 string) (Service443Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service443DB.GetCollection(ctx, "service443_db", "service443_data")
	if err != nil {
		return Service443Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id443},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service443Data{}, err
	}
	var service443Data Service443Data
	exists, err := res.One(ctx, &service443Data)
	if err != nil {
		return Service443Data{}, err
	}
	if exists {
		return service443Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service443DB.GetCollection(ctx, "service443_db", "service443_data")
	if err != nil {
		return Service443Data{}, err
	}
	service443Data = Service443Data{
		ID:   id443,
		Data: data443,
	}
	if err := coll.InsertOne(ctx, service443Data); err != nil {
		return Service443Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service443DB.GetCollection(ctx, "service443_db", "service443_data")
	if err != nil {
		return Service443Data{}, err
	}
	service443Data = Service443Data{
		ID:   id443,
		DataTwo: datatwo443,
	}
	if err := coll.InsertOne(ctx, service443Data); err != nil {
		return Service443Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service444.Method444(ctx, id443, data443, datatwo443); err != nil {
		return Service443Data{}, err
	}

	return service443Data, nil
}

func (s *Service443Impl) MethodOther443(ctx context.Context, id443 string, data443 string, datatwo443 string) (Service443Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service443DB.GetCollection(ctx, "service443_db", "service443_data")
	if err != nil {
		return Service443Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id443},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service443Data{}, err
	}
	var service443Data Service443Data
	exists, err := res.One(ctx, &service443Data)
	if err != nil {
		return Service443Data{}, err
	}
	if exists {
		return service443Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service443DB.GetCollection(ctx, "service443_db", "service443_data")
	if err != nil {
		return Service443Data{}, err
	}
	service443Data = Service443Data{
		ID:   id443,
		DataOther: data443,
	}
	if err := coll.InsertOne(ctx, service443Data); err != nil {
		return Service443Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service443DB.GetCollection(ctx, "service443_db", "service443_data")
	if err != nil {
		return Service443Data{}, err
	}
	service443Data = Service443Data{
		ID:   id443,
		DataOtherTwo: datatwo443,
	}
	if err := coll.InsertOne(ctx, service443Data); err != nil {
		return Service443Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service444.MethodOther444(ctx, id443, data443, datatwo443); err != nil {
		return Service443Data{}, err
	}

	return service443Data, nil
}

func (s *Service443Impl) MethodOtherOther443(ctx context.Context, id443 string, data443 string, datatwo443 string) (Service443Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service443DB.GetCollection(ctx, "service443_db", "service443_data")
	if err != nil {
		return Service443Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id443},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service443Data{}, err
	}
	var service443Data Service443Data
	exists, err := res.One(ctx, &service443Data)
	if err != nil {
		return Service443Data{}, err
	}
	if exists {
		return service443Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service443DB.GetCollection(ctx, "service443_db", "service443_data")
	if err != nil {
		return Service443Data{}, err
	}
	service443Data = Service443Data{
		ID:   id443,
		DataOtherOther: data443,
	}
	if err := coll.InsertOne(ctx, service443Data); err != nil {
		return Service443Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service443DB.GetCollection(ctx, "service443_db", "service443_data")
	if err != nil {
		return Service443Data{}, err
	}
	service443Data = Service443Data{
		ID:   id443,
		DataOtherOtherTwo: datatwo443,
	}
	if err := coll.InsertOne(ctx, service443Data); err != nil {
		return Service443Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service444.MethodOtherOther444(ctx, id443, data443, datatwo443); err != nil {
		return Service443Data{}, err
	}

	return service443Data, nil
}
