// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service71Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service71 interface {
	Method71(ctx context.Context, id string, data string, datatwo string) (Service71Data, error)
	MethodOther71(ctx context.Context, id string, data string, datatwo string) (Service71Data, error)
	MethodOtherOther71(ctx context.Context, id string, data string, datatwo string) (Service71Data, error)
}

type Service71Impl struct {
	service71DB backend.NoSQLDatabase
	service72 Service72
}

func NewService71Impl(ctx context.Context, service71DB backend.NoSQLDatabase, service72 Service72) (Service71, error) {
	return &Service71Impl{
		service71DB: service71DB,
		service72: service72,
	}, nil
}

func (s *Service71Impl) Method71(ctx context.Context, id71 string, data71 string, datatwo71 string) (Service71Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service71DB.GetCollection(ctx, "service71_db", "service71_data")
	if err != nil {
		return Service71Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id71},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service71Data{}, err
	}
	var service71Data Service71Data
	exists, err := res.One(ctx, &service71Data)
	if err != nil {
		return Service71Data{}, err
	}
	if exists {
		return service71Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service71DB.GetCollection(ctx, "service71_db", "service71_data")
	if err != nil {
		return Service71Data{}, err
	}
	service71Data = Service71Data{
		ID:   id71,
		Data: data71,
	}
	if err := coll.InsertOne(ctx, service71Data); err != nil {
		return Service71Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service71DB.GetCollection(ctx, "service71_db", "service71_data")
	if err != nil {
		return Service71Data{}, err
	}
	service71Data = Service71Data{
		ID:   id71,
		DataTwo: datatwo71,
	}
	if err := coll.InsertOne(ctx, service71Data); err != nil {
		return Service71Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service72.Method72(ctx, id71, data71, datatwo71); err != nil {
		return Service71Data{}, err
	}

	return service71Data, nil
}

func (s *Service71Impl) MethodOther71(ctx context.Context, id71 string, data71 string, datatwo71 string) (Service71Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service71DB.GetCollection(ctx, "service71_db", "service71_data")
	if err != nil {
		return Service71Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id71},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service71Data{}, err
	}
	var service71Data Service71Data
	exists, err := res.One(ctx, &service71Data)
	if err != nil {
		return Service71Data{}, err
	}
	if exists {
		return service71Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service71DB.GetCollection(ctx, "service71_db", "service71_data")
	if err != nil {
		return Service71Data{}, err
	}
	service71Data = Service71Data{
		ID:   id71,
		DataOther: data71,
	}
	if err := coll.InsertOne(ctx, service71Data); err != nil {
		return Service71Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service71DB.GetCollection(ctx, "service71_db", "service71_data")
	if err != nil {
		return Service71Data{}, err
	}
	service71Data = Service71Data{
		ID:   id71,
		DataOtherTwo: datatwo71,
	}
	if err := coll.InsertOne(ctx, service71Data); err != nil {
		return Service71Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service72.MethodOther72(ctx, id71, data71, datatwo71); err != nil {
		return Service71Data{}, err
	}

	return service71Data, nil
}

func (s *Service71Impl) MethodOtherOther71(ctx context.Context, id71 string, data71 string, datatwo71 string) (Service71Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service71DB.GetCollection(ctx, "service71_db", "service71_data")
	if err != nil {
		return Service71Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id71},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service71Data{}, err
	}
	var service71Data Service71Data
	exists, err := res.One(ctx, &service71Data)
	if err != nil {
		return Service71Data{}, err
	}
	if exists {
		return service71Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service71DB.GetCollection(ctx, "service71_db", "service71_data")
	if err != nil {
		return Service71Data{}, err
	}
	service71Data = Service71Data{
		ID:   id71,
		DataOtherOther: data71,
	}
	if err := coll.InsertOne(ctx, service71Data); err != nil {
		return Service71Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service71DB.GetCollection(ctx, "service71_db", "service71_data")
	if err != nil {
		return Service71Data{}, err
	}
	service71Data = Service71Data{
		ID:   id71,
		DataOtherOtherTwo: datatwo71,
	}
	if err := coll.InsertOne(ctx, service71Data); err != nil {
		return Service71Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service72.MethodOtherOther72(ctx, id71, data71, datatwo71); err != nil {
		return Service71Data{}, err
	}

	return service71Data, nil
}
