// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service395Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service395 interface {
	Method395(ctx context.Context, id string, data string, datatwo string) (Service395Data, error)
	MethodOther395(ctx context.Context, id string, data string, datatwo string) (Service395Data, error)
	MethodOtherOther395(ctx context.Context, id string, data string, datatwo string) (Service395Data, error)
}

type Service395Impl struct {
	service395DB backend.NoSQLDatabase
	service396 Service396
}

func NewService395Impl(ctx context.Context, service395DB backend.NoSQLDatabase, service396 Service396) (Service395, error) {
	return &Service395Impl{
		service395DB: service395DB,
		service396: service396,
	}, nil
}

func (s *Service395Impl) Method395(ctx context.Context, id395 string, data395 string, datatwo395 string) (Service395Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service395DB.GetCollection(ctx, "service395_db", "service395_data")
	if err != nil {
		return Service395Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id395},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service395Data{}, err
	}
	var service395Data Service395Data
	exists, err := res.One(ctx, &service395Data)
	if err != nil {
		return Service395Data{}, err
	}
	if exists {
		return service395Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service395DB.GetCollection(ctx, "service395_db", "service395_data")
	if err != nil {
		return Service395Data{}, err
	}
	service395Data = Service395Data{
		ID:   id395,
		Data: data395,
	}
	if err := coll.InsertOne(ctx, service395Data); err != nil {
		return Service395Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service395DB.GetCollection(ctx, "service395_db", "service395_data")
	if err != nil {
		return Service395Data{}, err
	}
	service395Data = Service395Data{
		ID:   id395,
		DataTwo: datatwo395,
	}
	if err := coll.InsertOne(ctx, service395Data); err != nil {
		return Service395Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service396.Method396(ctx, id395, data395, datatwo395); err != nil {
		return Service395Data{}, err
	}

	return service395Data, nil
}

func (s *Service395Impl) MethodOther395(ctx context.Context, id395 string, data395 string, datatwo395 string) (Service395Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service395DB.GetCollection(ctx, "service395_db", "service395_data")
	if err != nil {
		return Service395Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id395},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service395Data{}, err
	}
	var service395Data Service395Data
	exists, err := res.One(ctx, &service395Data)
	if err != nil {
		return Service395Data{}, err
	}
	if exists {
		return service395Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service395DB.GetCollection(ctx, "service395_db", "service395_data")
	if err != nil {
		return Service395Data{}, err
	}
	service395Data = Service395Data{
		ID:   id395,
		DataOther: data395,
	}
	if err := coll.InsertOne(ctx, service395Data); err != nil {
		return Service395Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service395DB.GetCollection(ctx, "service395_db", "service395_data")
	if err != nil {
		return Service395Data{}, err
	}
	service395Data = Service395Data{
		ID:   id395,
		DataOtherTwo: datatwo395,
	}
	if err := coll.InsertOne(ctx, service395Data); err != nil {
		return Service395Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service396.MethodOther396(ctx, id395, data395, datatwo395); err != nil {
		return Service395Data{}, err
	}

	return service395Data, nil
}

func (s *Service395Impl) MethodOtherOther395(ctx context.Context, id395 string, data395 string, datatwo395 string) (Service395Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service395DB.GetCollection(ctx, "service395_db", "service395_data")
	if err != nil {
		return Service395Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id395},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service395Data{}, err
	}
	var service395Data Service395Data
	exists, err := res.One(ctx, &service395Data)
	if err != nil {
		return Service395Data{}, err
	}
	if exists {
		return service395Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service395DB.GetCollection(ctx, "service395_db", "service395_data")
	if err != nil {
		return Service395Data{}, err
	}
	service395Data = Service395Data{
		ID:   id395,
		DataOtherOther: data395,
	}
	if err := coll.InsertOne(ctx, service395Data); err != nil {
		return Service395Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service395DB.GetCollection(ctx, "service395_db", "service395_data")
	if err != nil {
		return Service395Data{}, err
	}
	service395Data = Service395Data{
		ID:   id395,
		DataOtherOtherTwo: datatwo395,
	}
	if err := coll.InsertOne(ctx, service395Data); err != nil {
		return Service395Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service396.MethodOtherOther396(ctx, id395, data395, datatwo395); err != nil {
		return Service395Data{}, err
	}

	return service395Data, nil
}
