// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service207Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service207 interface {
	Method207(ctx context.Context, id string, data string, datatwo string) (Service207Data, error)
	MethodOther207(ctx context.Context, id string, data string, datatwo string) (Service207Data, error)
	MethodOtherOther207(ctx context.Context, id string, data string, datatwo string) (Service207Data, error)
}

type Service207Impl struct {
	service207DB backend.NoSQLDatabase
	service208 Service208
}

func NewService207Impl(ctx context.Context, service207DB backend.NoSQLDatabase, service208 Service208) (Service207, error) {
	return &Service207Impl{
		service207DB: service207DB,
		service208: service208,
	}, nil
}

func (s *Service207Impl) Method207(ctx context.Context, id207 string, data207 string, datatwo207 string) (Service207Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service207DB.GetCollection(ctx, "service207_db", "service207_data")
	if err != nil {
		return Service207Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id207},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service207Data{}, err
	}
	var service207Data Service207Data
	exists, err := res.One(ctx, &service207Data)
	if err != nil {
		return Service207Data{}, err
	}
	if exists {
		return service207Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service207DB.GetCollection(ctx, "service207_db", "service207_data")
	if err != nil {
		return Service207Data{}, err
	}
	service207Data = Service207Data{
		ID:   id207,
		Data: data207,
	}
	if err := coll.InsertOne(ctx, service207Data); err != nil {
		return Service207Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service207DB.GetCollection(ctx, "service207_db", "service207_data")
	if err != nil {
		return Service207Data{}, err
	}
	service207Data = Service207Data{
		ID:   id207,
		DataTwo: datatwo207,
	}
	if err := coll.InsertOne(ctx, service207Data); err != nil {
		return Service207Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service208.Method208(ctx, id207, data207, datatwo207); err != nil {
		return Service207Data{}, err
	}

	return service207Data, nil
}

func (s *Service207Impl) MethodOther207(ctx context.Context, id207 string, data207 string, datatwo207 string) (Service207Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service207DB.GetCollection(ctx, "service207_db", "service207_data")
	if err != nil {
		return Service207Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id207},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service207Data{}, err
	}
	var service207Data Service207Data
	exists, err := res.One(ctx, &service207Data)
	if err != nil {
		return Service207Data{}, err
	}
	if exists {
		return service207Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service207DB.GetCollection(ctx, "service207_db", "service207_data")
	if err != nil {
		return Service207Data{}, err
	}
	service207Data = Service207Data{
		ID:   id207,
		DataOther: data207,
	}
	if err := coll.InsertOne(ctx, service207Data); err != nil {
		return Service207Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service207DB.GetCollection(ctx, "service207_db", "service207_data")
	if err != nil {
		return Service207Data{}, err
	}
	service207Data = Service207Data{
		ID:   id207,
		DataOtherTwo: datatwo207,
	}
	if err := coll.InsertOne(ctx, service207Data); err != nil {
		return Service207Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service208.MethodOther208(ctx, id207, data207, datatwo207); err != nil {
		return Service207Data{}, err
	}

	return service207Data, nil
}

func (s *Service207Impl) MethodOtherOther207(ctx context.Context, id207 string, data207 string, datatwo207 string) (Service207Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service207DB.GetCollection(ctx, "service207_db", "service207_data")
	if err != nil {
		return Service207Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id207},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service207Data{}, err
	}
	var service207Data Service207Data
	exists, err := res.One(ctx, &service207Data)
	if err != nil {
		return Service207Data{}, err
	}
	if exists {
		return service207Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service207DB.GetCollection(ctx, "service207_db", "service207_data")
	if err != nil {
		return Service207Data{}, err
	}
	service207Data = Service207Data{
		ID:   id207,
		DataOtherOther: data207,
	}
	if err := coll.InsertOne(ctx, service207Data); err != nil {
		return Service207Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service207DB.GetCollection(ctx, "service207_db", "service207_data")
	if err != nil {
		return Service207Data{}, err
	}
	service207Data = Service207Data{
		ID:   id207,
		DataOtherOtherTwo: datatwo207,
	}
	if err := coll.InsertOne(ctx, service207Data); err != nil {
		return Service207Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service208.MethodOtherOther208(ctx, id207, data207, datatwo207); err != nil {
		return Service207Data{}, err
	}

	return service207Data, nil
}
