// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service151Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service151 interface {
	Method151(ctx context.Context, id string, data string, datatwo string) (Service151Data, error)
	MethodOther151(ctx context.Context, id string, data string, datatwo string) (Service151Data, error)
	MethodOtherOther151(ctx context.Context, id string, data string, datatwo string) (Service151Data, error)
}

type Service151Impl struct {
	service151DB backend.NoSQLDatabase
	service152 Service152
}

func NewService151Impl(ctx context.Context, service151DB backend.NoSQLDatabase, service152 Service152) (Service151, error) {
	return &Service151Impl{
		service151DB: service151DB,
		service152: service152,
	}, nil
}

func (s *Service151Impl) Method151(ctx context.Context, id151 string, data151 string, datatwo151 string) (Service151Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service151DB.GetCollection(ctx, "service151_db", "service151_data")
	if err != nil {
		return Service151Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id151},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service151Data{}, err
	}
	var service151Data Service151Data
	exists, err := res.One(ctx, &service151Data)
	if err != nil {
		return Service151Data{}, err
	}
	if exists {
		return service151Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service151DB.GetCollection(ctx, "service151_db", "service151_data")
	if err != nil {
		return Service151Data{}, err
	}
	service151Data = Service151Data{
		ID:   id151,
		Data: data151,
	}
	if err := coll.InsertOne(ctx, service151Data); err != nil {
		return Service151Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service151DB.GetCollection(ctx, "service151_db", "service151_data")
	if err != nil {
		return Service151Data{}, err
	}
	service151Data = Service151Data{
		ID:   id151,
		DataTwo: datatwo151,
	}
	if err := coll.InsertOne(ctx, service151Data); err != nil {
		return Service151Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service152.Method152(ctx, id151, data151, datatwo151); err != nil {
		return Service151Data{}, err
	}

	return service151Data, nil
}

func (s *Service151Impl) MethodOther151(ctx context.Context, id151 string, data151 string, datatwo151 string) (Service151Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service151DB.GetCollection(ctx, "service151_db", "service151_data")
	if err != nil {
		return Service151Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id151},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service151Data{}, err
	}
	var service151Data Service151Data
	exists, err := res.One(ctx, &service151Data)
	if err != nil {
		return Service151Data{}, err
	}
	if exists {
		return service151Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service151DB.GetCollection(ctx, "service151_db", "service151_data")
	if err != nil {
		return Service151Data{}, err
	}
	service151Data = Service151Data{
		ID:   id151,
		DataOther: data151,
	}
	if err := coll.InsertOne(ctx, service151Data); err != nil {
		return Service151Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service151DB.GetCollection(ctx, "service151_db", "service151_data")
	if err != nil {
		return Service151Data{}, err
	}
	service151Data = Service151Data{
		ID:   id151,
		DataOtherTwo: datatwo151,
	}
	if err := coll.InsertOne(ctx, service151Data); err != nil {
		return Service151Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service152.MethodOther152(ctx, id151, data151, datatwo151); err != nil {
		return Service151Data{}, err
	}

	return service151Data, nil
}

func (s *Service151Impl) MethodOtherOther151(ctx context.Context, id151 string, data151 string, datatwo151 string) (Service151Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service151DB.GetCollection(ctx, "service151_db", "service151_data")
	if err != nil {
		return Service151Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id151},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service151Data{}, err
	}
	var service151Data Service151Data
	exists, err := res.One(ctx, &service151Data)
	if err != nil {
		return Service151Data{}, err
	}
	if exists {
		return service151Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service151DB.GetCollection(ctx, "service151_db", "service151_data")
	if err != nil {
		return Service151Data{}, err
	}
	service151Data = Service151Data{
		ID:   id151,
		DataOtherOther: data151,
	}
	if err := coll.InsertOne(ctx, service151Data); err != nil {
		return Service151Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service151DB.GetCollection(ctx, "service151_db", "service151_data")
	if err != nil {
		return Service151Data{}, err
	}
	service151Data = Service151Data{
		ID:   id151,
		DataOtherOtherTwo: datatwo151,
	}
	if err := coll.InsertOne(ctx, service151Data); err != nil {
		return Service151Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service152.MethodOtherOther152(ctx, id151, data151, datatwo151); err != nil {
		return Service151Data{}, err
	}

	return service151Data, nil
}
