// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service252Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service252 interface {
	Method252(ctx context.Context, id string, data string, datatwo string) (Service252Data, error)
	MethodOther252(ctx context.Context, id string, data string, datatwo string) (Service252Data, error)
	MethodOtherOther252(ctx context.Context, id string, data string, datatwo string) (Service252Data, error)
}

type Service252Impl struct {
	service252DB backend.NoSQLDatabase
	service253 Service253
}

func NewService252Impl(ctx context.Context, service252DB backend.NoSQLDatabase, service253 Service253) (Service252, error) {
	return &Service252Impl{
		service252DB: service252DB,
		service253: service253,
	}, nil
}

func (s *Service252Impl) Method252(ctx context.Context, id252 string, data252 string, datatwo252 string) (Service252Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service252DB.GetCollection(ctx, "service252_db", "service252_data")
	if err != nil {
		return Service252Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id252},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service252Data{}, err
	}
	var service252Data Service252Data
	exists, err := res.One(ctx, &service252Data)
	if err != nil {
		return Service252Data{}, err
	}
	if exists {
		return service252Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service252DB.GetCollection(ctx, "service252_db", "service252_data")
	if err != nil {
		return Service252Data{}, err
	}
	service252Data = Service252Data{
		ID:   id252,
		Data: data252,
	}
	if err := coll.InsertOne(ctx, service252Data); err != nil {
		return Service252Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service252DB.GetCollection(ctx, "service252_db", "service252_data")
	if err != nil {
		return Service252Data{}, err
	}
	service252Data = Service252Data{
		ID:   id252,
		DataTwo: datatwo252,
	}
	if err := coll.InsertOne(ctx, service252Data); err != nil {
		return Service252Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service253.Method253(ctx, id252, data252, datatwo252); err != nil {
		return Service252Data{}, err
	}

	return service252Data, nil
}

func (s *Service252Impl) MethodOther252(ctx context.Context, id252 string, data252 string, datatwo252 string) (Service252Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service252DB.GetCollection(ctx, "service252_db", "service252_data")
	if err != nil {
		return Service252Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id252},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service252Data{}, err
	}
	var service252Data Service252Data
	exists, err := res.One(ctx, &service252Data)
	if err != nil {
		return Service252Data{}, err
	}
	if exists {
		return service252Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service252DB.GetCollection(ctx, "service252_db", "service252_data")
	if err != nil {
		return Service252Data{}, err
	}
	service252Data = Service252Data{
		ID:   id252,
		DataOther: data252,
	}
	if err := coll.InsertOne(ctx, service252Data); err != nil {
		return Service252Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service252DB.GetCollection(ctx, "service252_db", "service252_data")
	if err != nil {
		return Service252Data{}, err
	}
	service252Data = Service252Data{
		ID:   id252,
		DataOtherTwo: datatwo252,
	}
	if err := coll.InsertOne(ctx, service252Data); err != nil {
		return Service252Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service253.MethodOther253(ctx, id252, data252, datatwo252); err != nil {
		return Service252Data{}, err
	}

	return service252Data, nil
}

func (s *Service252Impl) MethodOtherOther252(ctx context.Context, id252 string, data252 string, datatwo252 string) (Service252Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service252DB.GetCollection(ctx, "service252_db", "service252_data")
	if err != nil {
		return Service252Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id252},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service252Data{}, err
	}
	var service252Data Service252Data
	exists, err := res.One(ctx, &service252Data)
	if err != nil {
		return Service252Data{}, err
	}
	if exists {
		return service252Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service252DB.GetCollection(ctx, "service252_db", "service252_data")
	if err != nil {
		return Service252Data{}, err
	}
	service252Data = Service252Data{
		ID:   id252,
		DataOtherOther: data252,
	}
	if err := coll.InsertOne(ctx, service252Data); err != nil {
		return Service252Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service252DB.GetCollection(ctx, "service252_db", "service252_data")
	if err != nil {
		return Service252Data{}, err
	}
	service252Data = Service252Data{
		ID:   id252,
		DataOtherOtherTwo: datatwo252,
	}
	if err := coll.InsertOne(ctx, service252Data); err != nil {
		return Service252Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service253.MethodOtherOther253(ctx, id252, data252, datatwo252); err != nil {
		return Service252Data{}, err
	}

	return service252Data, nil
}
