// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service189Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service189 interface {
	Method189(ctx context.Context, id string, data string, datatwo string) (Service189Data, error)
	MethodOther189(ctx context.Context, id string, data string, datatwo string) (Service189Data, error)
	MethodOtherOther189(ctx context.Context, id string, data string, datatwo string) (Service189Data, error)
}

type Service189Impl struct {
	service189DB backend.NoSQLDatabase
	service190 Service190
}

func NewService189Impl(ctx context.Context, service189DB backend.NoSQLDatabase, service190 Service190) (Service189, error) {
	return &Service189Impl{
		service189DB: service189DB,
		service190: service190,
	}, nil
}

func (s *Service189Impl) Method189(ctx context.Context, id189 string, data189 string, datatwo189 string) (Service189Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service189DB.GetCollection(ctx, "service189_db", "service189_data")
	if err != nil {
		return Service189Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id189},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service189Data{}, err
	}
	var service189Data Service189Data
	exists, err := res.One(ctx, &service189Data)
	if err != nil {
		return Service189Data{}, err
	}
	if exists {
		return service189Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service189DB.GetCollection(ctx, "service189_db", "service189_data")
	if err != nil {
		return Service189Data{}, err
	}
	service189Data = Service189Data{
		ID:   id189,
		Data: data189,
	}
	if err := coll.InsertOne(ctx, service189Data); err != nil {
		return Service189Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service189DB.GetCollection(ctx, "service189_db", "service189_data")
	if err != nil {
		return Service189Data{}, err
	}
	service189Data = Service189Data{
		ID:   id189,
		DataTwo: datatwo189,
	}
	if err := coll.InsertOne(ctx, service189Data); err != nil {
		return Service189Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service190.Method190(ctx, id189, data189, datatwo189); err != nil {
		return Service189Data{}, err
	}

	return service189Data, nil
}

func (s *Service189Impl) MethodOther189(ctx context.Context, id189 string, data189 string, datatwo189 string) (Service189Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service189DB.GetCollection(ctx, "service189_db", "service189_data")
	if err != nil {
		return Service189Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id189},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service189Data{}, err
	}
	var service189Data Service189Data
	exists, err := res.One(ctx, &service189Data)
	if err != nil {
		return Service189Data{}, err
	}
	if exists {
		return service189Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service189DB.GetCollection(ctx, "service189_db", "service189_data")
	if err != nil {
		return Service189Data{}, err
	}
	service189Data = Service189Data{
		ID:   id189,
		DataOther: data189,
	}
	if err := coll.InsertOne(ctx, service189Data); err != nil {
		return Service189Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service189DB.GetCollection(ctx, "service189_db", "service189_data")
	if err != nil {
		return Service189Data{}, err
	}
	service189Data = Service189Data{
		ID:   id189,
		DataOtherTwo: datatwo189,
	}
	if err := coll.InsertOne(ctx, service189Data); err != nil {
		return Service189Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service190.MethodOther190(ctx, id189, data189, datatwo189); err != nil {
		return Service189Data{}, err
	}

	return service189Data, nil
}

func (s *Service189Impl) MethodOtherOther189(ctx context.Context, id189 string, data189 string, datatwo189 string) (Service189Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service189DB.GetCollection(ctx, "service189_db", "service189_data")
	if err != nil {
		return Service189Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id189},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service189Data{}, err
	}
	var service189Data Service189Data
	exists, err := res.One(ctx, &service189Data)
	if err != nil {
		return Service189Data{}, err
	}
	if exists {
		return service189Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service189DB.GetCollection(ctx, "service189_db", "service189_data")
	if err != nil {
		return Service189Data{}, err
	}
	service189Data = Service189Data{
		ID:   id189,
		DataOtherOther: data189,
	}
	if err := coll.InsertOne(ctx, service189Data); err != nil {
		return Service189Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service189DB.GetCollection(ctx, "service189_db", "service189_data")
	if err != nil {
		return Service189Data{}, err
	}
	service189Data = Service189Data{
		ID:   id189,
		DataOtherOtherTwo: datatwo189,
	}
	if err := coll.InsertOne(ctx, service189Data); err != nil {
		return Service189Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service190.MethodOtherOther190(ctx, id189, data189, datatwo189); err != nil {
		return Service189Data{}, err
	}

	return service189Data, nil
}
