// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service233Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service233 interface {
	Method233(ctx context.Context, id string, data string, datatwo string) (Service233Data, error)
	MethodOther233(ctx context.Context, id string, data string, datatwo string) (Service233Data, error)
	MethodOtherOther233(ctx context.Context, id string, data string, datatwo string) (Service233Data, error)
}

type Service233Impl struct {
	service233DB backend.NoSQLDatabase
	service234 Service234
}

func NewService233Impl(ctx context.Context, service233DB backend.NoSQLDatabase, service234 Service234) (Service233, error) {
	return &Service233Impl{
		service233DB: service233DB,
		service234: service234,
	}, nil
}

func (s *Service233Impl) Method233(ctx context.Context, id233 string, data233 string, datatwo233 string) (Service233Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service233DB.GetCollection(ctx, "service233_db", "service233_data")
	if err != nil {
		return Service233Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id233},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service233Data{}, err
	}
	var service233Data Service233Data
	exists, err := res.One(ctx, &service233Data)
	if err != nil {
		return Service233Data{}, err
	}
	if exists {
		return service233Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service233DB.GetCollection(ctx, "service233_db", "service233_data")
	if err != nil {
		return Service233Data{}, err
	}
	service233Data = Service233Data{
		ID:   id233,
		Data: data233,
	}
	if err := coll.InsertOne(ctx, service233Data); err != nil {
		return Service233Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service233DB.GetCollection(ctx, "service233_db", "service233_data")
	if err != nil {
		return Service233Data{}, err
	}
	service233Data = Service233Data{
		ID:   id233,
		DataTwo: datatwo233,
	}
	if err := coll.InsertOne(ctx, service233Data); err != nil {
		return Service233Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service234.Method234(ctx, id233, data233, datatwo233); err != nil {
		return Service233Data{}, err
	}

	return service233Data, nil
}

func (s *Service233Impl) MethodOther233(ctx context.Context, id233 string, data233 string, datatwo233 string) (Service233Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service233DB.GetCollection(ctx, "service233_db", "service233_data")
	if err != nil {
		return Service233Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id233},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service233Data{}, err
	}
	var service233Data Service233Data
	exists, err := res.One(ctx, &service233Data)
	if err != nil {
		return Service233Data{}, err
	}
	if exists {
		return service233Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service233DB.GetCollection(ctx, "service233_db", "service233_data")
	if err != nil {
		return Service233Data{}, err
	}
	service233Data = Service233Data{
		ID:   id233,
		DataOther: data233,
	}
	if err := coll.InsertOne(ctx, service233Data); err != nil {
		return Service233Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service233DB.GetCollection(ctx, "service233_db", "service233_data")
	if err != nil {
		return Service233Data{}, err
	}
	service233Data = Service233Data{
		ID:   id233,
		DataOtherTwo: datatwo233,
	}
	if err := coll.InsertOne(ctx, service233Data); err != nil {
		return Service233Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service234.MethodOther234(ctx, id233, data233, datatwo233); err != nil {
		return Service233Data{}, err
	}

	return service233Data, nil
}

func (s *Service233Impl) MethodOtherOther233(ctx context.Context, id233 string, data233 string, datatwo233 string) (Service233Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service233DB.GetCollection(ctx, "service233_db", "service233_data")
	if err != nil {
		return Service233Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id233},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service233Data{}, err
	}
	var service233Data Service233Data
	exists, err := res.One(ctx, &service233Data)
	if err != nil {
		return Service233Data{}, err
	}
	if exists {
		return service233Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service233DB.GetCollection(ctx, "service233_db", "service233_data")
	if err != nil {
		return Service233Data{}, err
	}
	service233Data = Service233Data{
		ID:   id233,
		DataOtherOther: data233,
	}
	if err := coll.InsertOne(ctx, service233Data); err != nil {
		return Service233Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service233DB.GetCollection(ctx, "service233_db", "service233_data")
	if err != nil {
		return Service233Data{}, err
	}
	service233Data = Service233Data{
		ID:   id233,
		DataOtherOtherTwo: datatwo233,
	}
	if err := coll.InsertOne(ctx, service233Data); err != nil {
		return Service233Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service234.MethodOtherOther234(ctx, id233, data233, datatwo233); err != nil {
		return Service233Data{}, err
	}

	return service233Data, nil
}
