// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service83Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service83 interface {
	Method83(ctx context.Context, id string, data string, datatwo string) (Service83Data, error)
	MethodOther83(ctx context.Context, id string, data string, datatwo string) (Service83Data, error)
	MethodOtherOther83(ctx context.Context, id string, data string, datatwo string) (Service83Data, error)
}

type Service83Impl struct {
	service83DB backend.NoSQLDatabase
	service84 Service84
}

func NewService83Impl(ctx context.Context, service83DB backend.NoSQLDatabase, service84 Service84) (Service83, error) {
	return &Service83Impl{
		service83DB: service83DB,
		service84: service84,
	}, nil
}

func (s *Service83Impl) Method83(ctx context.Context, id83 string, data83 string, datatwo83 string) (Service83Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service83DB.GetCollection(ctx, "service83_db", "service83_data")
	if err != nil {
		return Service83Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id83},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service83Data{}, err
	}
	var service83Data Service83Data
	exists, err := res.One(ctx, &service83Data)
	if err != nil {
		return Service83Data{}, err
	}
	if exists {
		return service83Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service83DB.GetCollection(ctx, "service83_db", "service83_data")
	if err != nil {
		return Service83Data{}, err
	}
	service83Data = Service83Data{
		ID:   id83,
		Data: data83,
	}
	if err := coll.InsertOne(ctx, service83Data); err != nil {
		return Service83Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service83DB.GetCollection(ctx, "service83_db", "service83_data")
	if err != nil {
		return Service83Data{}, err
	}
	service83Data = Service83Data{
		ID:   id83,
		DataTwo: datatwo83,
	}
	if err := coll.InsertOne(ctx, service83Data); err != nil {
		return Service83Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service84.Method84(ctx, id83, data83, datatwo83); err != nil {
		return Service83Data{}, err
	}

	return service83Data, nil
}

func (s *Service83Impl) MethodOther83(ctx context.Context, id83 string, data83 string, datatwo83 string) (Service83Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service83DB.GetCollection(ctx, "service83_db", "service83_data")
	if err != nil {
		return Service83Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id83},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service83Data{}, err
	}
	var service83Data Service83Data
	exists, err := res.One(ctx, &service83Data)
	if err != nil {
		return Service83Data{}, err
	}
	if exists {
		return service83Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service83DB.GetCollection(ctx, "service83_db", "service83_data")
	if err != nil {
		return Service83Data{}, err
	}
	service83Data = Service83Data{
		ID:   id83,
		DataOther: data83,
	}
	if err := coll.InsertOne(ctx, service83Data); err != nil {
		return Service83Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service83DB.GetCollection(ctx, "service83_db", "service83_data")
	if err != nil {
		return Service83Data{}, err
	}
	service83Data = Service83Data{
		ID:   id83,
		DataOtherTwo: datatwo83,
	}
	if err := coll.InsertOne(ctx, service83Data); err != nil {
		return Service83Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service84.MethodOther84(ctx, id83, data83, datatwo83); err != nil {
		return Service83Data{}, err
	}

	return service83Data, nil
}

func (s *Service83Impl) MethodOtherOther83(ctx context.Context, id83 string, data83 string, datatwo83 string) (Service83Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service83DB.GetCollection(ctx, "service83_db", "service83_data")
	if err != nil {
		return Service83Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id83},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service83Data{}, err
	}
	var service83Data Service83Data
	exists, err := res.One(ctx, &service83Data)
	if err != nil {
		return Service83Data{}, err
	}
	if exists {
		return service83Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service83DB.GetCollection(ctx, "service83_db", "service83_data")
	if err != nil {
		return Service83Data{}, err
	}
	service83Data = Service83Data{
		ID:   id83,
		DataOtherOther: data83,
	}
	if err := coll.InsertOne(ctx, service83Data); err != nil {
		return Service83Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service83DB.GetCollection(ctx, "service83_db", "service83_data")
	if err != nil {
		return Service83Data{}, err
	}
	service83Data = Service83Data{
		ID:   id83,
		DataOtherOtherTwo: datatwo83,
	}
	if err := coll.InsertOne(ctx, service83Data); err != nil {
		return Service83Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service84.MethodOtherOther84(ctx, id83, data83, datatwo83); err != nil {
		return Service83Data{}, err
	}

	return service83Data, nil
}
