// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service267Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service267 interface {
	Method267(ctx context.Context, id string, data string, datatwo string) (Service267Data, error)
	MethodOther267(ctx context.Context, id string, data string, datatwo string) (Service267Data, error)
	MethodOtherOther267(ctx context.Context, id string, data string, datatwo string) (Service267Data, error)
}

type Service267Impl struct {
	service267DB backend.NoSQLDatabase
	service268 Service268
}

func NewService267Impl(ctx context.Context, service267DB backend.NoSQLDatabase, service268 Service268) (Service267, error) {
	return &Service267Impl{
		service267DB: service267DB,
		service268: service268,
	}, nil
}

func (s *Service267Impl) Method267(ctx context.Context, id267 string, data267 string, datatwo267 string) (Service267Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service267DB.GetCollection(ctx, "service267_db", "service267_data")
	if err != nil {
		return Service267Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id267},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service267Data{}, err
	}
	var service267Data Service267Data
	exists, err := res.One(ctx, &service267Data)
	if err != nil {
		return Service267Data{}, err
	}
	if exists {
		return service267Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service267DB.GetCollection(ctx, "service267_db", "service267_data")
	if err != nil {
		return Service267Data{}, err
	}
	service267Data = Service267Data{
		ID:   id267,
		Data: data267,
	}
	if err := coll.InsertOne(ctx, service267Data); err != nil {
		return Service267Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service267DB.GetCollection(ctx, "service267_db", "service267_data")
	if err != nil {
		return Service267Data{}, err
	}
	service267Data = Service267Data{
		ID:   id267,
		DataTwo: datatwo267,
	}
	if err := coll.InsertOne(ctx, service267Data); err != nil {
		return Service267Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service268.Method268(ctx, id267, data267, datatwo267); err != nil {
		return Service267Data{}, err
	}

	return service267Data, nil
}

func (s *Service267Impl) MethodOther267(ctx context.Context, id267 string, data267 string, datatwo267 string) (Service267Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service267DB.GetCollection(ctx, "service267_db", "service267_data")
	if err != nil {
		return Service267Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id267},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service267Data{}, err
	}
	var service267Data Service267Data
	exists, err := res.One(ctx, &service267Data)
	if err != nil {
		return Service267Data{}, err
	}
	if exists {
		return service267Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service267DB.GetCollection(ctx, "service267_db", "service267_data")
	if err != nil {
		return Service267Data{}, err
	}
	service267Data = Service267Data{
		ID:   id267,
		DataOther: data267,
	}
	if err := coll.InsertOne(ctx, service267Data); err != nil {
		return Service267Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service267DB.GetCollection(ctx, "service267_db", "service267_data")
	if err != nil {
		return Service267Data{}, err
	}
	service267Data = Service267Data{
		ID:   id267,
		DataOtherTwo: datatwo267,
	}
	if err := coll.InsertOne(ctx, service267Data); err != nil {
		return Service267Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service268.MethodOther268(ctx, id267, data267, datatwo267); err != nil {
		return Service267Data{}, err
	}

	return service267Data, nil
}

func (s *Service267Impl) MethodOtherOther267(ctx context.Context, id267 string, data267 string, datatwo267 string) (Service267Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service267DB.GetCollection(ctx, "service267_db", "service267_data")
	if err != nil {
		return Service267Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id267},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service267Data{}, err
	}
	var service267Data Service267Data
	exists, err := res.One(ctx, &service267Data)
	if err != nil {
		return Service267Data{}, err
	}
	if exists {
		return service267Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service267DB.GetCollection(ctx, "service267_db", "service267_data")
	if err != nil {
		return Service267Data{}, err
	}
	service267Data = Service267Data{
		ID:   id267,
		DataOtherOther: data267,
	}
	if err := coll.InsertOne(ctx, service267Data); err != nil {
		return Service267Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service267DB.GetCollection(ctx, "service267_db", "service267_data")
	if err != nil {
		return Service267Data{}, err
	}
	service267Data = Service267Data{
		ID:   id267,
		DataOtherOtherTwo: datatwo267,
	}
	if err := coll.InsertOne(ctx, service267Data); err != nil {
		return Service267Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service268.MethodOtherOther268(ctx, id267, data267, datatwo267); err != nil {
		return Service267Data{}, err
	}

	return service267Data, nil
}
