// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service460Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service460 interface {
	Method460(ctx context.Context, id string, data string, datatwo string) (Service460Data, error)
	MethodOther460(ctx context.Context, id string, data string, datatwo string) (Service460Data, error)
	MethodOtherOther460(ctx context.Context, id string, data string, datatwo string) (Service460Data, error)
}

type Service460Impl struct {
	service460DB backend.NoSQLDatabase
	service461 Service461
}

func NewService460Impl(ctx context.Context, service460DB backend.NoSQLDatabase, service461 Service461) (Service460, error) {
	return &Service460Impl{
		service460DB: service460DB,
		service461: service461,
	}, nil
}

func (s *Service460Impl) Method460(ctx context.Context, id460 string, data460 string, datatwo460 string) (Service460Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service460DB.GetCollection(ctx, "service460_db", "service460_data")
	if err != nil {
		return Service460Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id460},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service460Data{}, err
	}
	var service460Data Service460Data
	exists, err := res.One(ctx, &service460Data)
	if err != nil {
		return Service460Data{}, err
	}
	if exists {
		return service460Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service460DB.GetCollection(ctx, "service460_db", "service460_data")
	if err != nil {
		return Service460Data{}, err
	}
	service460Data = Service460Data{
		ID:   id460,
		Data: data460,
	}
	if err := coll.InsertOne(ctx, service460Data); err != nil {
		return Service460Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service460DB.GetCollection(ctx, "service460_db", "service460_data")
	if err != nil {
		return Service460Data{}, err
	}
	service460Data = Service460Data{
		ID:   id460,
		DataTwo: datatwo460,
	}
	if err := coll.InsertOne(ctx, service460Data); err != nil {
		return Service460Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service461.Method461(ctx, id460, data460, datatwo460); err != nil {
		return Service460Data{}, err
	}

	return service460Data, nil
}

func (s *Service460Impl) MethodOther460(ctx context.Context, id460 string, data460 string, datatwo460 string) (Service460Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service460DB.GetCollection(ctx, "service460_db", "service460_data")
	if err != nil {
		return Service460Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id460},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service460Data{}, err
	}
	var service460Data Service460Data
	exists, err := res.One(ctx, &service460Data)
	if err != nil {
		return Service460Data{}, err
	}
	if exists {
		return service460Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service460DB.GetCollection(ctx, "service460_db", "service460_data")
	if err != nil {
		return Service460Data{}, err
	}
	service460Data = Service460Data{
		ID:   id460,
		DataOther: data460,
	}
	if err := coll.InsertOne(ctx, service460Data); err != nil {
		return Service460Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service460DB.GetCollection(ctx, "service460_db", "service460_data")
	if err != nil {
		return Service460Data{}, err
	}
	service460Data = Service460Data{
		ID:   id460,
		DataOtherTwo: datatwo460,
	}
	if err := coll.InsertOne(ctx, service460Data); err != nil {
		return Service460Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service461.MethodOther461(ctx, id460, data460, datatwo460); err != nil {
		return Service460Data{}, err
	}

	return service460Data, nil
}

func (s *Service460Impl) MethodOtherOther460(ctx context.Context, id460 string, data460 string, datatwo460 string) (Service460Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service460DB.GetCollection(ctx, "service460_db", "service460_data")
	if err != nil {
		return Service460Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id460},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service460Data{}, err
	}
	var service460Data Service460Data
	exists, err := res.One(ctx, &service460Data)
	if err != nil {
		return Service460Data{}, err
	}
	if exists {
		return service460Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service460DB.GetCollection(ctx, "service460_db", "service460_data")
	if err != nil {
		return Service460Data{}, err
	}
	service460Data = Service460Data{
		ID:   id460,
		DataOtherOther: data460,
	}
	if err := coll.InsertOne(ctx, service460Data); err != nil {
		return Service460Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service460DB.GetCollection(ctx, "service460_db", "service460_data")
	if err != nil {
		return Service460Data{}, err
	}
	service460Data = Service460Data{
		ID:   id460,
		DataOtherOtherTwo: datatwo460,
	}
	if err := coll.InsertOne(ctx, service460Data); err != nil {
		return Service460Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service461.MethodOtherOther461(ctx, id460, data460, datatwo460); err != nil {
		return Service460Data{}, err
	}

	return service460Data, nil
}
