// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service434Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service434 interface {
	Method434(ctx context.Context, id string, data string, datatwo string) (Service434Data, error)
	MethodOther434(ctx context.Context, id string, data string, datatwo string) (Service434Data, error)
	MethodOtherOther434(ctx context.Context, id string, data string, datatwo string) (Service434Data, error)
}

type Service434Impl struct {
	service434DB backend.NoSQLDatabase
	service435 Service435
}

func NewService434Impl(ctx context.Context, service434DB backend.NoSQLDatabase, service435 Service435) (Service434, error) {
	return &Service434Impl{
		service434DB: service434DB,
		service435: service435,
	}, nil
}

func (s *Service434Impl) Method434(ctx context.Context, id434 string, data434 string, datatwo434 string) (Service434Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service434DB.GetCollection(ctx, "service434_db", "service434_data")
	if err != nil {
		return Service434Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id434},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service434Data{}, err
	}
	var service434Data Service434Data
	exists, err := res.One(ctx, &service434Data)
	if err != nil {
		return Service434Data{}, err
	}
	if exists {
		return service434Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service434DB.GetCollection(ctx, "service434_db", "service434_data")
	if err != nil {
		return Service434Data{}, err
	}
	service434Data = Service434Data{
		ID:   id434,
		Data: data434,
	}
	if err := coll.InsertOne(ctx, service434Data); err != nil {
		return Service434Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service434DB.GetCollection(ctx, "service434_db", "service434_data")
	if err != nil {
		return Service434Data{}, err
	}
	service434Data = Service434Data{
		ID:   id434,
		DataTwo: datatwo434,
	}
	if err := coll.InsertOne(ctx, service434Data); err != nil {
		return Service434Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service435.Method435(ctx, id434, data434, datatwo434); err != nil {
		return Service434Data{}, err
	}

	return service434Data, nil
}

func (s *Service434Impl) MethodOther434(ctx context.Context, id434 string, data434 string, datatwo434 string) (Service434Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service434DB.GetCollection(ctx, "service434_db", "service434_data")
	if err != nil {
		return Service434Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id434},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service434Data{}, err
	}
	var service434Data Service434Data
	exists, err := res.One(ctx, &service434Data)
	if err != nil {
		return Service434Data{}, err
	}
	if exists {
		return service434Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service434DB.GetCollection(ctx, "service434_db", "service434_data")
	if err != nil {
		return Service434Data{}, err
	}
	service434Data = Service434Data{
		ID:   id434,
		DataOther: data434,
	}
	if err := coll.InsertOne(ctx, service434Data); err != nil {
		return Service434Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service434DB.GetCollection(ctx, "service434_db", "service434_data")
	if err != nil {
		return Service434Data{}, err
	}
	service434Data = Service434Data{
		ID:   id434,
		DataOtherTwo: datatwo434,
	}
	if err := coll.InsertOne(ctx, service434Data); err != nil {
		return Service434Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service435.MethodOther435(ctx, id434, data434, datatwo434); err != nil {
		return Service434Data{}, err
	}

	return service434Data, nil
}

func (s *Service434Impl) MethodOtherOther434(ctx context.Context, id434 string, data434 string, datatwo434 string) (Service434Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service434DB.GetCollection(ctx, "service434_db", "service434_data")
	if err != nil {
		return Service434Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id434},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service434Data{}, err
	}
	var service434Data Service434Data
	exists, err := res.One(ctx, &service434Data)
	if err != nil {
		return Service434Data{}, err
	}
	if exists {
		return service434Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service434DB.GetCollection(ctx, "service434_db", "service434_data")
	if err != nil {
		return Service434Data{}, err
	}
	service434Data = Service434Data{
		ID:   id434,
		DataOtherOther: data434,
	}
	if err := coll.InsertOne(ctx, service434Data); err != nil {
		return Service434Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service434DB.GetCollection(ctx, "service434_db", "service434_data")
	if err != nil {
		return Service434Data{}, err
	}
	service434Data = Service434Data{
		ID:   id434,
		DataOtherOtherTwo: datatwo434,
	}
	if err := coll.InsertOne(ctx, service434Data); err != nil {
		return Service434Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service435.MethodOtherOther435(ctx, id434, data434, datatwo434); err != nil {
		return Service434Data{}, err
	}

	return service434Data, nil
}
