// Code generated by gen_workflow.go
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service321Data struct {
	ID   string `bson:"id"`
	Data string `bson:"data"`
	DataTwo string `bson:"datatwo"`
	DataOther string `bson:"data_other"`
	DataOtherTwo string `bson:"datatwo_other"`
	DataOtherOther string `bson:"data_other_other"`
	DataOtherOtherTwo string `bson:"datatwo_other_other"`
}

type Service321 interface {
	Method321(ctx context.Context, id string, data string, datatwo string) (Service321Data, error)
	MethodOther321(ctx context.Context, id string, data string, datatwo string) (Service321Data, error)
	MethodOtherOther321(ctx context.Context, id string, data string, datatwo string) (Service321Data, error)
}

type Service321Impl struct {
	service321DB backend.NoSQLDatabase
	service322 Service322
}

func NewService321Impl(ctx context.Context, service321DB backend.NoSQLDatabase, service322 Service322) (Service321, error) {
	return &Service321Impl{
		service321DB: service321DB,
		service322: service322,
	}, nil
}

func (s *Service321Impl) Method321(ctx context.Context, id321 string, data321 string, datatwo321 string) (Service321Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service321DB.GetCollection(ctx, "service321_db", "service321_data")
	if err != nil {
		return Service321Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id321},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service321Data{}, err
	}
	var service321Data Service321Data
	exists, err := res.One(ctx, &service321Data)
	if err != nil {
		return Service321Data{}, err
	}
	if exists {
		return service321Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service321DB.GetCollection(ctx, "service321_db", "service321_data")
	if err != nil {
		return Service321Data{}, err
	}
	service321Data = Service321Data{
		ID:   id321,
		Data: data321,
	}
	if err := coll.InsertOne(ctx, service321Data); err != nil {
		return Service321Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service321DB.GetCollection(ctx, "service321_db", "service321_data")
	if err != nil {
		return Service321Data{}, err
	}
	service321Data = Service321Data{
		ID:   id321,
		DataTwo: datatwo321,
	}
	if err := coll.InsertOne(ctx, service321Data); err != nil {
		return Service321Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service322.Method322(ctx, id321, data321, datatwo321); err != nil {
		return Service321Data{}, err
	}

	return service321Data, nil
}

func (s *Service321Impl) MethodOther321(ctx context.Context, id321 string, data321 string, datatwo321 string) (Service321Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service321DB.GetCollection(ctx, "service321_db", "service321_data")
	if err != nil {
		return Service321Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id321},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service321Data{}, err
	}
	var service321Data Service321Data
	exists, err := res.One(ctx, &service321Data)
	if err != nil {
		return Service321Data{}, err
	}
	if exists {
		return service321Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service321DB.GetCollection(ctx, "service321_db", "service321_data")
	if err != nil {
		return Service321Data{}, err
	}
	service321Data = Service321Data{
		ID:   id321,
		DataOther: data321,
	}
	if err := coll.InsertOne(ctx, service321Data); err != nil {
		return Service321Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service321DB.GetCollection(ctx, "service321_db", "service321_data")
	if err != nil {
		return Service321Data{}, err
	}
	service321Data = Service321Data{
		ID:   id321,
		DataOtherTwo: datatwo321,
	}
	if err := coll.InsertOne(ctx, service321Data); err != nil {
		return Service321Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service322.MethodOther322(ctx, id321, data321, datatwo321); err != nil {
		return Service321Data{}, err
	}

	return service321Data, nil
}

func (s *Service321Impl) MethodOtherOther321(ctx context.Context, id321 string, data321 string, datatwo321 string) (Service321Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service321DB.GetCollection(ctx, "service321_db", "service321_data")
	if err != nil {
		return Service321Data{}, err
	}
	query := bson.D{
		{Key: "id", Value: id321},
	}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service321Data{}, err
	}
	var service321Data Service321Data
	exists, err := res.One(ctx, &service321Data)
	if err != nil {
		return Service321Data{}, err
	}
	if exists {
		return service321Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service321DB.GetCollection(ctx, "service321_db", "service321_data")
	if err != nil {
		return Service321Data{}, err
	}
	service321Data = Service321Data{
		ID:   id321,
		DataOtherOther: data321,
	}
	if err := coll.InsertOne(ctx, service321Data); err != nil {
		return Service321Data{}, err
	}

	// ----------------------- WRITE v2 -----------------------
	coll, err = s.service321DB.GetCollection(ctx, "service321_db", "service321_data")
	if err != nil {
		return Service321Data{}, err
	}
	service321Data = Service321Data{
		ID:   id321,
		DataOtherOtherTwo: datatwo321,
	}
	if err := coll.InsertOne(ctx, service321Data); err != nil {
		return Service321Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service322.MethodOtherOther322(ctx, id321, data321, datatwo321); err != nil {
		return Service321Data{}, err
	}

	return service321Data, nil
}
