// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service47Data struct {
	id   string
	data string
}

type Service47 interface {
	Method47(ctx context.Context, id string, data string) (Service47Data, error)
}

type Service47Impl struct {
	service47DB backend.NoSQLDatabase
	service48   Service48
}

func NewService47Impl(ctx context.Context, service47DB backend.NoSQLDatabase, service48 Service48) (Service47, error) {
	return &Service47Impl{
		service47DB: service47DB,
		service48:   service48,
	}, nil
}

func (s *Service47Impl) Method47(ctx context.Context, id47 string, data47 string) (Service47Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service47DB.GetCollection(ctx, "service47_db", "service47_data")
	if err != nil {
		return Service47Data{}, err
	}
	query := bson.D{{Key: "id", Value: id47}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service47Data{}, err
	}
	var service47Data Service47Data
	exists, err := res.One(ctx, &service47Data)
	if err != nil {
		return Service47Data{}, err
	}
	if exists {
		return service47Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service47DB.GetCollection(ctx, "service47_db", "service47_data")
	if err != nil {
		return Service47Data{}, err
	}
	service47Data = Service47Data{
		id:   id47,
		data: data47,
	}
	if err := coll.InsertOne(ctx, service47Data); err != nil {
		return Service47Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service48.Method48(ctx, id47, data47); err != nil {
		return Service47Data{}, err
	}

	return service47Data, nil
}
