// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service24Data struct {
	id   string
	data string
}

type Service24 interface {
	Method24(ctx context.Context, id string, data string) (Service24Data, error)
}

type Service24Impl struct {
	service24DB backend.NoSQLDatabase
	service25   Service25
}

func NewService24Impl(ctx context.Context, service24DB backend.NoSQLDatabase, service25 Service25) (Service24, error) {
	return &Service24Impl{
		service24DB: service24DB,
		service25:   service25,
	}, nil
}

func (s *Service24Impl) Method24(ctx context.Context, id24 string, data24 string) (Service24Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service24DB.GetCollection(ctx, "service24_db", "service24_data")
	if err != nil {
		return Service24Data{}, err
	}
	query := bson.D{{Key: "id", Value: id24}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service24Data{}, err
	}
	var service24Data Service24Data
	exists, err := res.One(ctx, &service24Data)
	if err != nil {
		return Service24Data{}, err
	}
	if exists {
		return service24Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service24DB.GetCollection(ctx, "service24_db", "service24_data")
	if err != nil {
		return Service24Data{}, err
	}
	service24Data = Service24Data{
		id:   id24,
		data: data24,
	}
	if err := coll.InsertOne(ctx, service24Data); err != nil {
		return Service24Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service25.Method25(ctx, id24, data24); err != nil {
		return Service24Data{}, err
	}

	return service24Data, nil
}
