// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service98Data struct {
	id   string
	data string
}

type Service98 interface {
	Method98(ctx context.Context, id string, data string) (Service98Data, error)
}

type Service98Impl struct {
	service98DB backend.NoSQLDatabase
	service99   Service99
}

func NewService98Impl(ctx context.Context, service98DB backend.NoSQLDatabase, service99 Service99) (Service98, error) {
	return &Service98Impl{
		service98DB: service98DB,
		service99:   service99,
	}, nil
}

func (s *Service98Impl) Method98(ctx context.Context, id98 string, data98 string) (Service98Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service98DB.GetCollection(ctx, "service98_db", "service98_data")
	if err != nil {
		return Service98Data{}, err
	}
	query := bson.D{{Key: "id", Value: id98}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service98Data{}, err
	}
	var service98Data Service98Data
	exists, err := res.One(ctx, &service98Data)
	if err != nil {
		return Service98Data{}, err
	}
	if exists {
		return service98Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service98DB.GetCollection(ctx, "service98_db", "service98_data")
	if err != nil {
		return Service98Data{}, err
	}
	service98Data = Service98Data{
		id:   id98,
		data: data98,
	}
	if err := coll.InsertOne(ctx, service98Data); err != nil {
		return Service98Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service99.Method99(ctx, id98, data98); err != nil {
		return Service98Data{}, err
	}

	return service98Data, nil
}
