// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service62Data struct {
	id   string
	data string
}

type Service62 interface {
	Method62(ctx context.Context, id string, data string) (Service62Data, error)
}

type Service62Impl struct {
	service62DB backend.NoSQLDatabase
	service63   Service63
}

func NewService62Impl(ctx context.Context, service62DB backend.NoSQLDatabase, service63 Service63) (Service62, error) {
	return &Service62Impl{
		service62DB: service62DB,
		service63:   service63,
	}, nil
}

func (s *Service62Impl) Method62(ctx context.Context, id62 string, data62 string) (Service62Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service62DB.GetCollection(ctx, "service62_db", "service62_data")
	if err != nil {
		return Service62Data{}, err
	}
	query := bson.D{{Key: "id", Value: id62}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service62Data{}, err
	}
	var service62Data Service62Data
	exists, err := res.One(ctx, &service62Data)
	if err != nil {
		return Service62Data{}, err
	}
	if exists {
		return service62Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service62DB.GetCollection(ctx, "service62_db", "service62_data")
	if err != nil {
		return Service62Data{}, err
	}
	service62Data = Service62Data{
		id:   id62,
		data: data62,
	}
	if err := coll.InsertOne(ctx, service62Data); err != nil {
		return Service62Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service63.Method63(ctx, id62, data62); err != nil {
		return Service62Data{}, err
	}

	return service62Data, nil
}
