// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service3Data struct {
	id   string
	data string
}

type Service3 interface {
	Method3(ctx context.Context, id string, data string) (Service3Data, error)
}

type Service3Impl struct {
	service3DB backend.NoSQLDatabase
	service4   Service4
}

func NewService3Impl(ctx context.Context, service3DB backend.NoSQLDatabase, service4 Service4) (Service3, error) {
	return &Service3Impl{
		service3DB: service3DB,
		service4:   service4,
	}, nil
}

func (s *Service3Impl) Method3(ctx context.Context, id3 string, data3 string) (Service3Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service3DB.GetCollection(ctx, "service3_db", "service3_data")
	if err != nil {
		return Service3Data{}, err
	}
	query := bson.D{{Key: "id", Value: id3}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service3Data{}, err
	}
	var service3Data Service3Data
	exists, err := res.One(ctx, &service3Data)
	if err != nil {
		return Service3Data{}, err
	}
	if exists {
		return service3Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service3DB.GetCollection(ctx, "service3_db", "service3_data")
	if err != nil {
		return Service3Data{}, err
	}
	service3Data = Service3Data{
		id:   id3,
		data: data3,
	}
	if err := coll.InsertOne(ctx, service3Data); err != nil {
		return Service3Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service4.Method4(ctx, id3, data3); err != nil {
		return Service3Data{}, err
	}

	return service3Data, nil
}
