// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service91Data struct {
	id   string
	data string
}

type Service91 interface {
	Method91(ctx context.Context, id string, data string) (Service91Data, error)
}

type Service91Impl struct {
	service91DB backend.NoSQLDatabase
	service92   Service92
}

func NewService91Impl(ctx context.Context, service91DB backend.NoSQLDatabase, service92 Service92) (Service91, error) {
	return &Service91Impl{
		service91DB: service91DB,
		service92:   service92,
	}, nil
}

func (s *Service91Impl) Method91(ctx context.Context, id91 string, data91 string) (Service91Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service91DB.GetCollection(ctx, "service91_db", "service91_data")
	if err != nil {
		return Service91Data{}, err
	}
	query := bson.D{{Key: "id", Value: id91}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service91Data{}, err
	}
	var service91Data Service91Data
	exists, err := res.One(ctx, &service91Data)
	if err != nil {
		return Service91Data{}, err
	}
	if exists {
		return service91Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service91DB.GetCollection(ctx, "service91_db", "service91_data")
	if err != nil {
		return Service91Data{}, err
	}
	service91Data = Service91Data{
		id:   id91,
		data: data91,
	}
	if err := coll.InsertOne(ctx, service91Data); err != nil {
		return Service91Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service92.Method92(ctx, id91, data91); err != nil {
		return Service91Data{}, err
	}

	return service91Data, nil
}
