// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service87Data struct {
	id   string
	data string
}

type Service87 interface {
	Method87(ctx context.Context, id string, data string) (Service87Data, error)
}

type Service87Impl struct {
	service87DB backend.NoSQLDatabase
	service88   Service88
}

func NewService87Impl(ctx context.Context, service87DB backend.NoSQLDatabase, service88 Service88) (Service87, error) {
	return &Service87Impl{
		service87DB: service87DB,
		service88:   service88,
	}, nil
}

func (s *Service87Impl) Method87(ctx context.Context, id87 string, data87 string) (Service87Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service87DB.GetCollection(ctx, "service87_db", "service87_data")
	if err != nil {
		return Service87Data{}, err
	}
	query := bson.D{{Key: "id", Value: id87}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service87Data{}, err
	}
	var service87Data Service87Data
	exists, err := res.One(ctx, &service87Data)
	if err != nil {
		return Service87Data{}, err
	}
	if exists {
		return service87Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service87DB.GetCollection(ctx, "service87_db", "service87_data")
	if err != nil {
		return Service87Data{}, err
	}
	service87Data = Service87Data{
		id:   id87,
		data: data87,
	}
	if err := coll.InsertOne(ctx, service87Data); err != nil {
		return Service87Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service88.Method88(ctx, id87, data87); err != nil {
		return Service87Data{}, err
	}

	return service87Data, nil
}
