// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service17Data struct {
	id   string
	data string
}

type Service17 interface {
	Method17(ctx context.Context, id string, data string) (Service17Data, error)
}

type Service17Impl struct {
	service17DB backend.NoSQLDatabase
	service18   Service18
}

func NewService17Impl(ctx context.Context, service17DB backend.NoSQLDatabase, service18 Service18) (Service17, error) {
	return &Service17Impl{
		service17DB: service17DB,
		service18:   service18,
	}, nil
}

func (s *Service17Impl) Method17(ctx context.Context, id17 string, data17 string) (Service17Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service17DB.GetCollection(ctx, "service17_db", "service17_data")
	if err != nil {
		return Service17Data{}, err
	}
	query := bson.D{{Key: "id", Value: id17}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service17Data{}, err
	}
	var service17Data Service17Data
	exists, err := res.One(ctx, &service17Data)
	if err != nil {
		return Service17Data{}, err
	}
	if exists {
		return service17Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service17DB.GetCollection(ctx, "service17_db", "service17_data")
	if err != nil {
		return Service17Data{}, err
	}
	service17Data = Service17Data{
		id:   id17,
		data: data17,
	}
	if err := coll.InsertOne(ctx, service17Data); err != nil {
		return Service17Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service18.Method18(ctx, id17, data17); err != nil {
		return Service17Data{}, err
	}

	return service17Data, nil
}
