// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service13Data struct {
	id   string
	data string
}

type Service13 interface {
	Method13(ctx context.Context, id string, data string) (Service13Data, error)
}

type Service13Impl struct {
	service13DB backend.NoSQLDatabase
	service14   Service14
}

func NewService13Impl(ctx context.Context, service13DB backend.NoSQLDatabase, service14 Service14) (Service13, error) {
	return &Service13Impl{
		service13DB: service13DB,
		service14:   service14,
	}, nil
}

func (s *Service13Impl) Method13(ctx context.Context, id13 string, data13 string) (Service13Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service13DB.GetCollection(ctx, "service13_db", "service13_data")
	if err != nil {
		return Service13Data{}, err
	}
	query := bson.D{{Key: "id", Value: id13}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service13Data{}, err
	}
	var service13Data Service13Data
	exists, err := res.One(ctx, &service13Data)
	if err != nil {
		return Service13Data{}, err
	}
	if exists {
		return service13Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service13DB.GetCollection(ctx, "service13_db", "service13_data")
	if err != nil {
		return Service13Data{}, err
	}
	service13Data = Service13Data{
		id:   id13,
		data: data13,
	}
	if err := coll.InsertOne(ctx, service13Data); err != nil {
		return Service13Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service14.Method14(ctx, id13, data13); err != nil {
		return Service13Data{}, err
	}

	return service13Data, nil
}
