// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service20Data struct {
	id   string
	data string
}

type Service20 interface {
	Method20(ctx context.Context, id string, data string) (Service20Data, error)
}

type Service20Impl struct {
	service20DB backend.NoSQLDatabase
	service21   Service21
}

func NewService20Impl(ctx context.Context, service20DB backend.NoSQLDatabase, service21 Service21) (Service20, error) {
	return &Service20Impl{
		service20DB: service20DB,
		service21:   service21,
	}, nil
}

func (s *Service20Impl) Method20(ctx context.Context, id20 string, data20 string) (Service20Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service20DB.GetCollection(ctx, "service20_db", "service20_data")
	if err != nil {
		return Service20Data{}, err
	}
	query := bson.D{{Key: "id", Value: id20}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service20Data{}, err
	}
	var service20Data Service20Data
	exists, err := res.One(ctx, &service20Data)
	if err != nil {
		return Service20Data{}, err
	}
	if exists {
		return service20Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service20DB.GetCollection(ctx, "service20_db", "service20_data")
	if err != nil {
		return Service20Data{}, err
	}
	service20Data = Service20Data{
		id:   id20,
		data: data20,
	}
	if err := coll.InsertOne(ctx, service20Data); err != nil {
		return Service20Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service21.Method21(ctx, id20, data20); err != nil {
		return Service20Data{}, err
	}

	return service20Data, nil
}
