// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service76Data struct {
	id   string
	data string
}

type Service76 interface {
	Method76(ctx context.Context, id string, data string) (Service76Data, error)
}

type Service76Impl struct {
	service76DB backend.NoSQLDatabase
	service77   Service77
}

func NewService76Impl(ctx context.Context, service76DB backend.NoSQLDatabase, service77 Service77) (Service76, error) {
	return &Service76Impl{
		service76DB: service76DB,
		service77:   service77,
	}, nil
}

func (s *Service76Impl) Method76(ctx context.Context, id76 string, data76 string) (Service76Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service76DB.GetCollection(ctx, "service76_db", "service76_data")
	if err != nil {
		return Service76Data{}, err
	}
	query := bson.D{{Key: "id", Value: id76}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service76Data{}, err
	}
	var service76Data Service76Data
	exists, err := res.One(ctx, &service76Data)
	if err != nil {
		return Service76Data{}, err
	}
	if exists {
		return service76Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service76DB.GetCollection(ctx, "service76_db", "service76_data")
	if err != nil {
		return Service76Data{}, err
	}
	service76Data = Service76Data{
		id:   id76,
		data: data76,
	}
	if err := coll.InsertOne(ctx, service76Data); err != nil {
		return Service76Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service77.Method77(ctx, id76, data76); err != nil {
		return Service76Data{}, err
	}

	return service76Data, nil
}
