// Code generated by gen_workflow.go
		
package large_scale_app

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.mongodb.org/mongo-driver/bson"
)

type Service99Data struct {
	id   string
	data string
}

type Service99 interface {
	Method99(ctx context.Context, id string, data string) (Service99Data, error)
}

type Service99Impl struct {
	service99DB backend.NoSQLDatabase
	service100   Service100
}

func NewService99Impl(ctx context.Context, service99DB backend.NoSQLDatabase, service100 Service100) (Service99, error) {
	return &Service99Impl{
		service99DB: service99DB,
		service100:   service100,
	}, nil
}

func (s *Service99Impl) Method99(ctx context.Context, id99 string, data99 string) (Service99Data, error) {
	// ----------------------- READ -----------------------
	coll, err := s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	query := bson.D{{Key: "id", Value: id99}}
	res, err := coll.FindOne(ctx, query)
	if err != nil {
		return Service99Data{}, err
	}
	var service99Data Service99Data
	exists, err := res.One(ctx, &service99Data)
	if err != nil {
		return Service99Data{}, err
	}
	if exists {
		return service99Data, nil
	}

	// ----------------------- WRITE -----------------------
	coll, err = s.service99DB.GetCollection(ctx, "service99_db", "service99_data")
	if err != nil {
		return Service99Data{}, err
	}
	service99Data = Service99Data{
		id:   id99,
		data: data99,
	}
	if err := coll.InsertOne(ctx, service99Data); err != nil {
		return Service99Data{}, err
	}

	// call the next service in the chain
	if _, err := s.service100.Method100(ctx, id99, data99); err != nil {
		return Service99Data{}, err
	}

	return service99Data, nil
}
